### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by ThomDietrich**
Enjoy!

WIP do not merge.

### CODE REVIEW

**Comment by hakan42** [comment]
Could you convince your tools to add a trailing newline?

**Comment by ThomDietrich** [comment]
Sorry for the fuzz. This is a first test of crowdin for localization of the dashboard and the homebuilder. The crowdin export behaved a bit different as I know from previous tests.

DO NOT MERGE (obviously)

@hakan42 I feel you, not sure if they offer such an option.

I'm currently more confused that "Skip untranslated strings" results in empty strings in the json files.
Crowdin offers two approaches to the issue of incomplete translations. Either the main (english) string is inserted in all translation files or the key is left out. In other words: Either the translation files (managed by crowdin) handle incomplete translations for the applications or the application does so. I opted for the latter.
Leaving keys out works quite well in the properties files but no so much in the json files. Here empty strings are inserted. @kubawolanin can you make sense of that? How does the HomeBuilder handle missing translations?

Everyone: Despite the getting-started issues with the GitHub export, the Crowdin project is live and you may add your translations, please do 🙇 https://crowdin.com/project/openhab

**Comment by kubawolanin** [comment]
This is so awesome! 😀 
I wish we had it in openhab2-addons and ESH repos. I'd translate the hell out of it :D 
Thank you Thomas!

**Comment by ThomDietrich** [comment]
It was fun watching you adding strings all over the place 😄 

I think it is a but weird, that all commits are created in my name. Maybe in future an "openHAB translation bot" account should do that.

**Comment by kubawolanin** [comment]
>  How does the HomeBuilder handle missing translations?

Well, not very well. It'll treat them as truthy strings, thus display them empty.
What's more, when you have some translations in place, you'll need to add them to [definitions.js](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.ui.homebuilder/web/src/definitions.js) as well.

**Comment by martinvw** [comment]
Is it ready now? It looks mergeable imho.

**Comment by ThomDietrich** [comment]
No. Two issues currently:

1. The wrong interpretation of `warn.exposed`, which in return destroys the already translated strings. This will be fixed by #245 and correction of the translated strings afterwards.

2. The empty key:value pairs in the json files. I'm going to contact the crowdin support regarding this. @kubawolanin would it be possible for you to handle empty value strings like missing key:value pairs in the HomeBuilder code?

**Comment by ThomDietrich** [comment]
Issue 1 looks much better now.
@lolodomo could you please check if the new crowdin-generated french properties file still generates the correct results in the UI? Changes are 1) the unicode symbols, 2) the single quote escape by `''` and 3) the newline character in `warn.exposed` (not sure about this one...) Thanks!

**Comment by ThomDietrich** [comment]
First response by crowdin support: 

> Hello Thomas,
> Your idea seems interesting, so I will discuss such an improvement with devs.
> I can't promise the solution right now but if devs team agree to adjust the export, I will let you know at once. Thanks!

cc @kubawolanin

**Comment by kubawolanin** [comment]
Hey @ThomDietrich! I'll look at the possible solution soon. Will let you know when there's a progress on my side.

**Comment by lolodomo** [comment]
I will have a look.

**Comment by ThomDietrich** [comment]
Another answer by crowdin:

> Just a quick follow up regarding "Skip untranslated strings" issue.
> As I was told by developers, it is known export behavior for JSON format files. I'm sorry to say that we cannot simply trim the keys completely (like in Android XML, .properties etc.) due to some technical reasons. As you may know, the JSON files may have a nested structure and removing keys may lead to some undesirable consequences and corrupt the export.
> 
> Really hope that the current behavior won't cause a lot of inconveniences for you.
> Should you have any other questions, you are always welcome to contact us. We are here for you.

@kubawolanin this is a bit disappointing but I'm sure we can handle empty strings, can we?

**Comment by kubawolanin** [comment]
@ThomDietrich we'll need to prefetch English strings on load and use them in case there's something missing in the translation file.
Although I see that there is still some manual work needed, as the completed translations need to be declared in `definitions.js` file. I'll maintain that part if there's a new language completed for HomeBuilder so each time there are files to add, I'll check if they're valid (not empty I mean) as well.
Best regards

**Comment by ThomDietrich** [comment]
@kubawolanin agreed. Your algorithm should check for one string: if a locale file is available AND the file includes that key AND the value assigned to that key is not "" THEN return value ELSE return value from english translations file.

Wrt this PR, how do you want to proceed?

**Comment by kubawolanin** [comment]
Hmm turns out that [vue-i18n](https://kazupon.github.io/vue-i18n/en/fallback.html) got us covered ;-)
I've just tested the scenario you've described - simply removed value from "Window" key in Polish translation file. Result:

image

So no work on my side at the moment :-)
Later on I'll think how I can dynamically add languages to `definitions.js` based on the files structure (files in /i18n/ that is).

**Comment by ThomDietrich** [comment]
@kubawolanin looks good! Please clarify "removed". Would everything work as expected if the PR as it is right now was merged?

@lolodomo @kaikreuzer may I ask for your opinion regarding what I said above? I feel we should split up strings and remove HTML as much as possible, especially as [urls and magic strings are involved](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.ui.dashboard/ESH-INF/i18n/dashboard.properties). I'd like to agree on a solution first before going further with asking for translations in the community.

* Split `setup.check-doc`
* Split `common.getting-started`
* Split `warn.exposed` into multiple parts
* Use `text-transform: uppercase;` instead of uppercase letters in `warn.exposed`

If you agree, your help with that change would be highly appreciated!

**Comment by ThomDietrich** [comment]
@kubawolanin another answer from the crowdin team:

> Hello Thomas,
>
> I've discussed your inquiry about null vallue with the developers but as I was told, currently there are no plans to change the behavior since it may affect other users' workflow and files export. Sincerely hope for your understanding.
>
> The idea that comes to my mind is using a Chrome JSON file format, kindly see the sample in the attachment. The option "Skip untranslated strings" works perfectly here and on the export, the untranslated strings will be completely removed. By the day, the Chrome JSON allow the possibility to add the description to your source strings, thus your translators see the additional contextual information for translations. Probably this workaround will work fine for you?

```json
{
  "1": {
    "message": "string for translation.",
    "description": "some context"
  },
  "2": {
    "message": "String number two.",
    "description": "some context"
  },
  "3": {
    "message": "String number three.",
    "description": "some context"
  },
  "4": {
    "message": "String number four.",
    "description": 4
  }
}
```

**Comment by ThomDietrich** [comment]
@kaikreuzer do we want to push this for 2.2? I would like to invite people to add translations as soon as possible but also wanted to resolve the issues from above first. Currently waiting for you guys...

**Comment by kubawolanin** [comment]
@ThomDietrich 

> Please clarify "removed". Would everything work as expected if the PR as it is right now was merged?

I've tested empty nodes (keys without any values) as well as no keys at all. Everything worked as expected so I would tell that we're good with merging.

Cheers

**Comment by martinvw** [comment]
@lolodomo where you able to test the translations with the escaped unicode symbols?

**Comment by lolodomo** [comment]
No sorry.

**Comment by kaikreuzer** [comment]
> @kaikreuzer do we want to push this for 2.2?

No, definitely not. If we have that in place after the release and start inviting people then, this should imho be early enough.
When inviting people, it might make sense to also have other parts than openhab-core addressed already.
I myself also didn't yet have the time (and won't have it before the release) how this all works in detail. I am a bit concerned that we will put heavy load on ourselves in all refactoring situations, i.e. if keys get renamed, new/changed lists are defined, etc. Maybe CrowdIn makes this all easy, but I have no idea about that.

**Comment by ThomDietrich** [comment]
Fine with me. This way we don't have to rush anything and can collect and approve translations.

I had the chance to test crowdin the last couple of days and it offers a few nice features which should make managing translations in the long run easier/possible.

I agree, it would be good to manage most (translatable) openHAB projects there. Let's go at it step by step.

**Comment by ThomDietrich** [comment]
PR will be replaced by a new one. Translations are not lost!

**Pull request closed without merging**
