### PR TITLE
Fix build by wrapping lines

### PR DESCRIPTION
**Pull request by wborn**
Caused by #1713

### CODE REVIEW

**Review by kaikreuzer — APPROVED** [review]
Thanks, you were one minute faster than me ;-)

**Comment by wborn** [comment]
Because the Spotless XML wrapping is buggy, it will likely have a strange opinion about last minute [changes](https://github.com/openhab/openhab-core/pull/1713/commits/0c9d04494645b41b45b09048d439c35c182f7fae). :wink: 
I still need to check if there is already an issue for it in the Spotless issue tracker (and create one if missing). This buggy behavior can do serious damage (https://github.com/openhab/openhab-addons/pull/8413/) and is a source of unnecessary work, waiting and discussions. Maybe @nedtwigg knows if there is an existing issue for this?

**Comment by nedtwigg** [comment]
I maintain the Spotless core, but I haven't used the XML formatter myself.  I see that lines are being rewrapped, but that seems like expected behavior.  Is the bug that you don't want Spotless to care about line wrapping?  Or is Spotless being inconsistent about it, where it passes in one place but fails in another?

**Comment by wborn** [comment]
I've created https://github.com/diffplug/spotless/issues/723 for this @nedtwigg. :-)

**Pull request merged**
