### PR TITLE
improved addons parent pom

### PR DESCRIPTION
**Pull request by kaikreuzer**
- removed reference to openhab-core bom
- added required dependencies to core bundles
- removed Artifactory snapshot release

Related to https://github.com/openhab/openhab-core/pull/529#issuecomment-460750940

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
> If I remove the reference to the parent, is there any other solution than to duplicate the dependency list?

You just need a dependency to the bom.openhab-core POM:

```xml
  <dependency>
    <groupId>org.openhab.core.bom</groupId>
    <artifactId>org.openhab.core.bom.openhab-core</artifactId>
    <version>2.5.0-SNAPSHOT</version>
    <type>pom</type>
  </dependency>
```

All transitive dependencies (all the openHAB Core bundles) will be added to the dependency chain.

**Comment by kaikreuzer** [comment]
Confirmed working, so I'll self merge as you have approved. Thanks!

**Comment by kaikreuzer** [comment]
Hm, it worked locally for me, but [Jenkins has a problem](https://ci.openhab.org/job/openHAB2-Bundles/548/console) :-( .
Any idea, why it cannot resolve this package? Tycho is configured to consider pom dependencies (and as far as I have understood, it should also consider transitive dependencies)...

**Comment by maggu2810** [comment]
> [WARNING] Could not transfer metadata org.openhab:pom:2.5.0-SNAPSHOT/maven-metadata.xml from/to p2-openhab-deps-repo (https://ci.openhab.org/artifactory/libs-snapshot): Cannot access https://ci.openhab.org/artifactory/libs-snapshot with type p2 using the available connector factories: BasicRepositoryConnectorFactory

Why does Jenkins try to access a Maven repository with type p2?

**Comment by maggu2810** [comment]
On my machine:

> [WARNING] Could not transfer metadata org.openhab:pom-tycho:2.5.0-SNAPSHOT/maven-metadata.xml from/to p2-smarthome-snapshot (https://openhab.jfrog.io/openhab/eclipse-smarthome-stable): Cannot access https://openhab.jfrog.io/openhab/eclipse-smarthome-stable with type p2 using the available connector factories: BasicRepositoryConnectorFactory

**Comment by maggu2810** [comment]
Have you tried using the Maven parameter `-U`?

**Comment by maggu2810** [comment]
Hm, at least the "ZigBee" one looks good.

```
rm -rf ~/.m2/repository/org/openhab/
mvn clean install -U
```

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ZigBee Binding Parent POM 2.5.0-SNAPSHOT:
[INFO] 
[INFO] ZigBee Binding Parent POM .......................... SUCCESS [  0.797 s]
[INFO] ZigBee Binding ..................................... SUCCESS [ 52.748 s]
[INFO] ZigBee Ember Bridge ................................ SUCCESS [  9.164 s]
[INFO] ZigBee Telegesis Bridge ............................ SUCCESS [  7.500 s]
[INFO] ZigBee CC2531 Bridge ............................... SUCCESS [  6.001 s]
[INFO] ZigBee XBee Bridge ................................. SUCCESS [  5.509 s]
[INFO] ZigBee Binding Console ............................. SUCCESS [  7.390 s]
[INFO] ZigBee Binding Console Ember ....................... SUCCESS [  6.562 s]
[INFO] ZigBee Binding Console Telegesis ................... SUCCESS [  4.871 s]
[INFO] org.openhab.binding.zigbee.p2repo .................. SUCCESS [  0.040 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:09 min
[INFO] Finished at: 2019-02-06T16:07:29+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by kaikreuzer** [comment]
> Have you tried to use the Maven parameter `-U` on the Jenkins instance?

Yes.

> Hm, at least the "ZigBee" one looks good.

Also the openhab2-addons build works for me locally, that's the weird thing 🙄.

**Comment by kaikreuzer** [comment]
I can now reproduce it using the openhab-bundles project (which builds core and addons together):
```
git clone https://github.com/openhab/openhab-bundles/
cd openhab-bundles
git submodule update --init --recursive
git submodule foreach --recursive git checkout master
mvn clean install
```
So I guess the problem somehow comes from the fact that it is built in the same reactor. Do you understand why?

**Comment by maggu2810** [comment]
I assume you blow up the classpath mixing different staff into one runtime.

> This repository is only a mean to aggregate different other repositories for the build and release process of openHAB.

May I ask why you did it this way?

Wouldn't it be much simpler to create different Jenkins jobs for the different project?
If the "core" job finishes successfully it will trigger a rebuild "bindings", "addons" and "uis".

All jobs could be configured to use the same local Maven repository and the same external snapshot repository to publish and consume openHAB artifacts.

**Comment by maggu2810** [comment]
This will also eliminate problems like this: openhab/openhab-bundles#4

It complicates  the whole build setup if you try to build all different located bundles in one step.

I don't see any reason for it. At least not if you can use the powerful Jenkins infrastructure.
But also without that infrastructure a script could call the different builds one after the other.

**Comment by maggu2810** [comment]
The version of the parent is wrong:

```
    <parent>
        <groupId>org.openhab</groupId>
        <artifactId>pom-tycho</artifactId>
        <version>2.1.0-SNAPSHOT</version>
        <relativePath></relativePath>
    </parent>

    <groupId>org.openhab</groupId>
    <artifactId>pom-addons2</artifactId>
    <name>openHAB 2 Add-ons</name>
```

**Comment by maggu2810** [comment]
Hm, I see a lot of 2.1.0-SNAPSHOTS in the reactor.
Do I need to do something else then your commands above.

**Comment by maggu2810** [comment]
Because I know you will run into another problem:
If you change the parent version to use the current "pom-tycho" there is a "big" problem:

You cannot set the "relativePath" that is works for building openHAB addons alone and the whole bundle reactor.
If the "pom-tycho" POM cannot be resolved locally, it will be looked up in a remote repository.

But if fetch "pom-tycho" from a remote repository it is not the same that is part of your reactor (because snapshots can change all the time).

**Comment by kaikreuzer** [comment]
That was to simplify the overall build setup when the number of repos was growing - it should mimick a single repo build.

> Hm, I see a lot of 2.1.0-SNAPSHOTS in the reactor.

Sounds like you didn't pull the masters of the submodules. Are you sure that you executed the steps I gave in https://github.com/openhab/openhab-core/pull/536#issuecomment-461175368?

But nevermind, I have removed openhab-core from the openhab-bundles parent pom now and configured Jenkins to run two separate Maven builds - this solves the issue.

**Comment by maggu2810** [comment]
> Sounds like you didn't pull the masters of the submodules. Are you sure that you executed the steps I gave in [#536 (comment)](https://github.com/openhab/openhab-core/pull/536#issuecomment-461175368)?

I added the exact list of commands to the issue in the other repo.


> this solves the issue.

:+1:

**Pull request merged**
