### PR TITLE
PersistenceExtensions: fix DateTimeException when persisting an empty TimeSeries

### PR DESCRIPTION
**Pull request by holgerfriedrich**
backport of #4303 to 4.2.x series, regression from #4298

### CODE REVIEW

**Comment by jlaur** [comment]
@holgerfriedrich - usually commits are cherry-picked into patch branches.

**Comment by J-N-K** [comment]
No need for a PR. You can just cherry-pick the commit to the 4.2.x branch and push it. You should have sufficient write-access to do that.

**Comment by holgerfriedrich** [comment]
@jlaur @J-N-K I did not know how to do it. Thanks @J-N-K, I will try later today.

**Comment by jlaur** [comment]
@holgerfriedrich - just in case it can be useful for you: https://github.com/openhab/openhab-addons/pull/15329#issuecomment-1658595092

**Comment by holgerfriedrich** [comment]
> @holgerfriedrich - just in case it can be useful for you: [openhab/openhab-addons#15329 (comment)](https://github.com/openhab/openhab-addons/pull/15329#issuecomment-1658595092)

Thanks, @jlaur. I have put it into the add-ons wiki https://github.com/openhab/openhab-addons/wiki/Backporting (as we don't have a wiki for core).

**Pull request closed without merging**
