### PR TITLE
add further tests

### PR DESCRIPTION
**Pull request by maggu2810**
* io.net
* voice
* config.discovery
* ui
* ui.icon
* transform
* thing.xml
* io.rest.core

### CODE REVIEW

**Comment by maggu2810** [comment]
> We do not merge our own prs unless approved by another maintainer

This one has been approved by another maintainer, but I don't like merging my own PRs.

@kaikreuzer Can you give it a go?

**Comment by maggu2810** [comment]
Please use the "Rebase and merge" strategy to keep the commits separated.

**Comment by maggu2810** [comment]
I will stop adding further tests for the moment and so other commits to this PR -- otherwise it will be a never ending story.

**Comment by maggu2810** [comment]
> Please use the "Rebase and merge" strategy to keep the commits separated.

Any reason to not keep the commits separated as requested?

**Comment by kaikreuzer** [comment]
Because I didn't read it carefully enough, sorry.
Feel free to quickly rewrite history and correct this in the repo...

**Pull request merged**
