### PR TITLE
Auth messages translations (RC2)

### PR DESCRIPTION
**Pull request by ghys**
This contains an update to the messages for the login,
change password, create API token pages from Crowdin
in ISO-8859 format.

Contains a completed German translation update, and
the following new languages:
- Czech
- Finnish
- Hungarian (only the login page)
- Portuguese (Brazil)
- Swedish
- Ukrainian

Dutch, French, Italian are unchanged from RC1.

Signed-off-by: Yannick Schaus <github@schaus.net>

### CODE REVIEW

**Comment by ghys** [comment]
Verified that even Ukrainian works with all these escaped characters:

image

**Review by kaikreuzer — APPROVED** [review]
Nice!

**Comment by cinadr** [comment]
Hi!

How can I complete all auth messages in Hungarian? I cannot find missing token string in crowdin. Hungarian translation is 100%. Am I missing something? 
Thanks.

**Comment by ghys** [comment]
@cinadr they are in another project (openhab-core), see https://community.openhab.org/t/help-translating-openhab-3/109802/2. If you want them in OH3.0, hurry up! :)

**Comment by cinadr** [comment]
> @cinadr they are in another project (openhab-core), see https://community.openhab.org/t/help-translating-openhab-3/109802/2. If you want them in OH3.0, hurry up! :)

Thanks, done with that...

**Pull request merged**
