### PR TITLE
[persistence] Handle `null` value for `relative` & `inverted` props of filters

### PR DESCRIPTION
**Pull request by florian-h05**
This allows the UI to remove some specific checks that are performed on every save, and simplifies usage of the API for external applications.

### CODE REVIEW

**Comment by florian-h05** [comment]
@J-N-K This is what you proposed in https://github.com/openhab/openhab-core/pull/3681#issuecomment-1620621909, right?

I've tried this, but I get a NPE:

```
11:30:17.976 [ERROR] [.internal.JSONResponseExceptionMapper] - Unexpected exception occurred while processing REST request.
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "f.relative" is null
        at org.openhab.core.persistence.registry.PersistenceServiceConfigurationDTOMapper.lambda$9(PersistenceServiceConfigurationDTOMapper.java:84) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at org.openhab.core.persistence.registry.PersistenceServiceConfigurationDTOMapper.map(PersistenceServiceConfigurationDTOMapper.java:89) ~[?:?]
        at org.openhab.core.io.rest.core.internal.persistence.PersistenceResource.httpPutPersistenceServiceConfiguration(PersistenceResource.java:204) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[bundleFile:3.4.5]
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[bundleFile:3.4.5]
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[bundleFile:3.4.5]
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[bundleFile:3.4.5]
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[bundleFile:3.4.5]
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[bundleFile:3.4.5]
...
```

**Comment by J-N-K** [comment]
I just tried the exact same (except `this.inverted == inverted != null && inverted` instead of `this.inverted == inverted == null ? false : inverted`) and it works perfectly fine when I omit the `inverted` field in the include filter or `relative` in the threshold filter. What exactly did you try?

**Comment by florian-h05** [comment]
I have tried exactly the code as in this PR, and it did not work.
I just re-tried it (fresh compile, bundle:update, restart the runtime) and now it works fine.

**Review by J-N-K — APPROVED** [review]
LGTM, thanks

**Pull request merged**
