### PR TITLE
[CI] Add Java 21 compiling to J17 and native J21

### PR DESCRIPTION
**Pull request by holgerfriedrich**
As we have implemented all changes that allow for Java 21 builds, I'd like to introduce it in the CI as well.
For full Java 21 support, we are still lacking a solution for changed serialization #4174, which currently prohibits changing the JDK version of an existing installation.

This does not affect the build and test, so I propose to add 2 new build targets to the CI in addition to the existing Java 17 build:
* Java 21, generating Java 17 class files
* profile-j21, i.e. Java 21, generating Java 21 class files

Any hints to improve naming of the targets or to simplify the workflow file are appreciated.

I have already tested this on my forked repo and rebased a few times to check if it works reliably.
https://github.com/holgerfriedrich/openhab-core/actions

### CODE REVIEW

**Review by kaikreuzer — APPROVED** [review]
lgtm, thanks!

**Comment by holgerfriedrich** [comment]
@kaikreuzer shall I configure the branch protection to require all 3 builds to succeed?
Currently only DCO and Build on Java 17 are mandatory....

**Comment by kaikreuzer** [comment]
Yeah, might make sense!

**Comment by holgerfriedrich** [comment]
I will wait a few days, until the recent PRs got merged or rebased on current main branch that contains the Java 21 builds.
Otherwise all PR builds will be marked with a yellow dot since not all mandatory builds are completed.
We could merge of course, ignoring the missing checks.

**Pull request merged**
