### PR TITLE
Allow generation of default translations for automation modules

### LINKED ISSUE #2839: [automation] Generate translation property files based on JSON defined module types
> All we have to do next is to define the related property files for translation in [JSON based](https://github.com/openhab/openhab-core/tree/main/bundles/org.openhab.core.automation/src/main/resources/OH-INF/automation/moduletypes) module types.

Automation Triggers, Actions and Conditions can be defined in JSON syntax. The translation logic already is in place with the [ModuleTypeI18nService](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/provider/i18n/ModuleTypeI18nServiceImpl.java). Translations can be placed in the related property files using the following syntax:

```
module-type.<MODULE_TYPE_UID>.label =
module-type.<MODULE_TYPE_UID>.description =

module-type.input.<MODULE_TYPE_UID>.name.<INPUT_NAME>.label =
module-type.input.<MODULE_TYPE_UID>.name.<INPUT_NAME>.description =

module-type.output.<MODULE_TYPE_UID>.name.<INPUT_NAME>.label =
module-type.output.<MODULE_TYPE_UID>.name.<INPUT_NAME>.description =

rule-template.<RULE_TEMPLATE_UID>.label =
rule-template.<RULE_TEMPLATE_UID>.description =
```

_Originally posted by @cweitkamp in https://github.com/openhab/openhab-core/pull/2832#discussion_r825424306_

### PR DESCRIPTION
**Pull request by J-N-K**
Closes #2839 

Signed-off-by: Jan N. Klug <github@klug.nrw>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@cweitkamp I'd think you might be the best expert to review this PR, in case you find time.

**Review by cweitkamp — COMMENTED** [review]
Looks good. Thank you. Some nit-picking comments on readability.

**Comment by J-N-K** [comment]
Done.

**Review by cweitkamp — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
