### PR TITLE
Changed modbus polling logging level to warning when retrying

### PR DESCRIPTION
**Pull request by tnemrap**
https://community.openhab.org/t/modbus-errors/114602

Signed-off-by: Michael Parment <michael.parment@gmail.com>

### CODE REVIEW

**Comment by ssalonen** [comment]
You need to sign off your commits, see https://github.com/openhab/openhab-core/pull/2135/checks?check_run_id=1730728507

**Comment by tnemrap** [comment]
I did the commit directly from github and then the signoff failed when using my name instead of my github id.
Commit sha: 99ffd54, Author: tnemrap, Committer: GitHub; Expected "tnemrap michael.parment@gmail.com", but got "Michael Parment michael.parment@gmail.com".
I do not now how to just signoff this.
Should i close this and do it again from my pc?

**Comment by tnemrap** [comment]
I hate git now i succeeded to sign off but it created a second line Merge branch :(

**Comment by ssalonen** [comment]
The second commit is OK, it would still change only that one line.

You have correctly used your real name in the sign off, as required by CONTRIBUTING.MD. 

However, the check fails as it was expecting username. Do you have your real name set in github profile?

**Comment by tnemrap** [comment]
Now i have set my real name.
Do i need to do anything more?

**Comment by ssalonen** [comment]
> Now i have set my real name.
> Do i need to do anything more

We probably should try to retrigger rebuild. You can do this by closing the PR and then re-opening it (after closing, there should be "re-open" button there)

**Comment by tnemrap** [comment]
Close and reopen done.

**Comment by ssalonen** [comment]
Hmm still the DCO check is failing. @openhab/add-ons-maintainers any thoughts how to resolve this?

**Review by wborn — APPROVED** [review]

**Comment by wborn** [comment]
Thanks. We can also fix sign offs while merging PRs. :-)

**Comment by fwolter** [comment]
Here's a summary how to satisfy the DCO check: https://community.openhab.org/t/dco-check-signing-off-with-github-web-editor-explanation/83330

**Pull request merged**
