### PR TITLE
Sort serial port parameter options

### PR DESCRIPTION
**Pull request by wborn**
When you have many serial ports its easier to find them in a sorted list.

### CODE REVIEW

**Comment by maggu2810** [comment]
For me this seems to be a mixture of the UI layer and the business logic.

If an user interface would like to provide the options sorted (something I would expect and really prefer), the UI should sort the provided list.

I don't think non UI related code should be changed to use a strict order just because an UI would like to use that order.

If we don't want to adapt several UIs, can't we add a sort / comparation logic in the REST interface?

**Comment by wborn** [comment]
Yes you're right about that this is about presentation and it should be in the presentation layer. I'll create a Paper UI PR for this instead.

> If we don't want to adapt several UIs, can't we add a sort / comparation logic in the REST interface?

Adding a parameter for sorting results would make life a bit easier for API consumers. Though when parts of a UI are lazy loaded it may only want to sort content at the moment it is actually shown. So if it were added, the sorting should be optional.

**Comment by wborn** [comment]
There's now https://github.com/openhab/openhab-webui/pull/80 to get these lists of serial ports sorted. :-)

**Comment by maggu2810** [comment]
Thanks

**Pull request closed without merging**
