### PR TITLE
Upgrade org.apache.servicemix.specs.activation-api-1.2.1 to fix mail sending

### PR DESCRIPTION
**Pull request by kaikreuzer**
Fixes https://github.com/openhab/openhab-core/issues/2273

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@wborn I am not sure if that change is enough or if this bundle is somehow provided by Karaf itself.
Wasn't able to build and test locally due to some unrelated problems, but I thought I'd file the PR anyhow.

**Comment by wborn** [comment]
The runtime BOM is currently only used when running tests and debugging in Eclipse. There are also 3 bundles defined in the Karaf features in `karaf/openhab-tp/src/main/feature/feature.xml` which would need to be updated as well.

**Comment by kaikreuzer** [comment]
Perfect, many thanks @wborn!
I have adapted the PR accordingly.

**Review by wborn — APPROVED** [review]
Thanks for the fix! :+1: I had a look at https://github.com/apache/servicemix-specs/pull/17/ and those changes will very likely fix it.

**Pull request merged**
