### PR TITLE
Add option for formatting the y-axis labels in charts

### LINKED ISSUE #1033: Chart display temperature values in exponentional forma
I have use OH 2.4 installed under Ubuntu 19 and Win 10.
Under Ubuntu everything works well. Under Win 10 within the same configuration I got the problem with chart as demonstrated on attached screenshot, made from BasicUI.
As presisrent storage I have use rrd4j.
I hope that problem related with regional settings, i am from Russia. But when I am changed the regional setting in Windows and OH2 it dosen’t helped me. I am looking for the same problem on the community and git and didn’t found the same issues. 
image

### PR DESCRIPTION
**Pull request by J-N-K**
Closes #1033

Signed-off-by: Jan N. Klug <github@klug.nrw>

### CODE REVIEW

**Comment by lolodomo** [comment]
Just to understand: can you provide an example of value for the new attribute and show the resulting chart?

**Comment by J-N-K** [comment]
`Chart item=NewItem period=1h yAxisDecimalPattern="##,##.##"` results in `123234235` to be formatted as `1,23,23,42,35` (or depending on your locale `1.23.23.42.35`).

`Chart item=NewItem period=1h yAxisDecimalPattern="#.##E0"` results in `123234235` to be formatted as `1.23E8` (or depending on your locale `1,23E8`).

`Chart item=NewItem period=1h yAxisDecimalPattern="##0.#E00"` results in `123234235` to be formatted as `123.2E06` (or depending on your locale `123,2E06`).

https://docs.oracle.com/javase/7/docs/api/java/text/DecimalFormat.html is used by the library that generates the chart. We can't change that.

**Review by kaikreuzer — APPROVED** [review]
lgtm, thanks!

**Comment by davesen83** [comment]
> `Chart item=NewItem period=1h yAxisDecimalPattern="##,##.##"` results in `123234235` to be formatted as `1,23,23,42,35` (or depending on your locale `1.23.23.42.35`).
> 
> `Chart item=NewItem period=1h yAxisDecimalPattern="#.##E0"` results in `123234235` to be formatted as `1.23E8` (or depending on your locale `1,23E8`).
> 
> `Chart item=NewItem period=1h yAxisDecimalPattern="##0.#E00"` results in `123234235` to be formatted as `123.2E06` (or depending on your locale `123,2E06`).
> 
> https://docs.oracle.com/javase/7/docs/api/java/text/DecimalFormat.html is used by the library that generates the chart. We can't change that.

For me it doesn't work. I use openHAB 3.3.0.M6. When I put the new attribut yAxisDecimalPattern in a chart

`Chart item=CO2Gehalt period="d" yAxisDecimalPattern="##0.#E00"`

then I get this error:

`Error: Syntax error at line 56 col 45:
Chart item=CO2Gehalt period="d" yAxisDecimalPattern
Unexpected identifier token: "yAxisDecimalPattern". Instead, I was expecting to see one of the following`

What I'm doing wrong?

**Comment by J-N-K** [comment]
Which class logs this error and where do you put that line?

**Comment by davesen83** [comment]
> Which class logs this error and where do you put that line? Could it be your issue is caused by the quotes in your period value?

I put it here in the UI setting of a sitemap:
image

**Comment by J-N-K** [comment]
I thought I had answered that somewhere. Your period setting is invalid.

**Comment by davesen83** [comment]
> I thought I had answered that somewhere. Your period setting is invalid.

Ah ok, interestingly it works also with a small "d".
But error also occurs with a big "D":
`Error: Syntax error at line 56 col 45:

              Chart item=CO2Gehalt period="D" yAxisDecimalPattern
                                              ^
Unexpected identifier token: "yAxisDecimalPattern". Instead, I was expecting to see one of the following:`

**Comment by J-N-K** [comment]
Try like in my example above: 1d (without quotes).

**Comment by davesen83** [comment]
> Try like in my example above: 1d (without quotes).

Doesn't work. The quotes don't come from me, they come from the "Design" automatically. The "Code" part I don't program, it's the result of the "Design" part.

**Comment by J-N-K** [comment]
It seems the sitemap editor does not support setting this parameter. This is an UI issue.

**Pull request merged**
