### PR TITLE
[config] improve type validation message

### PR DESCRIPTION
**Pull request by J-N-K**
The message did not contain the detected wrong type which makes it harder to define what the actual error is.

Found while investigating #2710.

Signed-off-by: Jan N. Klug <github@klug.nrw>

### CODE REVIEW

**Comment by petero-dk** [comment]
Ok, so two follow up questions, how did my system get in a wrong state like this? And how should I go about fixing it?

**Comment by cweitkamp** [comment]
Can you please change the properties file for translations too? Thanks.

**Comment by J-N-K** [comment]
How do I change the translations for languages I don't understand? I also fixed a typo for numeric validations.

**Comment by cweitkamp** [comment]
You do not have to take care about other languages than default translation file in a PR. It will be uploaded to Crowdin and further process will happen over there.

**Review by cweitkamp — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
