### PR TITLE
[rest] Add endpoint for UoM information

### PR DESCRIPTION
**Pull request by J-N-K**
Currently the list of available dimensions for `Number` items is hard-coded in Main UI. The reason is that there is no way to determine the available dimensions at runtime. This endpoint adds that, so that the list can be created dynamically and will automatically be up-to-date if new dimensions (like #3608 or #3408) are added.

### CODE REVIEW

**Comment by J-N-K** [comment]
@ghys @florian-h05 FYI.

**Comment by florian-h05** [comment]
Looks like a great addition, the ability to get the default unit is something that could be really helpful for the user to choose the right dimension. Often you know the unit, but don‘t know the dimension.

**Review by kaikreuzer — APPROVED** [review]
lgtm, thanks!

**Comment by florian-h05** [comment]
@J-N-K Is there any way to register a unit system change listener? I’d like to implement caching like in https://github.com/openhab/openhab-core/pull/3335.

**Comment by florian-h05** [comment]
@J-N-K Can you please check whether you can access that endpoint on current snapshot?

**Comment by J-N-K** [comment]
I have checked with the snapshot before OH4 release and there it works.

**Comment by J-N-K** [comment]
Regarding the unit change listener: My recommendation would be to add a big red warning that changing the unit system change requires a restart. There are other pitfalls when doing so which probably can't be easily fixed.

**Comment by florian-h05** [comment]
For me it doesn't work on openHAB 4.1.0 (build Build #3562):

```
florianh@zephyrus-fh211 ~> http http://localhost:8080/rest/uom
HTTP/1.1 404 Not Found
Allow: DELETE,POST,GET,PUT,OPTIONS,HEAD
Content-Length: 0
Date: Mon, 24 Jul 2023 15:49:52 GMT
Server: Jetty(9.4.50.v20221201)
```

**Comment by J-N-K** [comment]
It's `rest/systeminfo/uom`.

**Pull request merged**
