### PR TITLE
[WIP][semantics] Add staircase and balcony to the semantic model

### PR DESCRIPTION
**Pull request by mgwoj**
I need to additional location to better describe model of my home - a staircase, which is independent room; and a balcony, which is outside of home, but above the ground level.

### CODE REVIEW

**Comment by cweitkamp** [comment]
Thank you very much for your first contribution over here.

I am afraid adding new entities to the CSV file is not the final solution we need related Java classes and translation too. Additionally the new classes have to be added to the model in general.

AFAIK there is a Groovy Script `generateTagClasses.groovy` in the bundle folder which helps creating all the stuff needed. But I am not sure how to apply it. Maybe @ghys or @lolodomo briefly can tell us how to use it.

**Comment by wborn** [comment]
> But I am not sure how to apply it. 

You download Groovy from https://groovy.apache.org/download.html
Extract the archive and make sure the "groovy" command is on you $PATH.
Then you `cd` into the `model` dir and run `groovy generateTagClasses.groovy`

But it can also be done using Maven when https://github.com/openhab/openhab-core/pull/2188 is merged.

**Comment by lolodomo** [comment]
And don't forget to prepare the associated PR for MainUI update when you update the semantic model in the core framework.

**Comment by mgwoj** [comment]
May I ask you where to do that? And why it has to be done in two places? I guess there should be single source of truth.

**Comment by lolodomo** [comment]
Because it is hardcoded in MainUI.
At least it was in December, I have not checked recently.

**Comment by cweitkamp** [comment]
@mgwoj May I ask if you will finish this PR by running `mvn -DgenerateTagClasses` in the bundle folder and submitting the resulting changes?

**Comment by kaikreuzer** [comment]
I didn't follow the process of the ontology expansion in detail, so I wonder if this PR is aligned with #1791, which seems to be the "coordinating issue" for such changes?

**Comment by cweitkamp** [comment]
I didn't follow #1791 in detail either. The OP does not list them but the addition of these locations are fitting into it perfectly as they are mentioned / requested in the comments by some of the participants.

**Comment by J-N-K** [comment]
Since there has been no activity for over a year now and there are merge conflicts, I'm closing this PR. A new PR with these changes and the result of https://github.com/openhab/openhab-core/pull/2188#issue-804767577 would be very welcome.

**Pull request closed without merging**
