### PR TITLE
Adding Indoor Temperature as system channel type

### PR DESCRIPTION
**Pull request by clinique**
Signed-off-by: Gaël L'hopital <gael@lhopital.org>

### CODE REVIEW

**Comment by clinique** [comment]
> > Build failure does not seem related to my PR. Am I wrong ?
> 
> I think you are wrong. wink
> 
> ```
> TEST org.openhab.core.thing.SystemWideChannelTypesTest#systemChannelTypesShouldBeTranslatedProperly() <<< ERROR: expected: <24> but was: <25>
> org.opentest4j.AssertionFailedError: expected: <24> but was: <25>
> ```
You're correct @wborn. I hope this new tentative will be the good one. The fact being that when working on core, I never succeed in launching anything in IDE.

**Comment by lolodomo** [comment]
This is a good idea, this channel type is defined by a lot of bindings.

**Comment by J-N-K** [comment]
Please note that changing to this channel will lead to a lot of broken installations because managed things will need to be deleted and readded due to #1924.

**Comment by lolodomo** [comment]
Yes  I know that and I even try to track any broken changes in PRs.

**Comment by lolodomo** [comment]
I imagine @clinique expects to use this mee channel type in the new netatmo binding.

**Comment by clinique** [comment]
Correct !

**Comment by wborn** [comment]
We also need default translations for Crowdin in:

`bundles/org.openhab.core.thing/src/main/resources/OH-INF/i18n/DefaultSystemChannels.properties`

**Review by wborn — APPROVED** [review]
Thanks! Can you also create a PR for adding the channel to the [System State Channel Types in the docs](https://www.openhab.org/docs/developer/bindings/thing-xml.html#system-state-channel-types)?

**Pull request merged**
