### PR TITLE
BasicUI: openHAB branding (added webapp manifest and icons)

### PR DESCRIPTION
**Pull request by resetnow**
Adds a webapp manifest for Android and homescreen icons for iOS. Startup images on iOS apparently are deprecated.

Signed-off-by: Vlad Ivanov <vlad@ivanov.email>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Many thanks!
Two questions:
1. Would it be hard to add the very same to the Classic UI as well?
2. Could also a favicon be set to address https://github.com/openhab/openhab-distro/issues/308 (at least for the Classic and Basic UIs)?

**Comment by resetnow** [comment]
1. Icon files and manifest can be just copied to ClassicUI. Page HTML will need to be modified eclipse/smarthome#2765
2. I'll add a favicon in a separate PR.

**Comment by resetnow** [comment]
>I'll add a favicon in a separate PR.

It's almost done so it's better to update this. Just a moment.

**Comment by resetnow** [comment]
Updated with favicon.

**Comment by kaikreuzer** [comment]
Thanks! Will merge as soon as I do a new ESH stable (probably on Sunday).

**Comment by kaikreuzer** [comment]
@resetnow Regarding https://github.com/openhab/openhab-core/pull/107#issuecomment-270703151 - people are missing the favicon in the Classic UI; could you do a PR with a similar change as what you did for the Basic UI already?

**Comment by resetnow** [comment]
@kaikreuzer 

1. Should I just copy the icons from BasicUI or should the files be shared between them somehow?
2. Do we need webapp manifest and icons as well for ClassicUI?

**Comment by kaikreuzer** [comment]
1. Copying should be just fine.
2. Wouldn't hurt, right?

Thanks a lot!

**Pull request merged**
