### PR TITLE
Add default translations for automation module types

### PR DESCRIPTION
**Pull request by wborn**
These were generated using openhab/openhab-core#2966.

### CODE REVIEW

**Review by J-N-K — APPROVED** [review]
Thanks!

**Comment by Nadahar** [comment]
As a translator, I've started to look at these. There are quite a few instances of the word `item` for example. There are "special rules" for Item, Thing, Sitemap etc, where theses should not be translated and always be written capitalized. Is it safe to assume that when I come across `item` that it doesn't mean "OH Item" but the generic word "item", and that it should be translated?

**Comment by J-N-K** [comment]
No, there are also cases where "item" in lower-case should not be translated. In fact, in the translations added here, "item" should never be translated and always refers to the openHAB item.

**Comment by Nadahar** [comment]
I think that is a potential source of confusion. I'm pretty sure that I read somewhere that they should always be capitalized, but in addition to that only the capitalized versions are in the "Crowdin glossary" that triggers a dotted underline under the words which states that they should not be translated.

**Pull request merged**
