### PR TITLE
Add Saxon dependency because of static-code-analysis setting a system…

### PR DESCRIPTION
**Pull request by triller-telekom**
… property

Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by martinvw** [comment]
Is this a temporary fix or can / should we fix this in static-analysis project? Because it might also give trouble if we start using it on smart home.

**Comment by triller-telekom** [comment]
This fix is also in the static-code-analysis PR for ESH: https://github.com/eclipse/smarthome/pull/3995/files#diff-600376dffeb79835ede4a0b285078036R213

But in theory the problem is that some code inside the static analysis checker sets a `system property` that defines which XML transformer to use. I do not know if we have another implementation of such transformer somewhere and also do not know where this property is set exactly.

**Comment by kaikreuzer** [comment]
Maybe @svilenvul has some insights here?

**Comment by svilenvul** [comment]
@triller-telekom could you take a look at the PR.

**Comment by triller-telekom** [comment]
@svilenvul Thank you for removing the Code which sets this System property. Looks much better now. Once https://github.com/openhab/static-code-analysis/pull/145 is merged could you please also change your PR against ESH to not include the dependency to saxon in the pom file?

And could you then also revert this PR, once your changes are in place, please?

**Comment by svilenvul** [comment]
Thanks for the good finding. I will update both places as soon as the new version is released.

**Pull request merged**
