### PR TITLE
Support more units

### PR DESCRIPTION
**Pull request by cpmeister**
I'm currently working on adding proper GATT characteristic support for the official bluetooth binding and found that the bluetooth specification uses a ton of units that openHAB doesn't currently support. So before I can complete the bluetooth binding I need to update the units used in the core first.

This replaces #1664 since it causes a lot fewer problems.

I've refactored the code in SmarthomeUnits to simplify adding symbols to the unit formatter and also corrected the names of the `Irradiance` and `Intensity` quantity/units.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
> This replaces #1664 since it causes a lot fewer problems.

Hm, I am not sure this is the right approach. As you have correctly identified, JSR 363 is outdated and as such the uom-se library as the RI is no further maintained. It has been replaced by JSR 385 as the "Units of Measurement API 2.0" with indyra as its RI. Imho it makes a lot of sense for openHAB 3 right at this moment to do the switch to this newer library - much better than copying certain parts from it and duplicating it in our own code.

**Comment by cpmeister** [comment]
Frankly I'm not copying all that much from the newer libraries since a lot of the units/quantities I've added aren't even available in those libraries. The newer library contains maybe 1/3rd of units that I've added here, the rest I'd still be adding to this codebase anyway. I also took a look at the source code for those newer libraries and there is a lot of unit duplication and the code doesn't appear as stable as the older uom-se library.

There are a few benefits that the newer library does have though, one of which is support for compound units (i.e. "1 min 20 seconds" or "2 ft 3in"). But overall I didn't see the newer libraries containing all that many new features that would be useful to us.

But the primary reason that I decided to close the old PR is that I wasn't able to ever get a working build, something else was always failing and it always complained about the old library missing curing the karaf build steps. I wasn't able to figure out how to fix it so someone else would have to be the one to do a version change PR since I don't know how to make it work 🤷‍♂️.

**Comment by wborn** [comment]
I would also prefer to not copy/paste the code for all the obvious long term benefits.

Regarding the error in #1664:

```
[ERROR] Message: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-core-base; type=karaf.feature; version=3.0.0.SNAPSHOT; filter:="(&(osgi.identity=openhab-core-base)(type=karaf.feature)(version>=3.0.0.SNAPSHOT))" [caused by: Unable to resolve openhab-core-base/3.0.0.SNAPSHOT: missing requirement [openhab-core-base/3.0.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.core; type=osgi.bundle; version="[3.0.0.202009230022,3.0.0.202009230022]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.core/3.0.0.202009230022: missing requirement [org.openhab.core/3.0.0.202009230022] osgi.wiring.package; filter:="(osgi.wiring.package=si.uom)"]]
[ERROR] Repositories: {
[ERROR] 	file:/home/travis/build/openhab/openhab-core/features/karaf/openhab-core/target/feature/feature.xml
[ERROR] 	mvn:org.apache.karaf.features/framework/4.2.7/xml/features
[ERROR] 	mvn:org.apache.karaf.features/standard/4.2.7/xml/features
[ERROR] 	mvn:org.openhab.core.features.karaf/org.openhab.core.features.karaf.openhab-tp/3.0.0-SNAPSHOT/xml/features
[ERROR] 	mvn:org.ops4j.pax.web/pax-web-features/7.2.11/xml/features
[ERROR] }
```

It looks to be caused by the manifest in [si-units-2.0.1.jar](https://search.maven.org/remotecontent?filepath=si/uom/si-units/2.0.1/si-units-2.0.1.jar) not exporting any packages.

**Comment by cpmeister** [comment]
> It looks to be caused by the manifest in si-units-2.0.1.jar not exporting any packages.

Anyway for us to fix that or is that something the library developers need to fix?

**Comment by wborn** [comment]
It should be fixed in that project. Since it's also open source anyone can fix it. ;-)

**Comment by cpmeister** [comment]
I went ahead an brought up the missing export `si.uom` package issue with the developers.
But after revisiting this I seem to have stumbled on a different error:
```
[ERROR] Message: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-core-base; type=karaf.feature; version=3.0.0.SNAPSHOT; filter:="(&(osgi.identity=openhab-core-base)(type=karaf.feature)(version>=3.0.0.SNAPSHOT))" [caused by: Unable to resolve openhab-core-base/3.0.0.SNAPSHOT: missing requirement [openhab-core-base/3.0.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.core; type=osgi.bundle; version="[3.0.0.202009250720,3.0.0.202009250720]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.core/3.0.0.202009250720: missing requirement [org.openhab.core/3.0.0.202009250720] osgi.wiring.package; filter:="(&(osgi.wiring.package=javax.measure)(version>=1.0.0)(!(version>=2.0.0)))"]]
[ERROR] Repositories: {
[ERROR] 	file:/Users/cpetty/eclipse/openhab-master2/git/openhab-core/features/karaf/openhab-core/target/feature/feature.xml
[ERROR] 	mvn:org.apache.karaf.features/framework/4.2.7/xml/features
[ERROR] 	mvn:org.apache.karaf.features/standard/4.2.7/xml/features
[ERROR] 	mvn:org.openhab.core.features.karaf/org.openhab.core.features.karaf.openhab-tp/3.0.0-SNAPSHOT/xml/features
[ERROR] 	mvn:org.ops4j.pax.web/pax-web-features/7.2.11/xml/features
[ERROR] }
[ERROR] Resources: {
[ERROR] 	mvn:com.google.guava/failureaccess/1.0.1
[ERROR] 	mvn:com.google.guava/guava/27.1-jre
[ERROR] 	mvn:commons-codec/commons-codec/1.6
[ERROR] 	mvn:commons-io/commons-io/2.2
[ERROR] 	mvn:commons-lang/commons-lang/2.6
[ERROR] 	mvn:de.jollyday/jollyday/0.5.8
[ERROR] 	mvn:de.maggu2810.p2redist/com.google.inject/3.0.0.v201312141243
[ERROR] 	mvn:de.maggu2810.p2redist/org.antlr.runtime/3.2.0.v201101311130
[ERROR] 	mvn:javax.annotation/javax.annotation-api/1.2
[ERROR] 	mvn:javax.annotation/javax.annotation-api/1.3
[ERROR] 	mvn:javax.el/javax.el-api/3.0.0
[ERROR] 	mvn:javax.mail/mail/1.4.7
[ERROR] 	mvn:javax.measure/unit-api/2.0
[ERROR] 	mvn:javax.servlet/javax.servlet-api/3.1.0
[ERROR] 	mvn:javax.websocket/javax.websocket-api/1.1
[ERROR] 	mvn:org.apache.aries.jax.rs/org.apache.aries.jax.rs.whiteboard/1.0.9
[ERROR] 	mvn:org.apache.aries.spec/org.apache.aries.javax.jax.rs-api/1.0.1
[ERROR] 	mvn:org.apache.aries.spifly/org.apache.aries.spifly.dynamic.bundle/1.2
[ERROR] 	mvn:org.apache.aries/org.apache.aries.util/1.1.3
[ERROR] 	mvn:org.apache.felix/org.apache.felix.configadmin/1.9.16
[ERROR] 	mvn:org.apache.felix/org.apache.felix.coordinator/1.0.2
[ERROR] 	mvn:org.apache.felix/org.apache.felix.fileinstall/3.6.4
[ERROR] 	mvn:org.apache.felix/org.apache.felix.inventory/1.0.4
[ERROR] 	mvn:org.apache.felix/org.apache.felix.metatype/1.2.2
[ERROR] 	mvn:org.apache.felix/org.apache.felix.scr/2.1.16
[ERROR] 	mvn:org.apache.felix/org.apache.felix.webconsole.plugins.ds/2.1.0
[ERROR] 	mvn:org.apache.felix/org.apache.felix.webconsole.plugins.event/1.1.8
[ERROR] 	mvn:org.apache.geronimo.specs/geronimo-jaspic_1.0_spec/1.1
[ERROR] 	mvn:org.apache.geronimo.specs/geronimo-jta_1.1_spec/1.1.1
[ERROR] 	mvn:org.apache.karaf.features/org.apache.karaf.features.core/4.2.7
[ERROR] 	mvn:org.apache.karaf.features/org.apache.karaf.features.extension/4.2.7
[ERROR] 	mvn:org.apache.karaf.http/org.apache.karaf.http.core/4.2.7
[ERROR] 	mvn:org.apache.karaf.scr/org.apache.karaf.scr.management/4.2.7
[ERROR] 	mvn:org.apache.karaf.scr/org.apache.karaf.scr.state/4.2.7
[ERROR] 	mvn:org.apache.karaf.services/org.apache.karaf.services.eventadmin/4.2.7
[ERROR] 	mvn:org.apache.karaf.webconsole/org.apache.karaf.webconsole.http/4.2.7
[ERROR] 	mvn:org.apache.karaf/org.apache.karaf.event/4.2.7
[ERROR] 	mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.javax-inject/1_2
[ERROR] 	mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.saaj-impl/1.3.23_2
[ERROR] 	mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.xstream/1.4.7_1
[ERROR] 	mvn:org.apache.servicemix.specs/org.apache.servicemix.specs.activation-api-1.1/2.9.0
[ERROR] 	mvn:org.apache.servicemix.specs/org.apache.servicemix.specs.annotation-api-1.3/1.3_1
[ERROR] 	mvn:org.apache.servicemix.specs/org.apache.servicemix.specs.jaxb-api-2.2/2.9.0
[ERROR] 	mvn:org.apache.servicemix.specs/org.apache.servicemix.specs.jaxws-api-2.2/2.9.0
[ERROR] 	mvn:org.apache.servicemix.specs/org.apache.servicemix.specs.saaj-api-1.3/2.9.0
[ERROR] 	mvn:org.apache.xbean/xbean-bundleutils/4.14
[ERROR] 	mvn:org.apache.xbean/xbean-finder/4.14
[ERROR] 	mvn:org.apache.xbean/xbean-reflect/4.14
[ERROR] 	mvn:org.eclipse.emf/org.eclipse.emf.common/2.12.0
[ERROR] 	mvn:org.eclipse.emf/org.eclipse.emf.ecore.change/2.11.0
[ERROR] 	mvn:org.eclipse.emf/org.eclipse.emf.ecore.xmi/2.12.0
[ERROR] 	mvn:org.eclipse.emf/org.eclipse.emf.ecore/2.12.0
[ERROR] 	mvn:org.eclipse.jdt.core.compiler/ecj/4.5.1
[ERROR] 	mvn:org.eclipse.jetty.websocket/javax-websocket-client-impl/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty.websocket/javax-websocket-server-impl/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty.websocket/websocket-api/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty.websocket/websocket-client/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty.websocket/websocket-common/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty.websocket/websocket-server/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty.websocket/websocket-servlet/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty/jetty-client/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty/jetty-continuation/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty/jetty-deploy/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty/jetty-http/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty/jetty-io/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty/jetty-jaas/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty/jetty-jaspi/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty/jetty-jmx/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty/jetty-jndi/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty/jetty-plus/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty/jetty-proxy/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty/jetty-rewrite/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty/jetty-security/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty/jetty-server/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty/jetty-servlet/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty/jetty-servlets/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty/jetty-util-ajax/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty/jetty-util/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty/jetty-webapp/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.jetty/jetty-xml/9.4.20.v20190813
[ERROR] 	mvn:org.eclipse.orbit.bundles/com.google.gson/2.8.2.v20180104-1110
[ERROR] 	mvn:org.eclipse.orbit.bundles/io.github.classgraph/4.8.35.v20190528-1517
[ERROR] 	mvn:org.eclipse.platform/org.eclipse.equinox.common/3.10.400
[ERROR] 	mvn:org.eclipse.platform/org.eclipse.equinox.registry/3.8.400
[ERROR] 	mvn:org.eclipse.platform/org.eclipse.equinox.supplement/1.9.0
[ERROR] 	mvn:org.eclipse.xtend/org.eclipse.xtend.lib.macro/2.19.0
[ERROR] 	mvn:org.eclipse.xtend/org.eclipse.xtend.lib/2.19.0
[ERROR] 	mvn:org.eclipse.xtext/org.eclipse.xtext.common.types/2.19.0
[ERROR] 	mvn:org.eclipse.xtext/org.eclipse.xtext.smap/2.19.0
[ERROR] 	mvn:org.eclipse.xtext/org.eclipse.xtext.util/2.19.0
[ERROR] 	mvn:org.eclipse.xtext/org.eclipse.xtext.xbase.lib/2.19.0
[ERROR] 	mvn:org.eclipse.xtext/org.eclipse.xtext.xbase/2.19.0
[ERROR] 	mvn:org.eclipse.xtext/org.eclipse.xtext/2.19.0
[ERROR] 	mvn:org.fusesource.jansi/jansi/1.18
[ERROR] 	mvn:org.jvnet.staxex/stax-ex/1.7.4
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.audio/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.automation/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.binding.xml/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.config.core/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.config.discovery/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.config.dispatch/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.config.xml/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.ephemeris/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.id/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.console/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.http/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.monitor/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.net/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.rest.core/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.rest.sse/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.rest/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.persistence/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.semantics/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.storage.json/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.thing.xml/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.thing/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.transform/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.voice/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core/3.0.0-SNAPSHOT
[ERROR] 	mvn:org.ops4j.pax.logging/pax-logging-api/1.11.2
[ERROR] 	mvn:org.ops4j.pax.logging/pax-logging-log4j2/1.11.2
[ERROR] 	mvn:org.ops4j.pax.url/pax-url-aether/2.6.1
[ERROR] 	mvn:org.ops4j.pax.web/pax-web-api/7.2.11
[ERROR] 	mvn:org.ops4j.pax.web/pax-web-extender-whiteboard/7.2.11
[ERROR] 	mvn:org.ops4j.pax.web/pax-web-jetty/7.2.11
[ERROR] 	mvn:org.ops4j.pax.web/pax-web-jsp/7.2.11
[ERROR] 	mvn:org.ops4j.pax.web/pax-web-runtime/7.2.11
[ERROR] 	mvn:org.ops4j.pax.web/pax-web-spi/7.2.11
[ERROR] 	mvn:org.osgi/org.osgi.service.jaxrs/1.0.0
[ERROR] 	mvn:org.osgi/org.osgi.util.function/1.0.0
[ERROR] 	mvn:org.osgi/org.osgi.util.function/1.1.0
[ERROR] 	mvn:org.osgi/org.osgi.util.promise/1.0.0
[ERROR] 	mvn:org.osgi/org.osgi.util.promise/1.1.0
[ERROR] 	mvn:org.ow2.asm/asm-analysis/7.1
[ERROR] 	mvn:org.ow2.asm/asm-commons/7.1
[ERROR] 	mvn:org.ow2.asm/asm-tree/7.1
[ERROR] 	mvn:org.ow2.asm/asm-util/7.1
[ERROR] 	mvn:org.ow2.asm/asm/7.1
[ERROR] 	mvn:org.threeten/threeten-extra/1.4
[ERROR] 	mvn:si.uom/si-units/2.0.1
[ERROR] 	mvn:tech.units/indriya/2.0.4
[ERROR] }
```

I don't know why it is complaining about the `javax.measure` package since that does have an export in the manifest, in addition I don't know why it is trying to only find version 1.0.0 of `javax.measure` instead of 2.0.0. Nothing that I can see tries to import `javax.measure` version 1.0.

Any ideas?

**Comment by wborn** [comment]
I still get the same error as Travis when rebuilding your branch and the manifest in my `org.openhab.core` bundle imports `javax.measure;version="[2.0,3)"` so that probably indicates you need to rebuild the bundles of your branch.

**Comment by wborn** [comment]
Link to issue for fixing the manifest: https://github.com/unitsofmeasurement/si-units/issues/80

**Comment by cpmeister** [comment]
We might be waiting indefinitely for the si-units project to fix their problem. Why not just add the extra units for now and then I can make another PR when the new units library comes out? Or would it be better for me to add the units into my bluetooth PR instead?

**Comment by splatch** [comment]
@cpmeister I'd check with UOM guys first if we fit into their release schedule. If their metadata is wrong you can always try using plain jar with `wrap:` before `mvn:tec.uom/...` (be aware you need `<feature prerequisite=true>wrap</feature>`.
By this way you can generate metadata on the fly form any library. As long as it does not play with classloaders or require custom initialization logic it will work.

**Comment by cpmeister** [comment]
@splatch Thanks! I'll give it a try.

**Comment by wborn** [comment]
>  If their metadata is wrong you can always try using plain jar with wrap: before mvn:tec.uom/... (be aware you need <feature prerequisite=true>wrap</feature>.

We used the `wrap` feature initially during the bnd migration. The issue with using it is that it only provides a solution for Karaf (which may not be used by everyone using the OHC framework). Such bundles also cannot be used when launching the  [app.bndrun](https://github.com/openhab/openhab-distro/blob/master/launch/app/app.bndrun) for debugging in Eclipse. So instead we now wrap the non-OSGi JARs in the [openhab-osgiify](https://github.com/openhab/openhab-osgiify) repo to bundles.

**Comment by NorbertHD** [comment]
Did you try the 2.1-SNAPSHOT of Indriya/si-units?
Does it solve the problem with osgi package exports?

**Comment by cpmeister** [comment]
> Did you try the 2.1-SNAPSHOT of Indriya/si-units?
> Does it solve the problem with osgi package exports?

I did give it a try, but it only revealed that the uom-lib-common library also has osgi problems. ☹️

**Comment by NorbertHD** [comment]
Too bad.
Was it this issue:
https://github.com/unitsofmeasurement/uom-lib/pull/65
Or is there another problem? Did you open an issue there?
But shouldn't the update of uom to Indriya be discussed here: #1664

**Comment by kaikreuzer** [comment]
@cpmeister I am also not quite clear on the status here and the relation to #1664 - my feeling is that we should first deal with the upgrade to Indriya and then see what is left to do.

**Comment by cpmeister** [comment]
Well upgrading Indriya isn't so much a concern to me so much as getting the new si-units library, which has to wait until the next version of it gets released. It is unknown when that will be and in the meantime I the generic bluetooth binding has to implement all of these units itself. I'd prefer to get these units implemented in the core so that everyone has them at their disposal, but if you want to wait until the new version of si-units gets released (whenever that is, could be mid next year for all I know), then feel free to let this PR sit around for months and months.

PR #1664 was meant to be the PR that upgraded the units libraries so that some of the new units would become accessible. But #1664 wouldn't add all of the units that I need, there are still others that I need to create (like cycles per minute) which is why this PR was created. But since upgrading the unit library is not an option atm I just decided to add all the units I need from the get-go and then once the new unit library comes out just remove/replace any of the units that can now be found in the new library. 

What are my options at this point?

**Comment by cpmeister** [comment]
I find it increasingly frustrating that this PR continues to get ignored while uom PRs get merged. Each time this happens I have to resolve the conflicts to keep this PR relevant. I see no good reason to prevent adding support for additional units since migration to the new javax measurement library can (and will) be done in another PR. Why should this PR be held hostage by another open source project's undisclosed release cycle?

**Comment by kaikreuzer** [comment]
@cpmeister I understand your frustration and beg your pardon.
We have only 5 days left until feature freeze and my absolute top prio are critical bugs (where there are plenty wrt rules that I am looking into) and API breaking changes that have to be done before the 3.0 release as afterwards we want to avoid any breaking stuff - and this was the category of the "other UoM PRs" that you probably refer to.

Your PR is adding features, which can safely be done later, hence it does not have top prio for me - and I assume the situation is fairly similar for the other @openhab/core-maintainers.

I wish I could tackle more stuff at the same or shorter time, but I simply can't - I hope you understand!

**Comment by cpmeister** [comment]
@kaikreuzer I understand, I just wanted to vent a bit. Thanks for taking the time to respond.

**Comment by wborn** [comment]
Maybe you can rebase this branch on the current main branch now that #2319 got merged @cpmeister?

**Comment by wborn** [comment]
Hi @cpmeister, can you update the PR?
There will be even more units available when https://github.com/openhab/openhab-core/pull/2573 is merged.

**Comment by J-N-K** [comment]
This is inactive for more than half a year and can't be merged due to conflicts. Please open an new PR (or fix conflicts and re-open this one).

**Pull request closed without merging**
