### PR TITLE
Backward compatibility for jsprofile from OH3

### PR DESCRIPTION
**Pull request by jimtng**
https://community.openhab.org/t/preparation-for-oh-4-0-how-to-find-my-js-transformations/146233/4

### CODE REVIEW

**Comment by J-N-K** [comment]
I understand your intention, but I think this is wrong. We should not add something that will be wrong in most cases (which script would be able to to bidirectional conversion?) and confuse people who are configuring the profile now.

**Comment by jimtng** [comment]
The jsscripting profile passes on the command from item to handler, hence why I set it to `|input`. The user script from `function` is only used for `toItemScript`. Wouldn't that work?

**Comment by J-N-K** [comment]
It still shows up in the UI and allows to add new "wrong" configurations. And if we want to add that, then we should:

1. check for `toItemScript`, if present use it
2. check for `function`, if present use it and print a warning that support for `function will be removed`.
3. remove it from the config description, so it doesn't show up in the UI

**Comment by jimtng** [comment]
I originally didn't want to add it to the config description, but if it wasn't there, how can the user "transfer" their existing configuration? I thought that by showing it there, with the warning, they could at least copy paste.

How would you propose we do this?

**Comment by jimtng** [comment]
I haven't investigated it, but perhaps there is a way to automatically migrate the config Param?

**Comment by stefaanbolle** [comment]
I have a few 100 changes to make. It would be nice that the system can change the configs automatically during a next upgrade or that a script can be provided to do it manually if you would chose to not maintain backwards compatibility (for which I also understand your argumentation).

**Comment by jimtng** [comment]
> I have a few 100 changes to make

@stefaanbolle Were your items created through the MainUI or file based configs (i.e. .items file)?

**Comment by stefaanbolle** [comment]
> 

All via Main UI. No text configuration files in use

**Comment by jimtng** [comment]
Closing this. The upgrade process will be done through cli #3268

**Pull request closed without merging**
