### PR TITLE
runtime: add support for Paho MQTT

### PR DESCRIPTION
**Pull request by maggu2810**

### CODE REVIEW

**Comment by davidgraeff** [comment]
Hm is that a long term solution? 
I mean to add all kind of dependencies to the pom although those parts are optional only (in this case, as long as you do not install the mqtt transport, you do not need paho).

**Comment by maggu2810** [comment]
What do you mean by "long term solution"?
The purpose of runtime BOM of `openhab-core` is to provide all things that are necessary to use an openHAB Core bundle at runtime.
Similar as as openHAB Core's compile BOM defines all non openHAB Core artifacts we depend on compile time.

**Comment by davidgraeff** [comment]
I'm just asking. So if we add more transports to this repo, the bom would need to be modified.

**Comment by maggu2810** [comment]
Just want to mention that it is not (only) "the long term solution" but the **intention** of that POM.

**Pull request merged**
