### PR TITLE
Remove author from addon xsd

### PR DESCRIPTION
**Pull request by kaikreuzer**
See https://github.com/openhab/openhab-core/pull/3050#discussion_r1071603658

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by J-N-K** [comment]
I think it should also be removed from `org.openhab.core.addon.AddonInfo` and the parsing should be removed from `org.openhab.core.addon.xml.internal.AddonInfoConverter` and `org.openhab.core.addon.xml.internal.AddonInfoReader`.

**Comment by jlaur** [comment]
FYI, addons should be ready for this: openhab/openhab-addons#14333

**Comment by kaikreuzer** [comment]
@jlaur Thanks! At least almost all bindings should be ready, see https://github.com/openhab/org.openhab.binding.zwave/pull/1843 and https://github.com/openhab/org.openhab.binding.zigbee/pull/795. 😉

**Review by J-N-K — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
