### PR TITLE
Add unit "calorie"

### LINKED ISSUE #3667: [UoM] add unit cal as energy
Calory is missing as a unit for energy (1 cal = 4.184 J) 

Some Scales (with Measurement for Fat, Water, BMI) do provide a recommendation for daily energy in kcal. Would be nice to have the option to use the unit "the openHAB way" :)

### PR DESCRIPTION
**Pull request by J-N-K**
Closes #3667

### CODE REVIEW

**Review by wborn — APPROVED** [review]
Thanks!

**Comment by wborn** [comment]
Can you also add the new unit to the UoM docs?

https://next.openhab.org/docs/concepts/units-of-measurement.html

**Comment by wborn** [comment]
I think these units also still need to be added to the docs:

* https://github.com/openhab/openhab-core/pull/3608
* https://github.com/openhab/openhab-core/pull/3616

**Comment by boehan** [comment]
> I think these units also still need to be added to the docs:
> 
>     * [Add dimension RadiationSpecificActivity #3608](https://github.com/openhab/openhab-core/pull/3608)
> 
>     * [[UoM] add unit rpm for rotational frequency #3616](https://github.com/openhab/openhab-core/pull/3616)

Done in https://github.com/openhab/openhab-docs/pull/2100

**Pull request merged**
