### PR TITLE
Icon format set to PNG by default for Classic UI

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Maybe you should use the chance and also set disableHtmlCache=false as a default?

**Comment by lolodomo** [comment]
And what about adding a default value for iconType in file https://github.com/eclipse/smarthome/blob/6dd1df77136a70ec55da6746be05bf65b78ba15b/extensions/ui/org.eclipse.smarthome.ui.classic/ESH-INF/config/config.xml.
The default value is set for Basic UI.

**Comment by kaikreuzer** [comment]
You are right, this is probably the even better option. Btw, I would suggest to use svg as default for both UIs.

**Comment by lolodomo** [comment]
@kaikreuzer : I submitted a PR in the smarthome repo that adds default values for config settings.
Do you think we still have to update feature.xml ?
By the way, we have in this file "iconType" set for Basic UI and unset for Classic UI.
It could make sense either to suppress "iconType" or to set it for both. What's your feeling ?

**Comment by kaikreuzer** [comment]
Yes, I'd agree that we could remove it here completely and only add these as default to the config descriptions (while we have to make sure that the UIs internally use the same value as a default, if no configuration is set).

**Comment by lolodomo** [comment]
Please note that Basic UI and Classic UI are currently considering PNG as default icon type when no configuration is set.
With the new default value set for configuration, I assume that a value will always be returned from the configuration and so the default icon type will finally be set to the one of the configuration.

**Comment by kaikreuzer** [comment]
> With the new default value set for configuration, I assume that a value will always be returned from the configuration and so the default icon type will finally be set to the one of the configuration.

I am not so sure about that - if there is no configuration available at all, the Java code will have to use its internal defaults. The default in the config description is mainly used to provide UIs an information of what they should select by default (instead of leaving fields empty).

**Comment by lolodomo** [comment]
In this case, the default values have to be changed in the code too, for both UI.

**Pull request closed without merging**
