### PR TITLE
Dashboard: Add DS annotations as optional dependency

### PR DESCRIPTION
**Pull request by triller-telekom**
Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by martinvw** [comment]
Pity I cannot merge here

**Comment by kaikreuzer** [comment]
@martinvw That can be changed ;-)
But this time I am happy you couldn't merge, because I need to figure out why the Jenkins PR builder didn't trigger...

**Comment by kaikreuzer** [comment]
Ok, triggered this time, see https://openhab.ci.cloudbees.com/view/Pull%20Request%20Builds/job/PR-openHAB-Core/2/.

I assume the hook is only shown here on new PRs, though.

**Comment by kaikreuzer** [comment]
> That can be changed

Done.

**Pull request merged**
