### PR TITLE
Added standard gravity and dBm Units

### PR DESCRIPTION
**Pull request by Hilbrand**
Also did some clean up, which is in the first commit. The units are in the second commit.
Related to: https://github.com/openhab/openhab2-addons/pull/4913

### CODE REVIEW

**Comment by maggu2810** [comment]
What's the reason to make the classes final and its constructor private?
Do you see any critical if someone wants to create a sub class so we need to prevent it that strong?
Sure, it would make no sense (perhaps) but does it harm if?

**Comment by maggu2810** [comment]
I assume it has been wrong before but has been possible to use every "SmartHomeUnit" as "SIUnit" and "ImperialUnit".

```
        System.out.println(SmartHomeUnits.AMPERE);
        System.out.println(SIUnits.AMPERE);
        System.out.println(ImperialUnits.AMPERE);
```

It is not valid anymore.

It seems to be correct after the change because a SmartHomeUnit is not necessary an SIUnit.

But should we mark this as "API breaking" (and merge it) as it can break the consumers.

**Comment by Hilbrand** [comment]
The classes already had private constructors, except for `SmartHomeUnits` that had a protected constructor. Because of the private constructors is seems logical to make this more explicit and make the classes final. `SmartHomeUnits` was kind of misused by the other to classes. They extended `SmartHomeUnits`, but created a singleton of their own class, even while `SmartHomeUnits` also is used as a singleton class. So I changed the extend to the `AbstractSystemOfUnits` class they should extend (I think) and with that change `SmartHomeUnits` can have the private constructor too (and be a final class).

**Comment by Hilbrand** [comment]
I checked the openhab2 repo and found 2 issues of problems due to the changes, but only in tests. I've created a [pr (5016)](https://github.com/openhab/openhab2-addons/pull/5016) to fix them.

**Comment by maggu2810** [comment]
Thanks

**Pull request merged**
