### PR TITLE
Inherit NullAnnotations also in Maven

### PR DESCRIPTION
**Pull request by triller-telekom**
Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by martinvw** [comment]
Thanks!

**Comment by martinvw** [comment]
Maybe we should configure the openHAB addons build to be executed as soon as the core build has completed, this way we will most likely detect things a little quicker.

**Comment by kaikreuzer** [comment]
If you have a close look, the openhab-core IS build within the openHAB bundles build!
The issue probably is that it isn't recognized within  the same reactor, so the issue only turned up on the second build, not on the first.

But no need to spend efforts on changing this here - we should rather focus on getting the new build pipeline up and running!

**Comment by martinvw** [comment]
I cannot find it quickly, but if you say that changes to both repositories should trigger the builds of the 'openHAB2-Bundles' and they do that in the correct order than it should be fine.

And indeed it might be more important to focus on the new build pipeline.

**Pull request merged**
