### PR TITLE
Fix NPE in GroupStateTriggerHandler and GroupCommandTriggerHandler

### PR DESCRIPTION
**Pull request by J-N-K**
Reported on the community forum. The handler checks if the item's group names contains the configured value. A `null` group name results in the NPW during that check.

### CODE REVIEW

**Review by wborn — APPROVED** [review]
Thanks for the fix!
Maybe it is also easy to add unit tests for this?

**Comment by J-N-K** [comment]
What should be covered by that test? The "real" problem is that we don't validate the trigger configurations before we create the modules.

**Comment by wborn** [comment]
> What should be covered by that test?

Based on the changes the tests could check that a warning is logged whenever the `groupName` is missing and no NPE is thrown when the `receive` method is called.
Then if someone in the future removes the check or messes up the logic the tests would fail.

**Comment by J-N-K** [comment]
Done

**Review by wborn — APPROVED** [review]
Thanks!

**Comment by lolodomo** [comment]
@J-N-K : is it something to backport in branch 4.1.x ?

**Pull request merged**
