### PR TITLE
Simplify code for 'updateProperty' method

### PR DESCRIPTION
**Pull request by cweitkamp**
- Simplify code for `ThingHandler` `updateProperty` method

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
This changes seems to make `org.openhab.core.config.xml.tests` fail.

**Comment by cweitkamp** [comment]
I will have a second look locally. IIRC the occasionally failure of the ConfigDescriptionI18nTest is a known issue (see #1222).

**Comment by kaikreuzer** [comment]
I already rebuilt it once and it showed the same error. Can try once more...

**Comment by cweitkamp** [comment]
The "rebuild" label did not trigger another build.

Locally it is working after two or more tries. The ConfigDescriptionI18nTest failed for me too on the first run.

I submitted a fix for #1222 with #1306.

**Pull request merged**
