### PR TITLE
Log failed feature installation on error

### PR DESCRIPTION
**Pull request by wborn**
With https://github.com/openhab/openhab-core/pull/99 bulk feature installation was added. With the code changes of that PR it is assumed that features are always installed succesfully.

Whenever features fail to install the openHAB `FeatureInstaller` will try to reinstall these every minute.
This may generate a lot of load which is hard to debug with many side effects (see [community topic](https://community.openhab.org/t/after-upgrade-to-2-4-stable-im-flooded-with-java-lang-illegalstateexception/61567?u=wborn)).

With this PR the `FeatureInstaller` will again log on error whenever features fail to install.

We could also not install features that aren't returned by `FeaturesService.listFeatures`. However it's still possible features fail to install and this load is generated for other reasons (offline, permissions, available disk space).

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Did you test that this works?
From my memory, the `featuresService.installFeatures` method throws an exception if ANY feature cannot be installed - which means that the current logic is correct as it will only get into the code if everything was successfully installed. But maybe the behavior of Karaf has changed meanwhile?

**Comment by wborn** [comment]
With the current implementation it doesn't throw exceptions for non-existing features and logs such features as installed. See the [community topic](https://community.openhab.org/t/after-upgrade-to-2-4-stable-im-flooded-with-java-lang-illegalstateexception/61567/14?u=wborn). But that is to be expected when we explicitly tell the service to not fail for features that can't be found:

https://github.com/openhab/openhab-core/blob/b4bade3e98baa856b0fbf2b362bd21b4ae9b8643/bundles/org.openhab.core.karaf/src/main/java/org/openhab/core/karaf/internal/FeatureInstaller.java#L424-L425

Not failing for features that can't be found makes the installation more robust ofcourse.

I tested these changes by adding some random addon names to `addons.cfg`.

**Comment by wborn** [comment]
There's also a similar smarthome event being logged whenever you install bindings using `addons.cfg`

```
23:32:10.606 [INFO ] [smarthome.event.ExtensionEvent       ] - Extension 'binding-ntp' has been installed.
```

If you remove a binding from `addons.cfg` both are logged:

```
23:32:54.906 [INFO ] [.core.karaf.internal.FeatureInstaller] - Uninstalled 'openhab-binding-ntp'
23:32:54.906 [INFO ] [smarthome.event.ExtensionEvent       ] - Extension 'binding-ntp' has been uninstalled.
```

If you make changes using UIs you won't see the FeatureInstaller events at all. What makes the additional FeatureInstaller events useful for you? If they don't add anything, I'd rather log the FeatureInstaller uninstalled event on debug as well.

**Comment by lolodomo** [comment]
This is useful to follow what happens at first startup of openHAB. Currently there is no more log relative to binding installation at first install. Nothing is logged during a long time and I am almost sure that bindings are installed during this time.
And this could be useful to confirm correct install when done with Paper UI.

**Pull request merged**
