### PR TITLE
Bump spifly to 1.3.6 and asm to 9.4 to support records

### PR DESCRIPTION
**Pull request by J-N-K**
Fixes https://github.com/openhab/openhab-addons/issues/15099

### CODE REVIEW

**Comment by J-N-K** [comment]
@wborn @kaikreuzer This breaks KNX at the moment. ASM 9.4 is already the version used by Karaf 4.4.3, it was not updated previously. Karaf 4.4.3 uses spifly 1.3.5 (where we still provided 1.3.4), but according to my tests 1.3.6 works fine.

**Comment by holgerfriedrich** [comment]
@J-N-K thanks a lot. 

I can confirm openhab/openhab-addons#15099. It is really annoying: KNX binding is broken right now.

I can confirm that the issue is resolved once I apply this patch and deploy the new openHAB framework on my RPI.

@kaikreuzer @wborn Could you have a look please and get this merged?

**Review by holgerfriedrich — APPROVED** [review]
LGTM! Fixes the broken knx binding on my dev system.

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Comment by florian-h05** [comment]
@kaikreuzer Can you please trigger a new distro build?

**Comment by kaikreuzer** [comment]
Already running: https://ci.openhab.org/job/openHAB-Core/

**Comment by wborn** [comment]
Can you also create a PR to fix the add-ons build @J-N-K?

**Pull request merged**
