### PR TITLE
[automation] Fixed duplication of config descriptions

### LINKED ISSUE #1265: [thing actions] Actions fail to execute after a binding restart
Reference my comment [here](https://github.com/openhab/openhab2-addons/pull/6494#issuecomment-561128456).

Most (if not all) thing action implementations contain code that looks like this.
```
    public static void restart(@Nullable ThingActions actions) {
        if (actions instanceof DoorbirdActions) {
            ((DoorbirdActions) actions).restart();
        } else {
            throw new IllegalArgumentException("Instance is not a DoorbirdActionsService class");
        }
    }
```

Normally, the `instanceof` test succeeds. However, after installing a new version of the binding, this test fails, which causes the code to throw `IllegalArgumentException` when invoking the action from a rule. This condition can only be cleared by restarting openHAB. There are several ways to reproduce this, one of which is to drop a new version of a binding into `addons` that overwrites an older version that's already there.

After installing the new version of the binding, it appears that the classloader instances are different. I suspect this is what's causing the `instanceof` test to fail.

Before installing new binding version:
```
2019-12-09 09:23:02.018 [INFO ] [ding.doorbird.action.DoorbirdActions] - DoorbirdActions classloader org.eclipse.osgi.internal.loader.EquinoxClassLoader@50578098[org.openhab.binding.doorbird:2.5.0.201912091420(id=245)]
2019-12-09 09:23:02.019 [INFO ] [ding.doorbird.action.DoorbirdActions] - ThingActions actions classloader org.eclipse.osgi.internal.loader.EquinoxClassLoader@50578098[org.openhab.binding.doorbird:2.5.0.201912091420(id=245)]
```
After installing new binding version:
```
2019-12-09 09:24:39.813 [INFO ] [ding.doorbird.action.DoorbirdActions] - DoorbirdActions classloader org.eclipse.osgi.internal.loader.EquinoxClassLoader@50578098[org.openhab.binding.doorbird:2.5.0.201912091423(id=245)]
2019-12-09 09:24:39.814 [INFO ] [ding.doorbird.action.DoorbirdActions] - ThingActions actions classloader org.eclipse.osgi.internal.loader.EquinoxClassLoader@1c14e241[org.openhab.binding.doorbird:2.5.0.201912091423(id=245)]
```

### PR DESCRIPTION
**Pull request by cweitkamp**
- Fixed removal / replacement of annotated `ThingActions`

Beside fixing https://github.com/openhab/openhab-core/issues/1265#issuecomment-651766273 I added some warnings for developers and missing null-checks inside the code. 

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by lolodomo** [comment]
As this is a severe bug, is it a fix that could be spplied to 2.5.x for the next release 2.5.7 ?

**Comment by mhilbush** [comment]
@cweitkamp I'm so glad you got to the bottom of this. Nice work!!!

**Comment by cweitkamp** [comment]
Thanks for the praise but I am afraid I have to disappoint you :disappointed:. This fix is not a solution for #1265. It only fixes my observations described in https://github.com/openhab/openhab-core/issues/1265#issuecomment-651766273.

I tried to apply this path to OHC 2.5.x by
- checking out [tag 2.5.0](https://github.com/openhab/openhab-core/releases/tag/2.5.0) (a1a162515d1839fd60d7fffdeb5b579b06dc7e5f)
- changing the relevant code (https://github.com/cweitkamp/openhab-core/commit/797cbac8e969cb20126b4f10a669fb127f913195)
- building the `*.jar` file of `org.openhab.core.automation`
- putting the `*-jar` file in my addons-folder (uninstall "openHAB Core :: Bundles :: Automation" first)

The error while executing the Thing action in a DSL rule still remained ... There must some more lines of misbehaving code.

**Comment by kaikreuzer** [comment]
@cweitkamp While it is not fixing #1265, it is imho fine to merge. I have adapted the title of this PR to make it clear that it does not fix reloading of ThingActions in general.

**Pull request merged**
