### PR TITLE
Refactor XML handling

### PR DESCRIPTION
**Pull request by J-N-K**
Supersedes #3377 

- adds a profile for JAXB generation to `bundles/pom.xml`
- integrates the XML handling in the thing-bundle
- prevents duplicate generation of DTOs
- use `src/generated` instead of `target` for class generation
- fix `.classpath` for bundles with generated classes

### CODE REVIEW

**Comment by J-N-K** [comment]
There are two things I'm unsure about: Should we also integrate `org.openhab.core.addon.xml` to `org.openhab.core` (where the `org.openhab.core.addon` package is located) and `org.openhab.core.config.xml` to `org.openhab.core.config.core` (why is that `.core.config.core` and not `.core.config`?)

**Comment by J-N-K** [comment]
@wborn @cweitkamp @kaikreuzer If you find the time, I would appreciate your opinion here.

**Comment by kaikreuzer** [comment]
> Should we also integrate [...]? I would vote for yes.

Me too. That's actually what I tried to express [here](https://github.com/openhab/openhab-core/pull/3377#issuecomment-1435688138) with "merge the xml bundles to the main/core bundles" (note the plural form).

> Shall we use an Xml prefix or suffix to the generated class names? We could then just use .dto instead of .xml.dto as package names.

If we are not getting into any conflict with the dtos for the JSON of the REST API, this should be ok. We just need to be aware that those dtos in the `io.rest` bundles are something different.

One other remark on your current PR: You have moved the generated classes from being internal to being public. Shouldn't they all have `internal` in their package name, since they are only used internally in the bundle for parsing?

**Comment by kaikreuzer** [comment]
> Should we also integrate [...]? I would vote for yes.

Me too. That's actually what I tried to express [here](https://github.com/openhab/openhab-core/pull/3377#issuecomment-1435688138) with "merge the xml bundles to the main/core bundles" (note the plural form).

> Shall we use an Xml prefix or suffix to the generated class names? We could then just use .dto instead of .xml.dto as package names.

If we are not getting into any conflict with the dtos for the JSON of the REST API, this should be ok. We just need to be aware that those dtos in the `io.rest` bundles are something different.

One other remark on your current PR: You have moved the generated classes from being internal to being public. Shouldn't they all have `internal` in their package name, since they are only used internally in the bundle for parsing?

**Comment by J-N-K** [comment]
The problem with `internal` is that they are not exported then and the code in `org.openhab.core.thing` can't use the classes from `org.openhab.core.config.internal`. As a result we would need to duplicate them again.

But I don't think this is a real issue. If these classes change, the XSD also changes and adaptions to code that uses them would be needed. My suggestion to prefix/suffix them with Xml should also prevent accidental use of these DTOs instead of the correct classes (e.g. `XmlThingType` vs. `ThingType`).

**Comment by kaikreuzer** [comment]
Could you point me to where they are actually referenced in code? I just moved them all to internal packages in my local IDE and everything still compiles...

**Comment by J-N-K** [comment]
`org.openhab.core.thing.xml.dto.ThingType.xml` uses `org.openhab.core.config.xml.dto.ConfigDescription`.

Compilation probably works, but feature resolution should fail. Otherwise BND does not generate the correct import statements for the manifest.

**Comment by kaikreuzer** [comment]
Sorry if I am blind or missing the point, but the generated `ThingType` dto has the following imports:
```
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
```
How does it "use" the `ConfigDescription` class?

**Comment by J-N-K** [comment]
That's very interesting. For me it looks like this:

```

package org.openhab.core.thing.xml.dto;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.openhab.core.config.xml.dto.ConfigDescription;
import org.openhab.core.config.xml.dto.ConfigDescriptionRef;


/**
 * <p>Java class for thingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="thingType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="supported-bridge-type-refs" type="{https://openhab.org/schemas/thing-description/v1.0.0}supportedBridgeTypeRefs" minOccurs="0"/&gt;
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="channels" type="{https://openhab.org/schemas/thing-description/v1.0.0}channels"/&gt;
 *           &lt;element name="channel-groups" type="{https://openhab.org/schemas/thing-description/v1.0.0}channelGroups"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="properties" type="{https://openhab.org/schemas/thing-description/v1.0.0}properties" minOccurs="0"/&gt;
 *         &lt;element name="representation-property" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="config-description" type="{https://openhab.org/schemas/config-description/v1.0.0}configDescription"/&gt;
 *           &lt;element name="config-description-ref" type="{https://openhab.org/schemas/config-description/v1.0.0}configDescriptionRef"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{https://openhab.org/schemas/config-description/v1.0.0}idRestrictionPattern" /&gt;
 *       &lt;attribute name="listed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="extensible" type="{https://openhab.org/schemas/thing-description/v1.0.0}namespaceIdListRestrictionPattern" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "thingType", propOrder = {
    "supportedBridgeTypeRefs",
    "label",
    "description",
    "category",
    "channels",
    "channelGroups",
    "properties",
    "representationProperty",
    "configDescription",
    "configDescriptionRef"
})
@XmlSeeAlso({
    BridgeType.class
})
@Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
public class ThingType implements Serializable
{

    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    private final static long serialVersionUID = 1L;
    @XmlElementWrapper(name = "supported-bridge-type-refs")
    @XmlElement(name = "bridge-type-ref")
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    protected List<BridgeTypeRef> supportedBridgeTypeRefs = new ArrayList<BridgeTypeRef>();
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    protected String label;
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    protected String description;
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    protected String category;
    @XmlElementWrapper
    @XmlElement(name = "channel")
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    protected List<Channel> channels = new ArrayList<Channel>();
    @XmlElementWrapper(name = "channel-groups")
    @XmlElement(name = "channel-group")
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    protected List<ChannelGroup> channelGroups = new ArrayList<ChannelGroup>();
    @XmlElementWrapper
    @XmlElement(name = "property")
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    protected List<Property> properties = new ArrayList<Property>();
    @XmlElement(name = "representation-property")
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    protected String representationProperty;
    @XmlElement(name = "config-description")
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    protected ConfigDescription configDescription;
    @XmlElement(name = "config-description-ref")
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    protected ConfigDescriptionRef configDescriptionRef;
    @XmlAttribute(name = "id", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    protected String id;
    @XmlAttribute(name = "listed")
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    protected Boolean listed;
    @XmlAttribute(name = "extensible")
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    protected String extensible;

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the representationProperty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public String getRepresentationProperty() {
        return representationProperty;
    }

    /**
     * Sets the value of the representationProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public void setRepresentationProperty(String value) {
        this.representationProperty = value;
    }

    /**
     * Gets the value of the configDescription property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigDescription }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public ConfigDescription getConfigDescription() {
        return configDescription;
    }

    /**
     * Sets the value of the configDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigDescription }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public void setConfigDescription(ConfigDescription value) {
        this.configDescription = value;
    }

    /**
     * Gets the value of the configDescriptionRef property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigDescriptionRef }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public ConfigDescriptionRef getConfigDescriptionRef() {
        return configDescriptionRef;
    }

    /**
     * Sets the value of the configDescriptionRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigDescriptionRef }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public void setConfigDescriptionRef(ConfigDescriptionRef value) {
        this.configDescriptionRef = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the listed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public boolean isListed() {
        if (listed == null) {
            return true;
        } else {
            return listed;
        }
    }

    /**
     * Sets the value of the listed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public void setListed(Boolean value) {
        this.listed = value;
    }

    /**
     * Gets the value of the extensible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public String getExtensible() {
        return extensible;
    }

    /**
     * Sets the value of the extensible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public void setExtensible(String value) {
        this.extensible = value;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public List<BridgeTypeRef> getSupportedBridgeTypeRefs() {
        return supportedBridgeTypeRefs;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public void setSupportedBridgeTypeRefs(List<BridgeTypeRef> supportedBridgeTypeRefs) {
        this.supportedBridgeTypeRefs = supportedBridgeTypeRefs;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public List<Channel> getChannels() {
        return channels;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public void setChannels(List<Channel> channels) {
        this.channels = channels;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public List<ChannelGroup> getChannelGroups() {
        return channelGroups;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public void setChannelGroups(List<ChannelGroup> channelGroups) {
        this.channelGroups = channelGroups;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public List<Property> getProperties() {
        return properties;
    }

    @Generated(value = "com.sun.tools.xjc.Driver", comments = "JAXB RI v2.3.7", date = "2023-02-21T21:36:06+01:00")
    public void setProperties(List<Property> properties) {
        this.properties = properties;
    }

}
```

**Comment by kaikreuzer** [comment]
Let me rebuild everything, maybe I had some old artefacts somewhere...

**Comment by J-N-K** [comment]
There is a problem when merging the bundles:

- `org.openhab.core` includes package `org.openhab.core.addon`
- `org.openhab.core.addon.xml` includes package `org.openhab.core.addon.xml`
- `org.openhab.core.addon.xml` depends on `org.openhab.core.config.xml`
- `org.openhab.core.config.xml` depends on `org.openhab.core`

If we merge `org.openhab.core.addon.xml` to `org.openhab.core` we have a cyclic dependency. A possible workaround would be to create a bundle `org.openhab.core.addon` that includes the `org.openhab.core.addon` package from `org.openhab.core` and then `org.openhab.core.addon.xml` package from `org.openhab.core.addon.xml`. WDYT?

**Comment by kaikreuzer** [comment]
Yes, extracting a `org.openhab.core.addon` would make sense then.

**Comment by kaikreuzer** [comment]
> For me it looks like this: [...]

For me as well. We have a `ThingType` dto in both generated packages and I was looking at the wrong one. 🙄 

So yeah, the dtos of config.core need to be exposed. But I would still keep the thing and update dtos in internal packages, since they are clearly not used by any other bundle.

**Comment by J-N-K** [comment]
@kaikreuzer This looks complete now. 

For consistency I have also introduced the code-generation instructions for the add-on bundle, even though the DTOs are not used at the moment (I plan to refactor the whole XML parsing to use the DTOs, so the code is always automatically in-line with the XSD).

**Review by kaikreuzer — APPROVED** [review]
Lgtm, thank you!

**Pull request merged**
