### PR TITLE
Switched PullApprove version to v3

### PR DESCRIPTION
**Pull request by cweitkamp**
Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by wborn** [comment]
It talks so it must be working. :smile:

**Comment by cweitkamp** [comment]
Yes, that are the good news. But now I know how to continue - in a private repo to not bother you with my tests ...

**Comment by maggu2810** [comment]
@cweitkamp Thanks for your effort.

**Comment by cweitkamp** [comment]
I guess I can stop digging. The feature we are looking for has been removed in version 3 (see https://www.pullapprove.com/docs/migration/).

> - Removed PR "requirements"
> Static PR requirements (such as signed-off-by) are no longer directly a part of PullApprove. Instead we're refocusing on the human element of code review, and you can integrate with other status checks via conditions.

And other features are imho nice to have for openhab-core.

Any ideas?

**Comment by wborn** [comment]
How about using probot DCO instead?

https://probot.github.io/apps/dco/

They have lots of other handy apps too like auto labeling, preventing merging WIP PRs etc.!

**Comment by maggu2810** [comment]
I stumbled across it yesterday while I was looking for alternatives.
I have seen DCO from time to time on other repositories.

But to be honest, I cannot judge as I never used it myself.
If it contains the desired check(s), let's (@kaikreuzer your turn :wink:) give it a try.

**Comment by cweitkamp** [comment]
Looks fine. Would be really helpful if it automatically send a notification to the user if the `sign-off` is missing.

```
Hey @{{ author }}, thanks for the PR! The review will start once the tests and CI checks have passed. You will also need to sign your commits and agree with the DCO (see [Sign your Work](https://www.openhab.org/docs/developer/contributing/contributing.html#sign-your-work)).
```

**Comment by kaikreuzer** [comment]
We already used DCO on openhab-android, so I have now activated it on all repos.

**Comment by maggu2810** [comment]
> We already used DCO on openhab-android, so I have now activated it on all repos.

Thanks!

**Comment by cweitkamp** [comment]
:heavy_check_mark:  DCO is working

I changed the syntax of the config file to handle "WIP" status and add how many approvals are required for a PR to be approved.

**Comment by kaikreuzer** [comment]
> add how many approvals are required for a PR to be approved.

This is actually already configured in github itself for the project, see https://github.com/openhab/openhab-core/settings/branch_protection_rules/3893707

**Comment by kaikreuzer** [comment]
I am actually not too sure if we need PullApprove at all by now... If the WIP is the only "feature" for us, this might also be outdated through the new "WIP PR" feature of Github (I didn't yet have a closer look at how that works).

**Comment by cweitkamp** [comment]
Alright. Meaning we can remove PullApprove completely over here?

**Comment by kaikreuzer** [comment]
Would be fine for me, but if anybody wants to keep/use it, go for it.

**Pull request closed without merging**
