### PR TITLE
[automation] Correctly map the state context variable of the ItemStateEvent to the implicit var newState

### PR DESCRIPTION
**Pull request by kaikreuzer**
Fixes https://github.com/openhab/openhab-core/issues/1802

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
Any chance to have this fix merged quickly? 
I would like to test it with the next snapshot.

**Review by cweitkamp — APPROVED** [review]
LGTM. Thanks.

**Comment by lolodomo** [comment]
Thank you. Can you please plan a new snapshot very soon (next night for example) ?

**Pull request merged**
