### PR TITLE
Update nrjavaserial, Fixes #101

### LINKED ISSUE #101: Update nrjavaserial
OH currently uses nrjavaserial-3.9.3 in the serial transport.  I've had issues getting serial communications to work properly (in particular with the UPB binding) and these issues go away with the latest version (3.12.1).  

Is there any particular issues or concerns with updating this library?

### PR DESCRIPTION
**Pull request by cvanorman**
Signed-off-by: Chris Van Orman <vanorman.chris@gmail.com>

### CODE REVIEW

**Comment by cvanorman** [comment]
Ok, I've looked into this as discussed in #101. Some findings:

* commons-lang3 is included as a dependency by nrjavaserial but appears to be unused.
* commons-net is used by a few classes in the rfc2217 package.
* rfc2217 appears to be a copy of another library called jvser.
* OH is not currently exporting the rfc2217 package and so should be unaffected by the removal of commons-net.

For the updated jar (now coming in at ~550KB), all I've done is remove the apache dependencies from it (I did not recompile it).  I've tested this with the UPB binding and it works as expected.

**Comment by kaikreuzer** [comment]
Thanks @cvanorman, sounds great!
Did you manually change the jar that you have now included?
I would love to have a reproducible way to build it (and to see the modifications that are done), so that it could be applied on future updates as well. This could possibly done with the [Maven Shade Plugin](https://maven.apache.org/plugins/maven-shade-plugin/).

**Comment by cvanorman** [comment]
Yes, it was just a manual change.

Shading the serial transport jar is totally possible, but it could introduce some awkwardness inside eclipse as it would complain about the gnu.io package not being available (since it isn't there until after the packaging process).

**Comment by cvanorman** [comment]
Ok, I've done another commit that pulls nrjavaserial via maven central and then includes it inside the jar with the Maven Shade Plugin (excluding the undesirable pieces).

**Comment by kaikreuzer** [comment]
> as it would complain about the gnu.io package not being available

This is correct. So with your latest commit, will we now have errors in the IDE? I agree that this isn't desirable.

**Comment by cvanorman** [comment]
The transport serial project itself will have no errors, but if you have a project reference in an eclipse workspace that includes both the transport serial project and another project that imports the gnu.io package in it's manifest then eclipse will complain.  It will still build via maven, however.

I presume once the repositories are updated, eclipse will handle the references fine as long as you don't have both projects in the same workspace.

The only way around that, would be to split nrjavaserial's build process. This is also possible (and not very difficult), but could get a little political with the current github account not being active.  I just don't have the setup to reliably build all the native libraries and so any work there would result in a manual effort to construct the jar.

**Comment by kaikreuzer** [comment]
Hm, looking at it, there actually is no reason to keep the io.transport.serial bundle at all right now - it only wraps the nrjavaserial lib. But if this jar itself would be a proper OSGi bundle, all we would need to do is to add it to the target platform and we would not even need it in the Eclipse workspace at all.

So maybe we should just put a simple pom.xml somewhere, which creates such an OSGi bundle jar from the nrjavaserial from Maven Central and I would add it to the target platform (e.g. right here: https://github.com/openhab/openhab-deps-repo/).

**Comment by cvanorman** [comment]
I'm not real familiar with how OH's distribution works, so I don't know would look like.  However, I believe the original jar has everything it needs to be an OSGi bundle, we just want to trim it down.  This really only amounts to deleting a folder or two inside it.

**Comment by kaikreuzer** [comment]
Ok, thanks a lot - I have just cherry picked your first commit from this PR, so that #101 is addressed.
I will have a look the next days if I can directly build the jar with your pom.xml and add it to the target platform.

**Comment by kaikreuzer** [comment]
I have reverted this change again: https://github.com/openhab/openhab-core/commit/fcc1bcb2ecd39d90da3ee09d07d87f5ec3cbd95a

**Pull request closed without merging**
