### PR TITLE
Fix AbstractScriptFileWatcher for windows

### LINKED ISSUE #3386: AbstractScriptFileWatcherTest fails on Windows
The AbstractScriptFileWatcherTest fails on Windows.

See: https://github.com/wborn/openhab-core/actions/runs/4211691329/jobs/7310201202

```
[ERROR] Tests run: 21, Failures: 5, Errors: 0, Skipped: 0, Time elapsed: 41.936 s <<< FAILURE! - in org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest
[ERROR] org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest.testLoadTwoCustomFilesAlternativePatternDifferentStartLevels  Time elapsed: 0.878 s  <<< FAILURE!
org.mockito.exceptions.verification.NeverWantedButInvoked: 

scriptEngineManagerMock.createScriptEngine(
    <any string>,
    "C:\Users\RUNNER~1\AppData\Local\Temp\junit339990818789447709\sl70\script.js"
);
Never wanted here:
-> at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest.testLoadTwoCustomFilesAlternativePatternDifferentStartLevels(AbstractScriptFileWatcherTest.java:281)
But invoked here:
-> at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcher.createAndLoad(AbstractScriptFileWatcher.java:337) with arguments: [js, C:\Users\RUNNER~1\AppData\Local\Temp\junit339990818789447709\sl70\script.js]

	at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest.testLoadTwoCustomFilesAlternativePatternDifferentStartLevels(AbstractScriptFileWatcherTest.java:281)
```

---

```
[ERROR] org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest.testOrderingStartlevelFolders  Time elapsed: 11.384 s  <<< FAILURE!
org.mockito.exceptions.verification.VerificationInOrderFailure: 

Verification in order failure
Wanted but not invoked:
scriptEngineManagerMock.createScriptEngine(
    "js",
    "C:\Users\RUNNER~1\AppData\Local\Temp\junit13707886903141936947\sl40\b_script.js"
);
-> at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest.testOrderingStartlevelFolders(AbstractScriptFileWatcherTest.java:369)
Wanted anywhere AFTER following interaction:
scriptEngineManagerMock.createScriptEngine(
    "js",
    "C:\Users\RUNNER~1\AppData\Local\Temp\junit13707886903141936947\sl30\script.js"
);
-> at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcher.createAndLoad(AbstractScriptFileWatcher.java:337)

	at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest.testOrderingStartlevelFolders(AbstractScriptFileWatcherTest.java:369)
```

---

```
[ERROR] org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest.testOrderingWithinSingleStartLevel  Time elapsed: 10.661 s  <<< FAILURE!
org.mockito.exceptions.verification.VerificationInOrderFailure: 

Verification in order failure
Wanted but not invoked:
scriptEngineManagerMock.createScriptEngine(
    "js",
    "C:\Users\RUNNER~1\AppData\Local\Temp\junit3039230032269303023\script.sl66.js"
);
-> at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest.testOrderingWithinSingleStartLevel(AbstractScriptFileWatcherTest.java:342)
Wanted anywhere AFTER following interaction:
scriptEngineManagerMock.createScriptEngine(
    "js",
    "C:\Users\RUNNER~1\AppData\Local\Temp\junit3039230032269303023\script.sl65.js"
);
-> at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcher.createAndLoad(AbstractScriptFileWatcher.java:337)

	at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest.testOrderingWithinSingleStartLevel(AbstractScriptFileWatcherTest.java:342)
```

---

```
[ERROR] org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest.testLoadTwoCustomFilesDifferentStartLevels  Time elapsed: 0.525 s  <<< FAILURE!
org.mockito.exceptions.verification.NeverWantedButInvoked: 

scriptEngineManagerMock.createScriptEngine(
    <any string>,
    "C:\Users\RUNNER~1\AppData\Local\Temp\junit7804289402298206703\script.sl70.js"
);
Never wanted here:
-> at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest.testLoadTwoCustomFilesDifferentStartLevels(AbstractScriptFileWatcherTest.java:247)
But invoked here:
-> at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcher.createAndLoad(AbstractScriptFileWatcher.java:337) with arguments: [js, C:\Users\RUNNER~1\AppData\Local\Temp\junit7804289402298206703\script.sl70.js]

	at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest.testLoadTwoCustomFilesDifferentStartLevels(AbstractScriptFileWatcherTest.java:247)
```

---

```
[ERROR] org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest.testSortsAllFilesInNewDirectory  Time elapsed: 11.798 s  <<< FAILURE!
org.mockito.exceptions.verification.VerificationInOrderFailure: 

Verification in order failure
Wanted but not invoked:
scriptEngineManagerMock.createScriptEngine(
    "js",
    "C:\Users\RUNNER~1\AppData\Local\Temp\junit10401868740813211202\dir\script.sl20.js"
);
-> at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest.testSortsAllFilesInNewDirectory(AbstractScriptFileWatcherTest.java:540)
Wanted anywhere AFTER following interaction:
scriptEngineManagerMock.createScriptEngine(
    "js",
    "C:\Users\RUNNER~1\AppData\Local\Temp\junit10401868740813211202\dir\script2.sl10.js"
);
-> at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcher.createAndLoad(AbstractScriptFileWatcher.java:337)

	at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest.testSortsAllFilesInNewDirectory(AbstractScriptFileWatcherTest.java:540)
```

_Originally posted by @wborn in https://github.com/openhab/openhab-core/issues/3384#issuecomment-1435702135_

### PR DESCRIPTION
**Pull request by J-N-K**
Fixes #3386 

This fixes a real bug with script start-level handling on windows systems.

### CODE REVIEW

**Comment by J-N-K** [comment]
Is there any reason why we don't have the Windows GHA builds for this repo? I guess it's less important for openhab-addons since most file-handling is done in core, but I would appreciate it here.

**Comment by J-N-K** [comment]
GHA failed unrelated.

**Comment by J-N-K** [comment]
I guess this really is an unstable test (it did not fail on my local builds). Since all the tests use 10s timeout and this one uses 1s, most probably the timeout is too short with parallel builds on low power machines.

**Review by wborn — APPROVED** [review]
It builds successfully on Windows now! :+1:

**Pull request merged**
