### PR TITLE
Use exec:exec instead of exec:java goal to avoid classloaders leak

### PR DESCRIPTION
**Pull request by gnodet**
This should help a lot as a workaround to https://github.com/mvndaemon/mvnd/issues/440 which has no real fix.

### CODE REVIEW

**Comment by gnodet** [comment]
@rogierhofboer can you have a look and see if this helps with mvndaemon/mvnd#440 ?

**Comment by rogierhofboer** [comment]
@gnodet This fixes the problem for me. But shouldn't it also work with `java` instead of `exec`?

**Comment by gnodet** [comment]
Yes, it should work with `java`, but the problems is not in `mvnd`, rather in the invoked java code, in this case, the eclipse EMF generator.  So you can raise an issue on their side, but I can't do anything in mvnd if they keep references to the classloaders somehow.

**Comment by kaikreuzer** [comment]
Thanks for this fix @gnodet! May I ask you to sign-off your commit as per our [contribution guidelines](https://www.openhab.org/docs/developer/contributing.html#sign-your-work)? Thanks!

**Comment by gnodet** [comment]
> Thanks for this fix @gnodet! May I ask you to sign-off your commit as per our [contribution guidelines](https://www.openhab.org/docs/developer/contributing.html#sign-your-work)? Thanks!

Done !

**Review by kaikreuzer — APPROVED** [review]
Perfect, thanks a lot!

**Pull request merged**
