### PR TITLE
[rest] fixed item links in rest api

### PR DESCRIPTION
**Pull request by kaikreuzer**
Fixes https://github.com/openhab/openhab-android/issues/2139

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by wborn** [comment]
Do you know if there are more issues with the item linking?
There was also a discussion about a regression introduced by #1385.

**Comment by kaikreuzer** [comment]
This is not at all related to item links (the openHAB concept) and thus not related to #1385.
It is about the "link" field within the REST API responses, see openhab/openhab-android#2139 for details.

**Comment by wborn** [comment]
Yes I understand that. When I did my most recent testing the linking appeared to be buggy but I had no time to further investigate the root cause. So I don't know if it was caused by #1385 or some other issue like this one. Therefor I postponed updating my secondary OH instance to OH3. :wink:

**Comment by kaikreuzer** [comment]
> Therefor I postponed updating my secondary OH instance to OH3

This issue here is hopefully my last "major" bug that I have encountered.
It really helped my to upgrade my (one and only) production system to really have the urge to debug and fix stuff - I can highly recommend doing so and I plan to push all of you to do the same very soon, so be warned 😎 .

**Comment by wborn** [comment]
I don't mind running it on my secondary instance when the linking works. But for my main instance I will first implement a WoL action (https://github.com/openhab/openhab-addons/issues/3799) or I wouldn't be able to turn on my desktop PC using voice commands. :smile:

**Comment by ghys** [comment]
> I will first implement a WoL action

Cool ;) I'm using the exec binding to run `wakeonlan <mac>` but would definitely prefer an action ;)

**Pull request merged**
