### PR TITLE
Create tags_no.properties

### PR DESCRIPTION
**Pull request by jmelhus**
Norwegian translation

Signed-off-by: Jørgen Melhus <jmelhus@gmail.com>

### CODE REVIEW

**Comment by cweitkamp** [comment]
@openhab/core-maintainers As stated in https://github.com/openhab/openhab-core/issues/1012 we need ISO-8859 encoded files for translations. The file added by this PR is encoded in UTF-8. What shall we do?

When I have a look at all available translations for `o.o.c.semantics` I see this:
```
bundles/org.openhab.core.semantics/src/main/resources/tags_de.properties: text/plain; charset=iso-8859-1
bundles/org.openhab.core.semantics/src/main/resources/tags_fr.properties: text/plain; charset=iso-8859-1
bundles/org.openhab.core.semantics/src/main/resources/tags_nl.properties: text/plain; charset=us-ascii
bundles/org.openhab.core.semantics/src/main/resources/tags_no.properties: text/plain; charset=utf-8
bundles/org.openhab.core.semantics/src/main/resources/tags_pl.properties: text/plain; charset=utf-8
bundles/org.openhab.core.semantics/src/main/resources/tags.properties:    text/plain; charset=us-ascii
```

**Comment by jmelhus** [comment]
> 
> 
> Thank you very much for your first contribution over here. As I do not speak Norwegian I will trust in you 😉 .
> 
> Might I ask you to [sign-off your work](https://www.openhab.org/docs/developer/contributing.html#sign-your-work)?

🙂 👍  I believe it should be signed-off now...

**Comment by jmelhus** [comment]
> 
> 
> @openhab/core-maintainers As stated in #1012 we need ISO-8859 encoded files for translations. The file added by this PR is encoded in UTF-8. What shall we do?
> 
> When I have a look at all available translations for `o.o.c.semantics` I see this:
> 
> ```
> bundles/org.openhab.core.semantics/src/main/resources/tags_de.properties: text/plain; charset=iso-8859-1
> bundles/org.openhab.core.semantics/src/main/resources/tags_fr.properties: text/plain; charset=iso-8859-1
> bundles/org.openhab.core.semantics/src/main/resources/tags_nl.properties: text/plain; charset=us-ascii
> bundles/org.openhab.core.semantics/src/main/resources/tags_no.properties: text/plain; charset=utf-8
> bundles/org.openhab.core.semantics/src/main/resources/tags_pl.properties: text/plain; charset=utf-8
> bundles/org.openhab.core.semantics/src/main/resources/tags.properties:    text/plain; charset=us-ascii
> ```

Reading that issue it seems like that the correct thing to do is to change the property files to ISO-8859 encoding, and then when we are on Java 9, change the files to UTF-8. Agree? I can change the encoding in the files to ISO-8859 if you agree upon this...

**Comment by ghys** [comment]
@jmelhus if your goal is to make a complete translation for HABot here are some pointers:
- https://github.com/openhab/openhab-webui/commit/bbf8724abbfcd0fb43f9648eefa2bc4f707731be for a typical PR content, except you don't need `tagattributes_no.properties` (these are now handled by the properties files you just made)
- https://github.com/openhab/openhab-webui/pull/61#issuecomment-496957081 for a way to easily setup a way to make the (required) tests pass.

Hope that helps and thanks!

**Comment by jmelhus** [comment]
@ghys That was my intention. Thanks, I'll look into it!

**Pull request merged**
