### PR TITLE
bump SAT version to 0.6.1 for Tycho builds

### PR DESCRIPTION
**Pull request by J-N-K**
This should be merged immediately before https://github.com/openhab/openhab2-addons/pull/5026.

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
The build is miserably failing, see https://ci.openhab.org/job/openHAB-Core/166/console.
Could this be related to SAT? Not really, but I do not see any other recent code changes...

@wborn Any idea what might have broken the build?

**Comment by J-N-K** [comment]
That looks really strange. I see the same "Errors" in my local build, however (as stated in the text) only as warnings. Since the change should only affect tycho builds and this is bnd, it should not be due to this change.

**Comment by wborn** [comment]
I think last time we saw these errors it was fixed by restarting Jenkins. It also prints:

```
17:15:22 Java HotSpot(TM) 64-Bit Server VM warning: Insufficient space for shared memory file:
17:15:22    8837
17:15:22 Try using the -Djava.io.tmpdir= option to select an alternate temp location.
```

Did you already restart Jenkins after I asked for that a few days ago @kaikreuzer ? (https://github.com/openhab/openhab2-addons/pull/5256#issuecomment-476780086). Are there also plans for improving Jenkins' speed/stability?

**Comment by kaikreuzer** [comment]
I restarted Jenkins once a day...
And yes, I have just restarted it now after reconfiguring the log configuration (which was the culprit for filling up the disk space). So let's touch wood that it runs much more stable from now on!

**Comment by kaikreuzer** [comment]
I just ran https://ci.openhab.org/job/openHAB-Core/167/console with `-DskipChecks=true`, though.
You think there is a chance it succeeds even with SAT enabled? I can try it...

**Comment by wborn** [comment]
Yes it should also work with SAT enabled. The last succesful build `#161` also had SAT enabled, see the [console output](https://ci.openhab.org/job/openHAB-Core/161/consoleFull).

**Comment by J-N-K** [comment]
#168 looks good.

**Comment by kaikreuzer** [comment]
Excellent!

**Pull request merged**
