### PR TITLE
Use sentence casing for ScriptActionType

### PR DESCRIPTION
**Pull request by jimtng**
image

### CODE REVIEW

**Comment by J-N-K** [comment]
Wouldn't `the system has reached start level 100` instead of `When the system has reached start level 100` be the better fix? You can then read it as a sentence with the larger title `When` and `Then`.

**Comment by jimtng** [comment]
This is specifically just for "execute an inline script"

**Comment by jimtng** [comment]
The way I see it, there are two options:
- Change it here in core,
- Check for `script.ScriptAction` and capitalize the first letter on the fly from within webui.

I'd much rather go with option 1, but I found others that need the same treatment, e.g. in MediaActionTypeProvider.java and possibly others.

So it's _easier_ for me to just convert them all on the fly on the webui side. 

In any case the webui isn't going to add `Then ` in front of it, so it still needs to be sentence-cased _somewhere_.

**Comment by wborn** [comment]
> Wouldn't `the system has reached start level 100` instead of `When the system has reached start level 100` be the better fix? 

That's how it should be, see also https://github.com/openhab/openhab-core/issues/1639

**Comment by jimtng** [comment]
> That's how it should be, see also #1639

Thanks for that link! In that case, some clean up is needed in webui to make it consistent. Right now it's still a mixture of upper and lowercase.

**Pull request closed without merging**
