### PR TITLE
Improve AutomationIntegrationJsonTest

### PR DESCRIPTION
**Pull request by J-N-K**

### CODE REVIEW

**Review by wborn — APPROVED** [review]
Thanks for having a look. I'll retrigger GHA several times to see if it helps.

**Comment by J-N-K** [comment]
I already did that some times. Your run is the 9th without failure (if it succeeds).

**Comment by wborn** [comment]
If it's still stable after 15 retries I'll merge it. :crossed_fingers:

**Review by wborn — APPROVED** [review]
CI :slightly_smiling_face:

**Pull request merged**
