### PR TITLE
Fix CodeQL warnings

### PR DESCRIPTION
**Pull request by holgerfriedrich**
Fix CodeQL warnings

* Implicit narrowing conversion in compound assignment

This PR only fixes the first 4 of the warnings.
There are more CodeQL warnings left, help is appreciated:
https://github.com/holgerfriedrich/openhab-core/security/code-scanning

### CODE REVIEW

**Review by wborn — APPROVED** [review]
Thanks!

**Comment by wborn** [comment]
> There are more CodeQL warnings left, help is appreciated:
> https://github.com/holgerfriedrich/openhab-core/security/code-scanning

It's a "404 not found" page for me.

**Comment by florian-h05** [comment]
AFAIK only users with write access to a repo can access its CodeQL results.

**Comment by holgerfriedrich** [comment]
> AFAIK only users with write access to a repo can access its CodeQL results.

Then it might make sense to activate CodeQL scans, then at least the maintainers could see the report.
@openhab/core-maintainers WDYT? Shall I set it up?

**Comment by wborn** [comment]
Do you know how CodeQL compares to [SonarCloud](https://www.sonarsource.com/products/sonarcloud/)? That may be another tool to use for this. I've used SonarQube with [SonarLint](https://www.sonarsource.com/products/sonarlint/) which also nicely integrates with your IDE. That prevents you from commiting such issues in the first place. :wink:

**Comment by J-N-K** [comment]
I'm using SonarLint in IntelliJ (without SonarQube) and it's really nicely integrated.

**Comment by florian-h05** [comment]
> Do you know how CodeQL compares to SonarCloud?

No, unfortunately not.

**Pull request merged**
