### PR TITLE
Added nullness annotations to fix NPE in HttpServiceUtil

### PR DESCRIPTION
**Pull request by cweitkamp**
- Added nullness annotations to fix NPE in `HttpServiceUtil`

```
2021-03-12 12:28:48.124 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while calling thing handler factory 'org.openhab.binding.chromecast.internal.factory.ChromecastHandlerFactory@6a197e': null
java.lang.NullPointerException: null
	at org.openhab.core.net.HttpServiceUtil.getHttpServicePortProperty(HttpServiceUtil.java:54) ~[?:?]
	at org.openhab.core.net.HttpServiceUtil.getHttpServicePort(HttpServiceUtil.java:39) ~[?:?]
	at org.openhab.binding.chromecast.internal.factory.ChromecastHandlerFactory.createCallbackUrl(ChromecastHandlerFactory.java:101) ~[?:?]
	at org.openhab.binding.chromecast.internal.factory.ChromecastHandlerFactory.createHandler(ChromecastHandlerFactory.java:80) ~[?:?]
	at org.openhab.core.thing.binding.BaseThingHandlerFactory.registerHandler(BaseThingHandlerFactory.java:129) ~[bundleFile:?]
	at org.openhab.core.thing.internal.ThingManagerImpl.doRegisterHandler(ThingManagerImpl.java:664) [bundleFile:?]
	at org.openhab.core.thing.internal.ThingManagerImpl.registerHandler(ThingManagerImpl.java:641) [bundleFile:?]
	at org.openhab.core.thing.internal.ThingManagerImpl.registerAndInitializeHandler(ThingManagerImpl.java:1110) [bundleFile:?]
	at org.openhab.core.thing.internal.ThingManagerImpl.lambda$10(ThingManagerImpl.java:1092) [bundleFile:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source) [?:?]
	at java.util.concurrent.CopyOnWriteArraySet.forEach(Unknown Source) [?:?]
	at org.openhab.core.thing.internal.ThingManagerImpl.lambda$9(ThingManagerImpl.java:1089) [bundleFile:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) [?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) [?:?]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) [?:?]
	at org.openhab.core.thing.internal.ThingManagerImpl.handleThingHandlerFactoryAddition(ThingManagerImpl.java:1088) [bundleFile:?]
	at org.openhab.core.thing.internal.ThingManagerImpl.onReadyMarkerAdded(ThingManagerImpl.java:1076) [bundleFile:?]
	at org.openhab.core.internal.service.ReadyServiceImpl.lambda$0(ReadyServiceImpl.java:52) [bundleFile:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) [?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) [?:?]
	at java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) [?:?]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) [?:?]
	at org.openhab.core.internal.service.ReadyServiceImpl.notifyTrackers(ReadyServiceImpl.java:79) [bundleFile:?]
	at org.openhab.core.internal.service.ReadyServiceImpl.markReady(ReadyServiceImpl.java:52) [bundleFile:?]
	at org.openhab.core.config.xml.osgi.XmlDocumentBundleTracker.registerReadyMarker(XmlDocumentBundleTracker.java:419) [bundleFile:?]
	at org.openhab.core.config.xml.osgi.XmlDocumentBundleTracker.finishBundle(XmlDocumentBundleTracker.java:362) [bundleFile:?]
	at org.openhab.core.config.xml.osgi.XmlDocumentBundleTracker.processBundle(XmlDocumentBundleTracker.java:385) [bundleFile:?]
	at org.openhab.core.config.xml.osgi.XmlDocumentBundleTracker$2.run(XmlDocumentBundleTracker.java:347) [bundleFile:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by wborn** [comment]
Looks like even with this fix there will be another NPE in that handler when the `bundleContext` is null, see [ChromecastHandlerFactory.java#L83-L84
](https://github.com/openhab/openhab-addons/blob/f3a517e4e1630d30cfb43a93c8800f04fcc5124c/bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/factory/ChromecastHandlerFactory.java#L83-L84)

Allowing a null bundleContext may also hide programming errors because the utility class needs it to do anything useful.

**Comment by cweitkamp** [comment]
Yes, that is a valid point. I looked into other util / helper classes which are using the `BundleContext` and found [TransformationHelper](https://github.com/openhab/openhab-core/blob/4a79e9bfe7dca9f6abd1e40d3eb398a9aa2c8988/bundles/org.openhab.core.transform/src/main/java/org/openhab/core/transform/TransformationHelper.java#L61) which does the same. We maybe want to add a logger message then.

Otherwise I suggest to change to `@Nullable`:
https://github.com/openhab/openhab-core/blob/4a79e9bfe7dca9f6abd1e40d3eb398a9aa2c8988/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/binding/BaseThingHandlerFactory.java#L59

wrt Chromecast: I can prepare an additional fix for the factory. Implementations can use the protected `getBundleContext()` method of `BaseThingHandlerFactory` to be safe. It returns a non-null `BundleContext` and will throw an `IllegalStateException` if `bundleContext` is `null`.

**Comment by wborn** [comment]
Do you also have an idea why the `bundleContext` was `null`? Was it creating a handler while the factory was deactivated? I see it sets the `bundleContext` to `null` in the `BaseThingHandlerFactory.deactivate` method. It might be easier to detect this in `BaseThingHandlerFactory.registerHandler` and ignore such calls. What may also help is to synchronize the `deactivate` and `registerHandler`  methods in the `BaseThingHandlerFactory`.

Making the `bundleContext` `@Nullable` will cause a lot of work and throwing a `IllegalStateException`s instead of a `NullPointerException`s isn't a big improvement. :wink:

**Comment by cweitkamp** [comment]
Yes, the `bundleContext` is set to `null` during deactivation of the factory. The NPE occurred in my environment after I uninstalled a different add-on. My log file looks like all bundles are restarted when uninstalling that binding. Do not know why that was happening.

**Comment by J-N-K** [comment]
You could also change the field to `private`. There is a `getBundleContext` method that takes care of the null check.

**Comment by wborn** [comment]
If the deactivation can be detected I think it would be best to handle it similarly as if there is no (active) factory registered for that specific thing type. It will probably log some warning/error that the thing handler could not be created.

**Comment by cweitkamp** [comment]
Regardless what we plan to do it will be a bigger refactoring for the sake of stability. It will be beyond the scope of this PR and should be tracked in a dedicated issue.

I will change this PR laten and remove the `@Nullable` annotation on the method parameters.

**Review by wborn — APPROVED** [review]
Thanks!

**Pull request merged**
