### PR TITLE
Fixed typo in class name TrustAllTrustMananger.

### PR DESCRIPTION
**Pull request by radicale**
Will require changes in a couple addons as well.

### CODE REVIEW

**Comment by cweitkamp** [comment]
Thanks for fixing this. We may want add the API breaking label here.

May I ask you to submit a fix for openHAB add-ons too?

**Comment by radicale** [comment]
> May I ask you to submit a fix for openHAB add-ons too?
Sure.

**Comment by radicale** [comment]
Added PR 8892 in openhab-addons

**Review by kaikreuzer — APPROVED** [review]
Good catch before the release of 3.0 - still a good time to do such breaking changes.

**Pull request merged**
