### PR TITLE
Get and set the thing configuration from rules

### PR DESCRIPTION
**Pull request by J-N-K**
Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by cweitkamp** [comment]
I like it. Looks a little bit like #583.

**Comment by J-N-K** [comment]
Didn't see that. The only difference I see is that you get/set the whole map while I only get/set one parameter.

**Comment by lolodomo** [comment]
By curiosity, what can be the usage ?

**Comment by cweitkamp** [comment]
> The only difference I see is that you get/set the whole map while I only get/set one parameter

No problem. Yes, your approach maybe is the better one. But there are still some more things to consider.

1. We should think forward and add an action for the new rule engine too.
2. What about adding a Karaf console command?
3. When we allow setting the configuration parameters doesn't it make sense to take the configuration description into account? And normalize the values like we do in the REST endpoint?
4. What about channel configuations?

**Pull request closed without merging**
