### PR TITLE
Fix resolver errors during bundle add-on installation

### LINKED ISSUE #4222: Snapshot 4069: failed to install bundles at startup
```
11:57:06.397 [ERROR] [.core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-hue, ...: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=shell; type=karaf.feature; version="[4.4.5,4.4.5]"; filter:="(&(osgi.identity=shell)(type=karaf.feature)(version>=4.4.5)(version<=4.4.5))" [caused by: Unable to resolve shell/4.4.5: missing requirement [shell/4.4.5] osgi.identity; osgi.identity=org.apache.karaf.shell.core; type=osgi.bundle; version="[4.4.5,4.4.5]"; resolution:=mandatory [caused by: Unable to resolve org.apache.karaf.shell.core/4.4.5: missing requirement [org.apache.karaf.shell.core/4.4.5] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.osgi.framework)(version>=1.0.0)(!(version>=3.0.0)))" [caused by: Unable to resolve org.eclipse.osgi/3.18.0.v20220516-2155: missing requirement [org.eclipse.osgi/3.18.0.v20220516-2155] osgi.ee; filter:="(| (&(osgi.ee=JavaSE)(version=1.8)) (&(osgi.ee=JavaSE/compact1)(version=1.8)) )"]]]
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=instance; type=karaf.feature; version="[4.4.5,4.4.5]"; filter:="(&(osgi.identity=instance)(type=karaf.feature)(version>=4.4.5)(version<=4.4.5))" [caused by: Unable to resolve instance/4.4.5: missing requirement [instance/4.4.5] osgi.identity; osgi.identity=org.apache.karaf.instance.core; type=osgi.bundle; version="[4.4.5,4.4.5]"; resolution:=mandatory [caused by: Unable to resolve org.apache.karaf.instance.core/4.4.5: missing requirement [org.apache.karaf.instance.core/4.4.5] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.osgi.framework)(version>=1.0.0)(!(version>=3.0.0)))" [caused by: Unable to resolve org.eclipse.osgi/3.18.0.v20220516-2155: missing requirement [org.eclipse.osgi/3.18.0.v20220516-2155] osgi.ee; filter:="(| (&(osgi.ee=JavaSE)(version=1.8)) (&(osgi.ee=JavaSE/compact1)(version=1.8)) )"]]]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
        at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:433)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:420)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:374)
        at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:256)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:399)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve instance/4.4.5: missing requirement [instance/4.4.5] osgi.identity; osgi.identity=org.apache.karaf.instance.core; type=osgi.bundle; version="[4.4.5,4.4.5]"; resolution:=mandatory [caused by: Unable to resolve org.apache.karaf.instance.core/4.4.5: missing requirement [org.apache.karaf.instance.core/4.4.5] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.osgi.framework)(version>=1.0.0)(!(version>=3.0.0)))" [caused by: Unable to resolve org.eclipse.osgi/3.18.0.v20220516-2155: missing requirement [org.eclipse.osgi/3.18.0.v20220516-2155] osgi.ee; filter:="(| (&(osgi.ee=JavaSE)(version=1.8)) (&(osgi.ee=JavaSE/compact1)(version=1.8)) )"]]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
        ... 12 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.apache.karaf.instance.core/4.4.5: missing requirement [org.apache.karaf.instance.core/4.4.5] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.osgi.framework)(version>=1.0.0)(!(version>=3.0.0)))" [caused by: Unable to resolve org.eclipse.osgi/3.18.0.v20220516-2155: missing requirement [org.eclipse.osgi/3.18.0.v20220516-2155] osgi.ee; filter:="(| (&(osgi.ee=JavaSE)(version=1.8)) (&(osgi.ee=JavaSE/compact1)(version=1.8)) )"]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
        ... 13 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.eclipse.osgi/3.18.0.v20220516-2155: missing requirement [org.eclipse.osgi/3.18.0.v20220516-2155] osgi.ee; filter:="(| (&(osgi.ee=JavaSE)(version=1.8)) (&(osgi.ee=JavaSE/compact1)(version=1.8)) )"
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
        ... 14 more
11:57:09.353 [ERROR] [.core.karaf.internal.FeatureInstaller] - Failed to refresh bundles after processing config update
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=instance; type=karaf.feature; version="[4.4.5,4.4.5]"; filter:="(&(osgi.identity=instance)(type=karaf.feature)(version>=4.4.5)(version<=4.4.5))" [caused by: Unable to resolve instance/4.4.5: missing requirement [instance/4.4.5] osgi.identity; osgi.identity=org.apache.karaf.instance.core; type=osgi.bundle; version="[4.4.5,4.4.5]"; resolution:=mandatory [caused by: Unable to resolve org.apache.karaf.instance.core/4.4.5: missing requirement [org.apache.karaf.instance.core/4.4.5] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.osgi.framework)(version>=1.0.0)(!(version>=3.0.0)))" [caused by: Unable to resolve org.eclipse.osgi/3.18.0.v20220516-2155: missing requirement [org.eclipse.osgi/3.18.0.v20220516-2155] osgi.ee; filter:="(| (&(osgi.ee=JavaSE)(version=1.8)) (&(osgi.ee=JavaSE/compact1)(version=1.8)) )"]]]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:433) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:420) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:374) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:256) ~[?:?]
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:399) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004) ~[?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve instance/4.4.5: missing requirement [instance/4.4.5] osgi.identity; osgi.identity=org.apache.karaf.instance.core; type=osgi.bundle; version="[4.4.5,4.4.5]"; resolution:=mandatory [caused by: Unable to resolve org.apache.karaf.instance.core/4.4.5: missing requirement [org.apache.karaf.instance.core/4.4.5] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.osgi.framework)(version>=1.0.0)(!(version>=3.0.0)))" [caused by: Unable to resolve org.eclipse.osgi/3.18.0.v20220516-2155: missing requirement [org.eclipse.osgi/3.18.0.v20220516-2155] osgi.ee; filter:="(| (&(osgi.ee=JavaSE)(version=1.8)) (&(osgi.ee=JavaSE/compact1)(version=1.8)) )"]]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341) ~[org.eclipse.osgi-3.18.0.jar:?]
        ... 12 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.apache.karaf.instance.core/4.4.5: missing requirement [org.apache.karaf.instance.core/4.4.5] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.osgi.framework)(version>=1.0.0)(!(version>=3.0.0)))" [caused by: Unable to resolve org.eclipse.osgi/3.18.0.v20220516-2155: missing requirement [org.eclipse.osgi/3.18.0.v20220516-2155] osgi.ee; filter:="(| (&(osgi.ee=JavaSE)(version=1.8)) (&(osgi.ee=JavaSE/compact1)(version=1.8)) )"]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341) ~[org.eclipse.osgi-3.18.0.jar:?]
        ... 12 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.eclipse.osgi/3.18.0.v20220516-2155: missing requirement [org.eclipse.osgi/3.18.0.v20220516-2155] osgi.ee; filter:="(| (&(osgi.ee=JavaSE)(version=1.8)) (&(osgi.ee=JavaSE/compact1)(version=1.8)) )"
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341) ~[org.eclipse.osgi-3.18.0.jar:?]
        ... 12 more
```

Two errors:

1. Failed installing ...
2. Failed to refresh bundles after processing config update

This is repeated ever and ever...

### PR DESCRIPTION
**Pull request by J-N-K**
Fixes #4222

@lolodomo @holgerfriedrich @jimtng Can you confirm this also fixes the issues on your systems? My Win11/Parallels now works fine.

### CODE REVIEW

**Comment by jimtng** [comment]
When I simply copied `~/.m2/repository/org/openhab/core/bundles/` into my openhab installation `runtime/system/org/openhab/core/bundles/` and tried starting it up, the error is still there.

How do I rebuild the entire distro?

**Comment by J-N-K** [comment]
I think the important file is `runtime/system/org/openhab/distro/distro/4.2.0-SNAPSHOT/distro-4.2.0-SNAPSHOT-features.xml`. If you edit that file (and remove the `conditional` sections (like in this PR) it should work. Make sure to clean cache and tmp before starting openHAB.

**Comment by jimtng** [comment]
Thanks! That did the trick

I saw a few errors like these:
```
00:14:30.315 [ERROR] [.core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-core-config-discovery-addon-mdns, openhab-automation-pidcontroller, openhab-core-config-discovery-addon-upnp, openhab-automation-jrubyscripting, openhab-core-config-discovery-addon-usb, openhab-core-config-discovery-addon-ip': Error restarting bundles:
        Exception in org.glassfish.hk2.osgiresourcelocator.Activator.start() of bundle org.glassfish.hk2.osgi-resource-locator.
```

```
00:15:21.503 [ERROR] [.core.karaf.internal.FeatureInstaller] - Failed to refresh bundles after processing config update
org.apache.karaf.features.internal.util.MultiException: Error restarting bundles:
        Exception in org.glassfish.hk2.osgiresourcelocator.Activator.start() of bundle org.glassfish.hk2.osgi-resource-locator.
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1049) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
        Suppressed: org.osgi.framework.BundleException: Exception in org.glassfish.hk2.osgiresourcelocator.Activator.start() of bundle org.glassfish.hk2.osgi-resource-locator.
                at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:839) ~[org.eclipse.osgi-3.18.0.jar:?]
                at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767) ~[org.eclipse.osgi-3.18.0.jar:?]
                at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032) ~[org.eclipse.osgi-3.18.0.jar:?]
                at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371) ~[org.eclipse.osgi-3.18.0.jar:?]
                at org.eclipse.osgi.container.Module.doStart(Module.java:605) ~[org.eclipse.osgi-3.18.0.jar:?]
                at org.eclipse.osgi.container.Module.start(Module.java:468) ~[org.eclipse.osgi-3.18.0.jar:?]
                at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445) ~[org.eclipse.osgi-3.18.0.jar:?]
                at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:464) ~[org.eclipse.osgi-3.18.0.jar:?]
                at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:165) ~[?:?]
                at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1160) ~[?:?]
                at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1041) ~[?:?]
                at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069) ~[?:?]
                at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004) ~[?:?]
                at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
                at java.lang.Thread.run(Thread.java:840) [?:?]
        Caused by: java.lang.IllegalStateException: Already initialzed with [org.glassfish.hk2.osgiresourcelocator.ServiceLoaderImpl@222b7a14]
                at org.glassfish.hk2.osgiresourcelocator.ServiceLoader.initialize(ServiceLoader.java:43) ~[?:?]
                at org.glassfish.hk2.osgiresourcelocator.Activator.start(Activator.java:32) ~[?:?]
                at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818) ~[org.eclipse.osgi-3.18.0.jar:?]
                at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1) ~[org.eclipse.osgi-3.18.0.jar:?]
                at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
                at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810) ~[org.eclipse.osgi-3.18.0.jar:?]
                ... 16 more
```

However, the bundles got installed despite the errors.

e.g. I tried adding astro, and this happened, even though astro binding got installed

```
00:19:22.255 [ERROR] [.core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-astro': Error restarting bundles:
        Exception in org.glassfish.hk2.osgiresourcelocator.Activator.start() of bundle org.glassfish.hk2.osgi-resource-locator.
00:19:22.869 [ERROR] [.core.karaf.internal.FeatureInstaller] - Failed to refresh bundles after processing config update
org.apache.karaf.features.internal.util.MultiException: Error restarting bundles:
        Exception in org.glassfish.hk2.osgiresourcelocator.Activator.start() of bundle org.glassfish.hk2.osgi-resource-locator.
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1049) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
        Suppressed: org.osgi.framework.BundleException: Exception in org.glassfish.hk2.osgiresourcelocator.Activator.start() of bundle org.glassfish.hk2.osgi-resource-locator.
                at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:839) ~[org.eclipse.osgi-3.18.0.jar:?]
                at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767) ~[org.eclipse.osgi-3.18.0.jar:?]
                at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032) ~[org.eclipse.osgi-3.18.0.jar:?]
                at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371) ~[org.eclipse.osgi-3.18.0.jar:?]
                at org.eclipse.osgi.container.Module.doStart(Module.java:605) ~[org.eclipse.osgi-3.18.0.jar:?]
                at org.eclipse.osgi.container.Module.start(Module.java:468) ~[org.eclipse.osgi-3.18.0.jar:?]
                at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445) ~[org.eclipse.osgi-3.18.0.jar:?]
                at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:464) ~[org.eclipse.osgi-3.18.0.jar:?]
                at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:165) ~[?:?]
                at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1160) ~[?:?]
                at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1041) ~[?:?]
                at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069) ~[?:?]
                at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004) ~[?:?]
                at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
                at java.lang.Thread.run(Thread.java:840) [?:?]
        Caused by: java.lang.IllegalStateException: Already initialzed with [org.glassfish.hk2.osgiresourcelocator.ServiceLoaderImpl@222b7a14]
                at org.glassfish.hk2.osgiresourcelocator.ServiceLoader.initialize(ServiceLoader.java:43) ~[?:?]
                at org.glassfish.hk2.osgiresourcelocator.Activator.start(Activator.java:32) ~[?:?]
                at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818) ~[org.eclipse.osgi-3.18.0.jar:?]
                at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1) ~[org.eclipse.osgi-3.18.0.jar:?]
                at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
                at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810) ~[org.eclipse.osgi-3.18.0.jar:?]
                ... 16 more
```

**Comment by jimtng** [comment]
I tried the following:

- Install a clean snapshot build 4070 
- Edit ./runtime/system/org/openhab/distro/distro/4.2.0-SNAPSHOT/distro-4.2.0-SNAPSHOT-features.xml and remove the `<conditional>` tags just like in this PR
- Start openhab
- No errors

It appears that the changes in this PR to FeatureInstaller is not necessary. Only the change in the xml is required.

**Comment by J-N-K** [comment]
Correct, it's not necessary, but it should make the whole process a bit more safe (in case of the unlikely case that a subsequent config change happens before the refresh finished).

**Review by jimtng — APPROVED** [review]

**Comment by holgerfriedrich** [comment]
Confirmed to work with a clean build on Windows. Thanks a lot, @J-N-K! 🎉

**Review by holgerfriedrich — APPROVED** [review]

**Comment by holgerfriedrich** [comment]
I wanted to check for implications of activating the finders on other OS as well, e.g. see Windows:

```
255 │ Active   │  80 │ 4.2.0.202405111317    │ openHAB Core :: Bundles :: Configuration USB-Serial Discovery for Linux using sysfs scanning
257 │ Active   │  80 │ 4.2.0.202405111321    │ openHAB Core :: Bundles :: Configuration USB-Serial Discovery for Windows
```

I did not see a problem on Windows and as this is a blocking issue, lets go for the merge first.

**Comment by holgerfriedrich** [comment]
@openhab/core-maintainers can anyone please trigger a snapshot build?

**Comment by J-N-K** [comment]
Done

**Comment by lolodomo** [comment]
> I wanted to check for implications of activating the finders on other OS as well, e.g. see Windows:
> 
> ```
> 255 │ Active   │  80 │ 4.2.0.202405111317    │ openHAB Core :: Bundles :: Configuration USB-Serial Discovery for Linux using sysfs scanning
> 257 │ Active   │  80 │ 4.2.0.202405111321    │ openHAB Core :: Bundles :: Configuration USB-Serial Discovery for Windows
> ```
> 
> I did not see a problem on Windows and as this is a blocking issue, lets go for the merge first.

I agree that a solution has to be found. I have now a bundle for Windows on RPI.
```
256 x Active x  80 x 4.2.0.202405111809    x openHAB Core :: Bundles :: USB Suggested Add-on Finder
257 x Active x  80 x 4.2.0.202405111808    x openHAB Core :: Bundles :: Configuration USB-Serial Discovery
258 x Active x  80 x 4.2.0.202405111809    x openHAB Core :: Bundles :: Configuration USB-Serial Discovery for Linux using sysfs scanning
259 x Active x  80 x 4.2.0.202405111809    x openHAB Core :: Bundles :: Configuration USB-Serial Discovery using ser2net mDNS scanning
260 x Active x  80 x 4.2.0.202405111809    x openHAB Core :: Bundles :: Configuration USB-Serial Discovery for Windows
```

**Comment by J-N-K** [comment]
That's more cosmetic, correct? It does not result in any malfunction, as far as I know.

**Comment by holgerfriedrich** [comment]
Neither a malfunction nor a log m stage seems to be caused by this. IMHO we can leave it as it is for now.

**Comment by lolodomo** [comment]
Yes, it seems to be without any impact.

**Comment by lolodomo** [comment]
Someone in the community forum is reporting this error while he uses openhabian :
```
[ERROR] [y.internal.WindowsUsbSerialDiscovery] - bundle org.openhab.core.config.discovery.usbserial.windowsregistry:4.2.0.M3 (320)[org.openhab.core.config.discovery.usbserial.windowsregistry.internal.WindowsUsbSerialDiscovery(389)] : The deactivate method has thrown an exception
```

**Comment by lolodomo** [comment]
The error occurs when stopping openHAB.

**Comment by mherwege** [comment]
> The error occurs when stopping openHAB.

Fixed with https://github.com/openhab/openhab-core/pull/4235

**Pull request merged**
