### PR TITLE
Bump netty to 4.1.72.Final for log4j2 2.15.0 fix

### PR DESCRIPTION
**Pull request by Skinah**
Nettys news/change log is here:
https://netty.io/news/2021/12/13/4-1-72-Final.html

Contains an update to log4j2 2.15.0 to fix security issue.

Also have made a PR here for the addons repo changes..
https://github.com/openhab/openhab-addons/pull/11826

Signed-off-by: Matthew Skinner <matt@pcmus.com>

### CODE REVIEW

**Comment by wborn** [comment]
The Hive MQTT client really seem to prefer some packages from another Netty version causing the feature validation to fail with this upgrade:

`Message: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab.tp-hivemqclient; type=karaf.feature; version=3.3.0.SNAPSHOT; filter:="(&(osgi.identity=openhab.tp-hivemqclient)(type=karaf.feature)(version>=3.3.0.SNAPSHOT))" [caused by: Unable to resolve openhab.tp-hivemqclient/3.3.0.SNAPSHOT: missing requirement [openhab.tp-hivemqclient/3.3.0.SNAPSHOT] osgi.identity; osgi.identity=com.hivemq.client.mqtt; type=osgi.bundle; version="[1.2.2,1.2.2]"; resolution:=mandatory [caused by: Unable to resolve com.hivemq.client.mqtt/1.2.2: missing requirement [com.hivemq.client.mqtt/1.2.2] osgi.wiring.package; filter:="(&(osgi.wiring.package=io.netty.channel.epoll)(version>=4.1.0)(!(version>=4.2.0)))"]]`

**Comment by J-N-K** [comment]
I guess `io.netty/netty-transport-classes-epoll/4.1.72` is missing (which exists since 4.1.70).

**Comment by wborn** [comment]
Perhaps you can add that new bundle to the feature and see if it fixes the issue @Skinah?

**Comment by Skinah** [comment]
Done. Build errors fixed.

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Comment by kaikreuzer** [comment]
@Skinah It seems as if this [broke the add-ons build](https://ci.openhab.org/job/openHAB-Addons/572/console) due to a tellstick dependency on Netty:
```
missing requirement [org.openhab.binding.tellstick/3.3.0.202112230404] osgi.wiring.package; filter:="(&(osgi.wiring.package=io.netty.channel.kqueue)(version>=4.1.0)(!(version>=5.0.0)))"]]
```
Could you please have a look?

**Comment by kaikreuzer** [comment]
I've reverted this for now with https://github.com/openhab/openhab-core/pull/2646 in order to have the build working again.
Please come up with a new PR once it is clear, why simply bumping the version does not work.

**Pull request merged**
