### PR TITLE
removed classpath entries of non-existent folders in order to solve compilation errors in IDE

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
What's the compilation errors that are caused by that classpath entries?
The entries are `maven.pomderived` and also marked `optional`.

I also was not aware of any error in my IDEs.

**Comment by kaikreuzer** [comment]
Well, the usual error: Eclipse shows an exclamation mark on the project and won't even start compiling it due to errors in the build path (so my issue title is not fully correct, I agree).

Try the official IDE with a clean checkout and you will see.

**Comment by maggu2810** [comment]
For me the error is caused by:

```
Description	Resource	Path	Location	Type
Project 'org.openhab.core.model.thing' is missing required source folder: 'model'	org.openhab.core.model.thing		Build path	Build Path Problem
```

There is no lifecycle mapping for the xtend plugin, so you need to build the model once with Maven.

So, the src-gen directories are missing:

See e.g.: `find -name src-gen -type d`

We could apply this change, but I don't think it will solve the problem (and I also don't think there is any need to remove that lines as its derived by the POM).

Have you tried e.g.:

```
mvn clean install -DskipChecks=true -am -pl bundles/org.openhab.core.model.item/ -pl bundles/org.openhab.core.model.persistence/ -pl bundles/org.openhab.core.model.rule/ -pl bundles/org.openhab.core.model.script/ -pl bundles/org.openhab.core.model.sitemap/ -pl bundles/org.openhab.core.model.thing/
```

**Comment by maggu2810** [comment]
I can confirm that the Eclipse IDE errors are gone as soon as the src-gen folders are created (with their content).

**Comment by kaikreuzer** [comment]
> For me the error is caused by

This is what is displayed to me as well, but if you then check the buildpath in Eclipse and fix its error, this message disappears as well - and Eclipse is correct, the path does not exist.

> Have you tried

I have tried the standard IDE setup, which every developer will use - it has to work without doing any manual magic on the command line. And this PR makes it work. Do you expect any issues?

**Comment by maggu2810** [comment]
Hm, my idea has been that the cause is not the presence of this line, but that your changes triggers another build or something similar.
So, I am not sure, that it helps if you install the IDE with that lines removed.

But we can give it a try.

**Comment by maggu2810** [comment]
> And this PR makes it work.

Okay, if this change makes it work, let's go.

**Comment by maggu2810** [comment]
> So, I am not sure, that it helps if you install the IDE with that lines removed.

For me this changes does not solve the problem:

Description | Resource | Path | Location | Type
--- | --- | --- | --- | ---
Project 'org.openhab.core.model.item' is missing required source folder: 'model' | org.openhab.core.model.item | | Build path | Build Path Problem
Project 'org.openhab.core.model.persistence' is missing required source folder: 'model' | org.openhab.core.model.persistence |  | Build path | Build Path Problem
Project 'org.openhab.core.model.rule' is missing required source folder: 'model' | org.openhab.core.model.rule |  | Build path | Build Path Problem
Project 'org.openhab.core.model.script' is missing required source folder: 'model' | org.openhab.core.model.script |  | Build path | Build Path Problem
Project 'org.openhab.core.model.sitemap' is missing required source folder: 'model' | org.openhab.core.model.sitemap |  | Build path | Build Path Problem
Project 'org.openhab.core.model.thing' is missing required source folder: 'model' | org.openhab.core.model.thing |  | Build path | Build Path Problem

**Comment by maggu2810** [comment]
That are the goals that are exectued while executing

```
mvn clean install -pl bundles/org.openhab.core.model.item -DskipTests=true -DskipChecks=true
```

```
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ org.openhab.core.model.item ---
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java) @ org.openhab.core.model.item ---
[INFO] --- directory-maven-plugin:0.3.1:highest-basedir (directories) @ org.openhab.core.model.item ---
[INFO] --- build-helper-maven-plugin:3.0.0:add-source (default) @ org.openhab.core.model.item ---
[INFO] --- build-helper-maven-plugin:3.0.0:add-resource (default) @ org.openhab.core.model.item ---
[INFO] --- exec-maven-plugin:1.4.0:java (default) @ org.openhab.core.model.item ---
[INFO] --- xtend-maven-plugin:2.17.0:compile (default) @ org.openhab.core.model.item ---
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ org.openhab.core.model.item ---
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ org.openhab.core.model.item ---
[INFO] --- bnd-maven-plugin:4.2.0:bnd-process (default) @ org.openhab.core.model.item ---
[INFO] --- xtend-maven-plugin:2.17.0:xtend-install-debug-info (default) @ org.openhab.core.model.item ---
[INFO] --- xtend-maven-plugin:2.17.0:testCompile (default) @ org.openhab.core.model.item ---
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ org.openhab.core.model.item ---
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ org.openhab.core.model.item ---
[INFO] --- xtend-maven-plugin:2.17.0:xtend-test-install-debug-info (default) @ org.openhab.core.model.item ---
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ org.openhab.core.model.item ---
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ org.openhab.core.model.item ---
[INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ org.openhab.core.model.item ---
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ org.openhab.core.model.item ---
```

There "exec-maven-plugin" executes "org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher".
There is no lifecycle mapping for that plugin so the "Mwe2Launcher" is not executed inside the IDE.

**Pull request merged**
