### PR TITLE
enable nullness checks on Maven build again

### PR DESCRIPTION
**Pull request by maggu2810**

### CODE REVIEW

**Comment by maggu2810** [comment]
The ECJ configuration previously used in the ESH build has been reused.

**Comment by kaikreuzer** [comment]
@maggu2810 It seems the behavior is somewhat different to before - the Zigbee binding fails to build with null check errors, which do not seem to be correct (it complains about a null parameter although the field is marked as nullable). The very same code compiled before successfully. Any idea? https://ci.openhab.org/job/PR-org.openhab.binding.zigbee/455/org.openhab.binding$org.openhab.binding.zigbee.ember/console

**Comment by maggu2810** [comment]
@kaikreuzer I don't understand.

This commit changes the compiler and the settings of that compiler that is used to compile the openHAB Core bundles. The ECJ can check the nullness stuff at compile time.
The bytecode that is generated by the compiler should not differ (at least with respect to the nullness annotations) from the bytecode that has been generated by another compiler.

Are you sure that you compile against the current version of https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.config.discovery.usbserial/src/main/java/org/eclipse/smarthome/config/discovery/usbserial/UsbSerialDeviceInformation.java#L48

**Comment by maggu2810** [comment]
I used "JD-GUI" to decompile the class file and it seems the `@NonNullByDefault` class annotation is still present but the annotation of the constructor arguments is missing.

Sorry, will have a look at.

**Comment by maggu2810** [comment]
Using an alternate ECJ version seems to solve it.
Will try to find the most recent one that works.

After you can use the artifact results, we should report it upstream.

**Comment by maggu2810** [comment]
My findings (please check it yourself, perhaps I am wrong):

This is not caused by the build JAR files and its bytecode.
It is caused because your tycho build infers the settings that we apply to our pure Maven openHAB Core project.

I can compile the zigbee ember binding using the same config.discovery.usbserial JAR file but changing the openHAB Core base reactor POM.

I already stated in the other issue that the Tycho build should not depend on settings of the pure Maven build as its build settings does not need to work for Tycho builds.

from child to parent:
* org.openhab/pom-tycho
* => org.openhab/pom
* => org.openhab.core.bom/org.openhab.core.bom.openhab-core
* => org.openhab.core.bom/org.openhab.core.reactor.bom
* => org.openhab.core/org.openhab.core.reactor

**Pull request merged**
