### PR TITLE
[rest] Allow colons in sse topics filter

### LINKED ISSUE #1043: [REST] Subscribing to single thing endpoint not working
I am trying to subscribe to a single thing SSE events over rest API using the filter `smarthome/things/{thingUID}/statuschanged` but it seems like there is something wrong.

For example, I tried subscribing to simple NTP thing using 'http://localhost:8080/rest/events?topics=smarthome/things/ntp:ntp:local/updated' but this returned 
`HTTP ERROR 400`
`Problem accessing /rest/events. Reason:`
`Bad Request`

I tried replacing the colons with underscores, the subscription started but it doesn't send any events.

Attached jetty debug log for reference.
[jetty.log](https://github.com/openhab/openhab-core/files/3651972/jetty.log)

### PR DESCRIPTION
**Pull request by falmanna**
fixes #1043

### CODE REVIEW

**Comment by cweitkamp** [comment]
Thanks. Can you please [sign-off](https://www.openhab.org/docs/developer/contributing.html#sign-your-work) your work?

It would be nice to have some [unit tests](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.io.rest.sse/src/test/java/org/eclipse/smarthome/io/rest/sse/internal/util/SseUtilTest.java) for the new pattern to cover at least all available [core events](https://www.openhab.org/docs/developer/utils/events.html#the-core-events). May I ask you to add them?

**Comment by falmanna** [comment]
I signed off the work and added some tests for the single entity filter.

**Comment by cweitkamp** [comment]
Unfortunately the test failed https://travis-ci.org/openhab/openhab-core/jobs/591061769#L2130 - It looks like the dash "-" is not allowed too:

```
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.24 s <<< FAILURE! - in org.eclipse.smarthome.io.rest.sse.internal.util.SseUtilTest
[ERROR] testValidInvalidFilters(org.eclipse.smarthome.io.rest.sse.internal.util.SseUtilTest)  Time elapsed: 0.139 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is <true>
     but: was <false>
	at org.eclipse.smarthome.io.rest.sse.internal.util.SseUtilTest.testValidInvalidFilters(SseUtilTest.java:56)

[ERROR] Failures: 
[ERROR]   SseUtilTest.testValidInvalidFilters:56 
Expected: is <true>
     but: was <false> 
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by falmanna** [comment]
That's strange, why did it pass when I ran it locally in Eclipse?

**Comment by falmanna** [comment]
Okay, apparently I didn't rebuild the bundle before running tests.

Should I add another commit? or modify the previous?

**Pull request merged**
