### PR TITLE
Enable Semantics Integration Tests

### PR DESCRIPTION
**Pull request by wborn**
They seem to work just fine.

### CODE REVIEW

**Comment by cweitkamp** [comment]
I'd say it's okay. But where is Travis?

**Comment by wborn** [comment]
Maybe we need to remove the Travis CI "Service" from the [Apps and Integrations](https://github.com/openhab/openhab-core/settings/installations) settings @kaikreuzer ? We don't have it in openhab2-addons anymore. So it may also be caused by https://github.com/openhab/openhab2-addons/issues/4935.

**Comment by wborn** [comment]
Another difference is that it is missing a [Webhook](https://github.com/openhab/openhab-core/settings/hooks) to https://notify.travis-ci.org

**Comment by maggu2810** [comment]
@kaikreuzer 
It seems all `PR-openHAB-Core` fail because of OOM.
Anything we can do?
Can you activate Travis CI again, so there is at least one CI active?

**Comment by maggu2810** [comment]
Build it myself and it succeeded.

**Pull request merged**
