### PR TITLE
IP addon finder: developer docs

### PR DESCRIPTION
**Pull request by holgerfriedrich**
pure documentation change, describes configuration of IP addon finder in the bindings (addon.xml)

### CODE REVIEW

**Comment by holgerfriedrich** [comment]
@kaikreuzer could you pls include this one as well?

**Comment by holgerfriedrich** [comment]
@mherwege could you have a look please, we need to have the developer docs visible....

**Review by mherwege — APPROVED** [review]
LGTM

**Comment by holgerfriedrich** [comment]
@openhab/core-maintainers Could you please merge this (pure documentation) change?
I want to extend the docs even further for #3943.

**Review by kaikreuzer — APPROVED** [review]
sure, thanks!

**Pull request merged**
