### PR TITLE
Removes the scriptengine from local map after closing and removing a scriptengine

### PR DESCRIPTION
**Pull request by digitaldan**
Signed-off-by: Dan Cunningham <dan@digitaldan.com>

### CODE REVIEW

**Comment by digitaldan** [comment]
After we clean up a script engine and close it, we are not removing it from the local map/cache and the script manager tries to reuse it, which it can not and throws an error.  See my comment on https://github.com/openhab/openhab-core/pull/2681#issuecomment-1019688489

@jpg0 does this seem reasonable?

**Comment by jpg0** [comment]
@digitaldan that's certainly possible - I can see that it's not explicitly removed. The problem that I was fixing is that new ones were getting inserted over the top of old ones (so I guess implicit removal), and I didn't try to change that behaviour, only close the engines properly when requested. Maybe this change has uncovered an existing bug that closed engines were being reused but we didn't realise because they were not actually closed properly? I will certainly take a look - possibly just removal from the map at the end of `removeEngine` is all that is needed.

**Comment by digitaldan** [comment]
Thanks @jpg0 ! indeed https://github.com/openhab/openhab-core/pull/2706/files looks like a better solution.

**Comment by jpg0** [comment]
Oh, I just realised that I has commented on a PR which did exactly the same as mine! Sorry! At least as you suggested it looks better - I purposefully removed from the map first so that any other threads couldn't so easily get at an engine which is in the process of being closed.

**Pull request closed without merging**
