### PR TITLE
[PersistenceExtensions] Fix TimeSeries policy `REPLACE` not being applied

### LINKED ISSUE #4297: TimeSeries policy `REPLACE` is ignored when using `PersistenceExtensions.persist`
It seems the TimeSeries policy `REPLACE` is ignored when using the `persist` overloads with time series support.

## Expected Behavior
The policy should be used.

## Current Behavior
The policy implicitly becomes `ADD`.

## Possible Solution
It seems this method simply persists all states within the provided TimeSeries:

https://github.com/openhab/openhab-core/blob/b932a4df5e6d4f0706afee20b112b710683d16d7/bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/extensions/PersistenceExtensions.java#L212-L227

without first deleting existing states within the period when policy is `REPLACE`.

I guess method `removeAllStatesBetween` could be called first in case of policy being `REPLACE`.

## Steps to Reproduce
See openhab/openhab-js#356

## Context
See details in openhab/openhab-js#356

## Your Environment
* Version used: 4.2RC1

### PR DESCRIPTION
**Pull request by jlaur**
This is a very quick attempt, tested manually, but without test coverage, sorry.

Logic is similar to this:
https://github.com/openhab/openhab-core/blob/b932a4df5e6d4f0706afee20b112b710683d16d7/bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManagerImpl.java#L318-L326

Fixes #4297

### CODE REVIEW

**Comment by jlaur** [comment]
@mherwege - are you available to have a look?

**Review by J-N-K — APPROVED** [review]
LGTM!

**Comment by mherwege** [comment]
LGTM

**Comment by holgerfriedrich** [comment]
@J-N-K @kaikreuzer should we merge this bugfix? Or should we stick to the code freeze?
We have two positive reviews.

**Comment by jimtng** [comment]
Sorry, dyslexic typo erroneously referring to this PR from 4921. Please disregard.

**Pull request merged**
