### PR TITLE
Remove Java 17 build, switch to 21

### PR DESCRIPTION
**Pull request by holgerfriedrich**
To be delayed until 4.3 is released.

### CODE REVIEW

**Comment by holgerfriedrich** [comment]
I have reconfigured branch protection in core to require Java21 only (getting rid of two possibly failing builds).
Until this is merged, 3 build actions are still done.

Can someone pls. help me to change Jenkins core PR build to J21 as well? I don't know how to proceed with this.
@wborn  @kaikreuzer ?

**Comment by wborn** [comment]
> Can someone pls. help me to change Jenkins core PR build to J21 as well?

I switched them all over to use JDK 21.

**Comment by holgerfriedrich** [comment]
Thanks, @wborn. Now Action and Jenkins seem to run fine.

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Pull request merged**
