### PR TITLE
Carve out infrastructure stuff into an openHAB Super POM

### PR DESCRIPTION
**Pull request by pfink**
As discussed [here](https://github.com/openhab/openhab-core/pull/467#issuecomment-455906917), I'd like to carve out some infrastructure stuff into an openHAB-wide Super POM that does not flow with the openHAB release cycle.

I plan to put the Super POM into our openhab/infrastructure repository. This is the current state: https://github.com/pfink/infrastructure/blob/master/pom.xml

WIP, please don't merge yet (Super POM has to be tested and deployed to our repository(s) first). 

Signed-off-by: Patrick Fink <mail@pfink.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
I veto against a parent of the framework POM using a version range (not a fixed version)

**Comment by pfink** [comment]
Why?

**Comment by maggu2810** [comment]
Let's assume there is openhab-super-pom v1.0 and openhab-super-pom v1.1

I build an openHAB Core release, which version of openhab-super-pom is used:

* if the local repository contains already a version that fits the range, the version v1.0
* if the local repository contains already a version that fits the range, the version v1.1

and how does it differ if the repo containing the openhab-super-pom releases is available or not?
At which time lookups are done?

After that the release is done.

I use the released bundled as dependencies for my addons, bindings, transport, whatever.
Which openhab-super-pom parent is used by my artifacts if I depend on openHAB Core bundles that release has been created at the time openhab-super-pom 1.1 has been the latest one?

If there has been a release 1.2 and I am offline, my machine will still use 1.1.
If my local repository is empty and I am online, my machine will use 1.2 and not 1.1.

Parents will always be used and inject stuff into the build of dependent artifacts.
So multiple consumers that uses the openHAB Core release can use different versions of the openhab-super-pom.

This is non deterministic.

A release should never change.

If I checkout a tag, apply a bugfix and do a patch release, the other stuff should remain the same.
This is not true anymore.

**Comment by pfink** [comment]
I think you're missing some major points:

1. The reproducibility of a build should not depend on somebodys local repository. Reproducibility have to be ensured independently from that, I have to be able to fully delete my local repository at any time and still have the same build result afterwards.
1. Not changing anything won't keep builds reproducible (see example below).
1. The Maven Super POM establishs a way that we can **keep** the reproducibility of builds over time. The whole point of the Super POM is to enhance reproducibility and determinism of builds, not to break it. Changes to the Super POM which can possibly affect reproducibility of older builds negatively are strongly forbidden. Only those changes are allowed which either fix broken reproducibility or do not affect the build result at all (e.g. like the project <description>). For other changes, a new major version of the Super POM has to be provided so that past builds are still reproducible.

 I do an example:

Lets say, in 2019, we'll release openHAB 2.5 with openhab-super-pom v1.0.

In 2020, JFrog may decide to end its service for open source projects and we would have to migrate to another artifact repository provider.

In 2021, somebody wants to build openHAB 2.5 again, but this won't work anymore as all respository URLs have changed, JFrog is not available anymore.

In case we have carved out all repository URLs to the Super POM (which is not part of this PR yet), we would now be able to retrospectively fix it and update the repository URLs.

Coming back to your example, the offline user will still have exactly the same build result as the online user, even if he inherits from an earlier version of the Super POM. He does not need the update because he already have all artifacts in his local repository. And he won't be affected negatively by the Super POM update in any way, it won't change anything to the status quo. But the difference now is that the online user who does not have any local repository yet, is also able to easily reproduce the build, so he is affected positively.

**Comment by maggu2810** [comment]
> 1. The reproducibility of a build should not depend on somebodys local repository. Reproducibility have to be ensured independently from that, I have to be able to fully delete my local repository at any time and still have the same build result afterwards.

Can you please my answer at which time new release versions that fullfil the range are looked up?
In commercial environments it is not unusable to use proxy / aggreagtion Maven repositories.
Should I clean the whole proxy all the time just to ensure the most recent parent is used?

> 2. Not changing anything won't keep builds reproducible (see example below).

I don't understand your example at all.
Where do you want to host the super POM at all?
If the provider of that repository takes the repository down, changes the URL, ...
... you have to change the repository section of the reactor using the parent POM that does not reside in that reactor. It does not help if change the repositories in the parent POM as it cannot be found.

Can you please give me a list of settings (that resided in a POM) that you would like to be able to change of a released openHAB Core without an modification of a core artifact?

> Changes to the Super POM which can possibly affect reproducibility of older builds negatively are forbidden.

By convention?
Who controls it?

AFAIK: Changing repositories affects everything because you change also the repositories used by products that just depends on an openHAB artifact. All the repositories used by a dependency are used for the resolution of projects that depend on such an artifact.
Am I wrong?

**Comment by pfink** [comment]
> Where do you want to host the super POM at all? [..] It does not help if change the repositories in the parent POM as it cannot be found.

I also already thought about that issue. My idea was indeed to check if we can upload the Super POM to Maven Central so that there is a "safe fallback". Anyhow, even if it's not in Maven Central, it would be easier to reproduce the build as yu just would have to install a single artifact into your local repository (the Super POM) rather than hundreds of artifacts.

> Should I clean the whole proxy all the time just to ensure the most recent parent is used?

You don't have to do it. The version is looked up within maven-metadata.xml. In proxy repositories there is normally a cache expiration period for this file which you can configure, so it'll automatically fetch updates at some point of time.

> Can you please my answer at which time new release versions that fullfil the range are looked up?

At the time where maven-metadata.xml is downloaded, you can see it in the log.

> By convention?
> Who controls it?

Yes, by convention. The maintainers of the infrastructure repository would control that. Currently, it's me and Kai. For me, it would be totally fine if you join as a maintainer as well.

> Can you please give me a list of settings (that resided in a POM) that you would like to be able to change of a released openHAB Core without an modification of a core artifact?

I wouldn't provide a _final_ list of possible changes as I can't anticipate all future build issues that may will occur on older versions. Here a not final list of changes that would be fine from my point of view without a major version bump:

- Project Metadata (description, organization, license, ...)
- Properties which are not used within the normal Maven Build Lifecycle (e.g. `scm.gitBaseUrl`)
- Versions of Maven Plugins that are not used within a `mvn verify` lifecycle (e.g. maven unleash plugin, unleash-scm-provider-git, maven versions plugin, maven deploy plugin, maven install plugin, ...) in case the newer version does not break any existing process that was used before. Why the `mvn verify` lifecycle? Because that's the part which affects the actual build result, the rest is infrastructure stuff.
- Repository URLs in case they change

As stated already in the comments of the Super POM, I'd not allow a `<dependencies>` section by any means.

> All the repositories used by a dependency are used for the resolution of projects that depend on such an artifact.

I think so, otherwise transitive dependency resolution would not work.

**Comment by pfink** [comment]
@maggu2810: If you have some time, it would be cool if we could revive the discussion, I'd like to continue to work on this topic in case you'd agree to my thoughts. Thanks is advance!

**Comment by maggu2810** [comment]
Sorry! Please excuse my late response.

I still don't see the real need of that parent POM.

> * Project Metadata (description, organization, license, ...)

I don't think that a future change to the organization or license (or similar stuff) will change the license or organization a previous version has been used.
If you e.g. ever change from EPL to APL, this will not affect old versions.
Also, if the organization name changes. A released version has been released by the old organization and not suddenly by the new one.

And IMHO that is also true for the most of the other stuff.
We can't change the history.
If the source code has been placed into the Git repo A as the version x has been released, this is still true if the source code is now placed at repo B.

It is already to complicated that a change in core cannot be applied because it will break addons.
If you migrate e.g. plugin versions to another POM that is used by all other project, this does not relax the situation.

If you want to use the same unleash plugin version in all projects because it is used in your build system, you still can set it in every POM. I don't think you will change that several times.
Other plugin versions should be in control of the specific project.
If e.g. openHAB Core decides to use the next version of the Bnd plugin, I don't see any reason, why every subproject should bump that version.
Perhaps a bump of a plugin needs updated sources. Repo A should not need to wait until all the migration is done in repo B if there is no really a hard requirement.

Perhaps (or let's say "I am pretty sure) I don't see the real pain, why we need that super POM (yet).

**Comment by pfink** [comment]
> Also, if the organization name changes. A released version has been released by the old organization and not suddenly by the new one.

Sorry, I did not correctly answered on your initial question. The Metadata is not something that should be retrospectively changed on an openHAB Core artifact. The list I provided was a "list of changes that would be fine from my point of view without a major version bump" as I wrote, and not the list you asked for. The metadata within the Super POM is just referring to the Super POM itself, but it should still be overriden in all child projects. So yes, the Super POM metadata can change without a major version bump of the Super POM. But no, this will not affect older versions because the child projects override this metadata in their own POM. Please excuse the misunderstanding.

> If the source code has been placed into the Git repo A as the version x has been released, this is still true if the source code is now placed at repo B.

I think here you misunderstand something. This version range is not affecting some existing release that is already uploaded to nexus. Released artifacts will and should stay the same and won't be changed retrospectively. The version range makes life easier for people that want to make a **new** build on an older code base (e.g. on a tag of a release version because they use this release). And the new build is released at the time the build is done and should then also reflect the correct Git repository at build time.

> It is already to complicated that a change in core cannot be applied because it will break addons.

I don't see the point. Which changes will a Super POM prevent? If you do a breaking change, you just increase the major version and you're done - when you change the major version, you'll have exactly the same effort like you'd have with a fixed version that you initally wanted to have - before you doubted the Super POM as a whole.

> I don't think you will change that several times.

I think I've already changed it at least 3 times in more than 4 places and the next version bump is already planned... And  I think I don't have to accept increased maintenance effort and unnecessary duplicates just because other maintainers have no pain. No pain is no argument for not improving something now that we may need anyway later on as you admit yourself when you end you sentence with _(yet)_.

> If e.g. openHAB Core decides to use the next version of the Bnd plugin, I don't see any reason, why every subproject should bump that version.

This example has nothing to do with my suggestion, As stated, the Super POM should not contain plugins that are used within the normal build lifecycle. It's an organization-wide POM that sets infrastructure standards, not architecture standards.

**Comment by maggu2810** [comment]
> Sorry, I did not correctly answer on your initial question. The Metadata is not something that should be retrospectively changed on an openHAB Core artifact. The list I provided was a "list of changes that would be fine from my point of view without a major version bump" as I wrote, and not the list you asked for.

Can you provide me the requested list?
Can you point me to the super POM that you would like to use?

> The metadata within the Super POM is just referring to the Super POM itself, but it should still be overriden in all child projects.

What's the use case of the metadata in the super POM, if it should be overriden in all child projects?
So, the metadata is for the super POM only (also the super POM needs an organization, a license, ...) but you agree that if the metadata should be overwritten by all childs the metadata itself is not an argument for the super POM (the "metadata" I don't say here that there is no other reason -- just let me answer step by step).

> So yes, the Super POM metadata can change without a major version bump of the Super POM. But no, this will not affect older versions because the child projects override this metadata in their own POM. Please excuse the misunderstanding.

Sure, all overwritten stuff does not change. I think about to non overwritten stuff (I repeat myself: for me the data that needs to be overwritten by all children does not bring the need for a parent POM).

> > If the source code has been placed into the Git repo A as the version x has been released, this is still true if the source code is now placed at repo B.
> 
> I think here you misunderstand something. This version range is not affecting some existing release that is already uploaded to nexus. Released artifacts will and should stay the same and won't be changed retrospectively. The version range makes life easier for people that want to make a **new** build on an older code base (e.g. on a tag of a release version because they use this release). And the new build is released at the time the build is done and should then also reflect the correct Git repository at build time.

Hm, are you sure that it does not change anything?
* Let's assume a third party product is using openHAB 2.5.
* The company develops its own proprietary addons.
* To use all dependencies and the whole setup that is declared by openHAB 2.5 the addons of the company use the addon's bundles POM v2.5 as parent (as it is done by all addon bundles of openhab2-addons). This is `org.openhab.addons.bundles:org.openhab.addons.reactor.bundles:2.5`
* All fine, the POM (in this case `org.openhab.addons.bundles:org.openhab.addons.reactor.bundles:2.5`)  is released and releases does not change.
* The POM ``org.openhab.addons.bundles:org.openhab.addons.reactor.bundles:2.5` (to be more correct one of its parent) is using the super POM in a range of [1,2) as parent.
* Current super POM is 1.2.
* Now you release super POM 1.3 and this super POM will at some time be found by Maven and placed into the build machines local Maven repo.
* A third party addon has a bug and a bugfix is applied.
* A new version of the third party addon is build.
* Nothing has been changed, only a simple line in the code.
* Which version of the super POM will be used now?
* Is still 1.2 be used as previously or is now 1.3 be used because it fits still in the range [1,2).
* If 1.3 is used now and not 1.2 it is IMHO not what is expected for the addons developer.
* Why is metadata or other stuff you define in the super POM be changed if I still use a released version as parent? I would expect nothing change as long as I don't change the parent from one released version to another.

> > It is already to complicated that a change in core cannot be applied because it will break addons.
> 
> I don't see the point. Which changes will a Super POM prevent? If you do a breaking change, you just increase the major version and you're done - when you change the major version, you'll have exactly the same effort like you'd have with a fixed version that you initally wanted to have - before you doubted the Super POM as a whole.

Hm, perhaps my understanding of your "Super POM" is wrong.
I assume it will be better if you show me the "Super POM" we are talking about.
Let's assume a company is using openHAB Core as framework and would like to build its own versions.
I think this is no unusual thing as some fixes will be perhaps necessary for their products but not be backported upstream yet.
All works, the build machines of that company are configured and works.
Now the Super POM changes the version of some Maven plugin that affects the build (e.g. the company is using the unleash plugin, too -- I don't know) and releases a new version that still fits to the range.
The build of the company is broken after a backport just because the updated plugin affects the build result in a way that the build machine setup needs to be changed, too.
But that should not be possible as long as nothing has been changed.
(please respect also my reply to the next paragraph)

> > If e.g. openHAB Core decides to use the next version of the Bnd plugin, I don't see any reason, why every subproject should bump that version.
> 
> This example has nothing to do with this PR. As stated, the Super POM should not contain plugins that are used within the normal build lifecycle. It's an organization-wide POM that sets infrastructure standards, not architecture standards.

Next misunderstanding from my side.
Okay, no plugin that affect a build is defined in the Super POM. Fine.
Then I still would like to know what is part of the Super POM.
If it is about infrastructure can't this be configured in Maven's `settings.xml` used by the infrastructure e.g. Jenkins?

> > If you want to use the same unleash plugin version in all projects because it is used in your build system, you still can set it in every POM. I don't think you will change that several times.
> > [..]
> > Perhaps (or let's say "I am pretty sure) I don't see the real pain, why we need that super POM (yet).
> 
> I think I've already changed it at least 3 times in more than 4 places and the next version bump is already planned... And I think I don't have to accept increased maintenance effort and unnecessary duplicates just because other maintainers have no pain. No pain is no argument for not improving something now that we may need anyway later on as you admit yourself when you end you sentence with _(yet)_. Which sense does it make to revoke this PR and duplicate the change on every place where it is needed? It's like saying "Yes, copy this method to 5 classes, I have no pain for a super class (or utility class) currently!"

Do you know if no other one relies on the specific unleash plugin version?
I don't use it, but perhaps other companies build system is using it.
For this special case wouldn't it make more sense to use an openHAB infrastructure profile provided by a `settings.xml`. Why should infrastructure specific stuff be published to a Maven repository and referenced by project artifacts?
And also here: Let's have a look at the "Super POM".

> Sorry, this really sounds like just discussing against something on principle instead of working together. If I have to do such a discussion for every PR now, our next automated release will be in September.

Sorry, but IMHO this is not fair, too.
I don't tell you that you don't get my point and just want to force the usage of a Super POM.
I invested a lot of time in Eclipse SmartHome and now in openHAB Core and I am pretty sure that I try to "work together".
Why do you blame me just because I don't see the need of that Super POM?
Should a maintainer accept PRs just because he trust that the person that provides the PR. Regardless what he thinks about that change?
Should I press the merge button just to end that long discussion?
Perhaps my understanding of the maintainer job is wrong.

**Comment by maggu2810** [comment]
> our next automated release will be in September.

While reading [the latest version of the Super POM](https://github.com/pfink/infrastructure/blob/b2dc965/pom.xml) (following the link in your first post) I don't understand why that Super POM blocks or unblocks the automated release.

Can you please elaborate a little bit why an automated build requires that Super POM.

Would this one help you:
https://github.com/openhab/openhab-core/compare/master...maggu2810:build-infra?expand=1

**Comment by pfink** [comment]
First, sorry for my late response. 

> Why do you blame me just because I don't see the need of that Super POM?
> Should a maintainer accept PRs just because he trust that the person that provides the PR. Regardless what he thinks about that change?

Please read my statement accurately, I don't blame you. I stated that the way this discussion was going _sounds like_ that you are just desperetely searching for arguments just not to give up your initial position instead of working collaboratively. Why did I get this impression? First we are discussing just about the version range, a very little topic, so I stopped my work on the release process because I think this is not the most important part and I think we can clarify this fast. More then 2 months later, after the version range part is more or less clarified, you are suddenly questioning the Super POM as a whole. So I ask myself, why do we discuss 2 months about a more or less unimportant part of the PR when you're questioning the need of it as a whole? Also, I have the impression that in some points this discussion is going in circles and I have to repeat points that I already made. E.g. it was initially stated of in the PR that **infrastructure stuff** should be carved out into the Super POM and it was also already stated before that it should not influence the normal build lifecycle. And now, you show yourself extremely surprised about the statement that the Super POM is about infrastructure stuff and not architecture stuff... Finally, the last statement you made "no pain for a Super POM" really frustrated me because as I said, it's no argument in my eyes - I'm also maintainer and I would not make this PR if there would be no pain. Your view is quite limited to the openhab-core repository, but I'm maintaining the openHAB release process for overall 7 repositories, openhab-core is just one of them. The goal of this Super POM is to make builds better reproducible and to make the maintenance of the release process - which goes over 7 repositories - easier. Of course, as a maintainer, it's your right to put things on question and ask more about what this is all about. You don't have to and you should not trust me blind and merge everything I do. But it also won't work out if you just do the discussion to win it and you're only looking for arguments for not merging it. I don't accuse you that you're doing so - I just shared my personal impression and my frustration and it's on you to review yourself and check if I'm (at least partly) right. If not, I was just wrong on this and that's also fine.

I'm sorry if my statement felt for you like an accusion, it was just expressing my frustration and you may understand that it makes me a little bit desperate to think of that I have to do such extensive discussions for 7 repositories with different maintainers for changes that only affect infrastructure parts and not the code or build process of the repositories itself. Anyhow, my frustration is not your fault and I should not burden others with it, so let's continue the discussion on the content.

> Can you provide me the requested list?

It's the list I provided, just without metadata. As I said, it may does not cover everything, I cannot anticipate all future use cases. The limitations I stated do apply, of course.

> Can you point me to the super POM that you would like to use?

It's in this PR. Repository URLs are still missing, I was waiting first how this discussion goes before I continued the work.

> Hm, are you sure that it does not change anything?[..] The company develops its own proprietary addons.

As you said, the company develops it's proprietary add-ons later on, so it's not part of the openHAB release. At the time those add-ons are developed, of course the latest infrastructure from the latest POM should be used. Here comes the example with repository locations into play again: If the repository URLs changed, of course this company would not want that outdated repository URLs are still be used because the build would not work with them.

My argument was: Existing releases are not changed. On future releases, add-ons or other stuff (even if they are made for older releases), of course it'll have an effect, and that's by intention - because these effects should **keep** the build working (and NOT the opposite). And again we're going in circles, I already made this argument multiple times, e.g. here: https://github.com/openhab/openhab-core/pull/555#issuecomment-466676652

> Now the Super POM changes the version of some Maven plugin that affects the build (e.g. the company is using the unleash plugin, too -- I don't know) and releases a new version that still fits to the range. The build of the company is broken after a backport just because the updated plugin affects the build result in a way that the build machine setup needs to be changed, too.

And again, we're going in circles. I already answered this:

> And if you now try to make other example changes where reproducibility is affected negatively, I can just answer, those are just not allowed. You're not allowed to do changes to the Super POM which do affect reproducibility negatively, so this is a question of good maintenance. In my expectation, the Super POM won't and shouldn't be changed very often, it's really a last resort to (retrospectively) fix heavy build issues and not a playground for daily changes to the build process.

To say it in other words: Changes to the minor version of the Super POM should only be made if they are meant to retrospectively fix issues on the build or release process. If there is a risk that you break more than you fix, a major version bump has to be done and then older versions are not affected.

> If it is about infrastructure can't this be configured in Maven's settings.xml used by the infrastructure e.g. Jenkins?

Of course, it could. But this would not be the better way because the settings.xml is not versioned together with our repositories. Somebody that wants to reuse our settings.xml (this means: reuse our release process) would have a hard time to find out which version of it fits together with which versions of openHAB.

> Can you please elaborate a little bit why an automated build requires that Super POM.

It's not required. It's just better and makes things easier. I could continue to make PRs for multiple repositories that I would have to reverse in case this one is merged - I didn't because I thought this does not make any sense. At this time, I did not think of to continue first with a settings.xml until the discussion is done. Thanks for bringing me on this idea :)

> Would this one help you

No, this would not help as it's just affecting the openhab-core repository. The Super POM is meant as a parent POM for all openHAB Maven projects.

**Comment by maggu2810** [comment]
> I stated that the way this discussion was going _sounds like_ that you are just desperetely searching for arguments just not to give up your initial position instead of working collaboratively.

I don't care about my initial position.
If I am convinced that it is a good idea to use that SuperPOM mechanism (regardless of fixed version or version range) I will agree.
But I am still not convinced that it is a good idea.

> It's like saying "Yes, copy this method to 5 classes, I have no pain for a super class (or utility class) currently!"

It depends.
If we transfer what I understand that you want to do from POM to classes:

* All our classes will use a super class "OpenHABObject".
* The class "openHABObject" will be provided by "openHAB infrastructure" repository
* We do not depend on a fixed version of "OpenHABObject" but use version ranges

We could argue that this is similar to what we are doing in all our OSGi bundles as you can change a package by another version as long as it fits to the imported version range.

But such a change (the used runtime version) is done by intention.

There will be no other version choosen at compile time just because you released a bugfix of "OpenHABObject".

A version is that and that one will be used all the time as long as another version will be set.

No stuff gets magically injected.

> First we are discussing just about the version range
> More then 2 months later, after the version range part is more or less clarified, you are suddenly questioning the Super POM as a whole.

While arguing about the version ranges I never said that I like the idea of the Super POM at all.
Version ranges for the Super POM is IMHO a no go with respect to the arguments I given in the post before.
The Super POM itself that does not reside in the repository at all is something I am really not happy about and I (as an openHAB Core guy) don't see any reason that makes it necessary.

> So I ask myself, why do we discuss 2 months about a more or less unimportant part of the PR when you're questioning the need of it as a whole?

Just a comment about the timespan:
The discussion itself is about three months old, but we don't discuss all that time.
It has been my fault that I did not reply to that topic about a month.
Please excuse me.

> Also, I have the impression that in some points this discussion is going in circles and I have to repeat points that I already made.

Me too.

> it was initially stated of in the PR that **infrastructure stuff** should be carved out into the Super POM and it was also already stated before that it should not influence the normal build lifecycle.

> Is this fair, if I have to do more work just because you have no pain? Your view is quite limited to the openhab-core repository, but I'm maintaining the openHAB release process for overall 7 repositories, openhab-core is just one of them. The goal of this Super POM is to make builds better reproducible and to make the maintenance of the release process - which goes over 7 repositories - easier.

openHAB Core is just one of them, you are right.
We used ESH in our commercial products.
We agreed on the migration from ESH to openHAB Core that we keep it usable as a framework.
Otherwise it would not make sense for to migrate at all.
We maintain our own releases and version number of openHAB Core as we need to maintain also old releases with backporting bugfixes etc.
The version range part is IMHO a no-go.
I don't want to need to trust the openHAB infrastructure maintainer that no non-infrastructure stuff is added to the Super POM without a major version change, I would point (if used at all) a very specific and known and never be changed anymore Super POM.

> > Can you point me to the super POM that you would like to use?
> 
> It's in this PR. Repository URLs are still missing, I was waiting first how this discussion goes before I continued the work.

The Super POM should not contain repository URLs.
The repositories openHAB Core is using should be defined in openHAB Core POM files.

> > Hm, are you sure that it does not change anything?[..] The company develops its own proprietary addons.

> As you said, the company develops it's proprietary add-ons later on, so it's not part of the openHAB release. At the time those add-ons are developed, of course the latest infrastructure from the latest POM should be used. Here comes the example with repository locations into play again: If the repository URLs changed, of course this company would not want that outdated repository URLs are still be used because the build would not work with them.

You already told me you would like to upload the infrastructure POM to Maven Central.
That's the only way that it is used at all (without require to use a special settings.xml on all machines) without building it on the local machine.
Assume an empty local maven repository.
A developer check out openHAB Core and type "mvn clean install".
If the repository URLs are not part of openHAB Core the only repository the parent will be looked up will be Maven Central.

> My argument was: Existing releases are not changed. On future releases, add-ons or other stuff (even if they are made for older releases), of course it'll have an effect, and that's by intention - because these effects should **keep** the build working (and NOT the opposite).

It should keep your build working.
I assume if you break other ones build you don't care (e.g. because other ones build infrastructure rely on not changing build infrastructure things like specific maven plugin versions).

> And again, we're going in circles. I already answered this:
> 
> > And if you now try to make other example changes where reproducibility is affected negatively, I can just answer, those are just not allowed. You're not allowed to do changes to the [minor version of the] Super POM which do affect reproducibility negatively, so this is a question of good maintenance. In my expectation, the Super POM won't and shouldn't be changed very often, it's really a last resort to (retrospectively) fix heavy build issues and not a playground for daily changes to the build process.

I get your point, but you argue here with "good maintenance" and "you're not allowed".
This will work for a period of time.
But you open a door. It is possible to break if no good mainenance is used.
The door should not be opened!
Perhaps you know it and will do your job.
But what if you retire and another one is doing it?
What if he published a new version using the an higher minor and the same major version?
In the history we used "better save then sorry" multiple times.
So, don't open that door and don't rely that no mistake is done in future.





One thing that comes in my mind the last days.
If you argue that the super POM contains only stuff for your build system / infrastructure, then all settings done in the super POM should be added to a profile that is activated on your infrastructure and should not contain any settings that are not part of that profile.
I still think "better save then sorry" and not open the backdoor is more safe.

**Comment by pfink** [comment]
> If I am convinced that it is a good idea to use that SuperPOM mechanism (regardless of fixed version or version range) I will agree. But I am still not convinced that it is a good idea.

Anyhow, you don't provide any single valuable argument against a Super POM with a fixed version yet. This is not acceptable. The decision should be based on arguments and facts, not on your good-will.

> The repositories openHAB Core is using should be defined in openHAB Core POM files.

Same here: Please justify your opinion. Thanks.

> You already told me you would like to upload the infrastructure POM to Maven Central.
That's the only way that it is used at all (without require to use a special settings.xml on all machines) without building it on the local machine.
Assume an empty local maven repository.
A developer check out openHAB Core and type "mvn clean install".
If the repository URLs are not part of openHAB Core the only repository the parent will be looked up will be Maven Central.

What's your whole point here? I see no argument against my proposal in your paragraph.

> No stuff gets magically injected.

The discussion thread (and therefore also the example) you were responding to here was about the need of the Super POM at all and not for the need of the version range. So please don't mix things up.

> I assume if you break other ones build you don't care.

If I wouldn't care about other ones builds, I would have given up this discussion long ago. As you said, I could put everything in the settings.xml and don't care that others can easily redo our releases on older versions. The whole sense of the Super POM is too make our release process easily reproducible for others, especially for forks here at GitHub.

> (e.g. because other ones build infrastructure rely on not changing build infrastructure things like specific maven plugin versions)

Given the limitations I made, I think this is not possible. If you're convinced of the opposite, please make an example.

> I don't want to need to trust the openHAB infrastructure maintainer that no non-infrastructure stuff is added to the Super POM

That's why I offered you to share the maintenance.

> But what if you retire and another one is doing it?
> What if he published a new version using the an higher minor and the same major version?
> In the history we used "better save then sorry" multiple times.
> So, don't open that door and don't rely that no mistake is done in future.

First, this very unlikely. There are very hard limitations that I'll also document for future maintainers. And here a good thing: Even if this very unlikely case would became reality, you can just easily fix it by reversing the breaking change within the infrastructure repository and plead on the rules that I/we worked out here which ensure that no such thing will happen.

> If you argue that the super POM contains only stuff for your build system / infrastructure, then all settings done in the super POM should be added to a profile that is activated on your infrastructure and should not contain any settings that are not part of that profile.

I don't argue that I want to do stuff for "my infrastructure". I want to make our release process centrally versioned and easily reusable for others. I don't like your idea as it'll make the command for others to reproduce our release longer. But if it's the only way you would accept this PR, I'd also accept this suggestion as a compromise (given the assumption that it will work, but I think it should).

**Comment by maggu2810** [comment]
Can you continue with your PR using a fixed versioned Super POM?
If the PR is finally reviewed the last step should be to create a release of the Super POM, so we do not rely on a snapshot parent and downstream consumers can create its own release (so not rely on a moving target / parent).

**Comment by pfink** [comment]
> Can you continue with your PR using a fixed versioned Super POM?

Yes, but this does not mean I agree to stay with a fixed version. And what about the repository URLs now?

> If the PR is finally reviewed the last step should be to create a release of the Super POM

Sure, there has to be a release before this PR gets merged.

**Comment by kaikreuzer** [comment]
Super POM is now available in Maven Central: http://repo1.maven.org/maven2/org/openhab/openhab-super-pom/1.0.0/

**Pull request merged**
