### PR TITLE
Osgiify of dagger library

### PR DESCRIPTION
**Pull request by Hilbrand**
Depends on https://github.com/openhab/openhab-osgiify/pull/11

### CODE REVIEW

**Comment by cweitkamp** [comment]
openhab/openhab-osgiify#11 has been merged. Do we now have to merge this PR too?

**Comment by kaikreuzer** [comment]
No, because the build has failed, see the discussion on the issue.

**Comment by J-N-K** [comment]
I‘ll fix that this evening.

**Comment by Hilbrand** [comment]
I also want to test this, but am really short on time currently. Because for the demo app I had to add an extra option to the runconfiguration to make it work, and it maybe the wrapping of dagger needs additional configuration. For now, with the osgiif-ed version being available, it should be possible to get the Eclipse demo running with some additional settings, while using the standard dagger in a deployed instance when this pr is not yet merged.
See https://github.com/openhab/openhab-distro/pull/1010

**Pull request merged**
