### PR TITLE
[addon] Fix localisation of suggested Add-ons

### LINKED ISSUE #2204: [persistence] Persistence in OH 3 creates a new table for every new item, even if it is not to be persisted
openHAB 3.0.1.

I have defined that only items that are members of certain groups are to be persisted:

```
Items {
       Persist* : strategy = everyChange, restoreOnStartup
       HM* : strategy = every15Minutes, everyChange, restoreOnStartup
       CO2 : strategy = restoreOnStartup, every15Minutes, everyChange
       WatchDog* : strategy = restoreOnStartup, everyHour, everyChange
}
```

This still works in OH 3, but in contrast to OH 2.5, it still creates (empty) tables for ALL new items, even if they are not a member of those groups.

It should only create tables for items, that are defined to be persisted, like in OH 2.5.

### PR DESCRIPTION
**Pull request by andrewfg**
Fixes [#2204](https://github.com/openhab/openhab-webui/issues/2204)

Since time is of the essence, I am opening this PR now for code review. I will create and test a full OH build tomorrow.

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

### CODE REVIEW

**Comment by mherwege** [comment]
I think this should do.
LGTM

**Review by kaikreuzer — APPROVED** [review]
thanks

**Comment by andrewfg** [comment]
> I think this should do.

I tested it today, and unfortunately it does not work!

@kaikreuzer you should probably revert this merge. I am working on finding a working solution today.

**Comment by kaikreuzer** [comment]
Reverted.

**Pull request merged**
