### PR TITLE
[voice] fix try all interpreters

### PR DESCRIPTION
**Pull request by GiviMAD**
Signed-off-by: Miguel Álvarez <miguelwork92@gmail.com>

This revert a change in the behavior introduced in https://github.com/openhab/openhab-core/pull/2976.

### CODE REVIEW

**Comment by GiviMAD** [comment]
Pinning @lolodomo

**Comment by GiviMAD** [comment]
@wborn, Is this ok?

**Comment by wborn** [comment]
Yes I think it's OK. :+1: Maybe it also possible to add some unit tests coverage to prevent it from breaking again? :slightly_smiling_face:

**Comment by GiviMAD** [comment]
> Yes I think it's OK. 👍 Maybe it also possible to add some unit test coverage to prevent it from breaking again? 🙂

Makes a lot of sense, working on it.

**Review by J-N-K — APPROVED** [review]

**Review by wborn — APPROVED** [review]
Thank you!

**Pull request merged**
