### PR TITLE
Fix dynamic options in UI

### LINKED ISSUE #1040: Dynamic state description broken in snapshot 1693
Dynamic state description is no more working, empty list are rendered by UI.
Default widget which should be a selection is no more working too, text widget is used.
This is probably a consequence of this recently merged PR:
https://github.com/openhab/openhab-core/pull/1010

The problem was introduced aftter snapshot 1678.
Coming back to snapshot 1678 until it is fixed.

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #1040

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@cweitkamp : can you please review and check that your change has no other impact.
This is not clear for me if we are handling null or empty list for options.

**Comment by cweitkamp** [comment]
@lolodomo Here you are: https://github.com/lolodomo/openhab-core/pull/2

**Comment by lolodomo** [comment]
I Mercee your tests but did not test them.

**Comment by lolodomo** [comment]
Yes, that's true. But I don't know in practice how it could occur.

**Pull request merged**
