### PR TITLE
changed start level of transformation services

### PR DESCRIPTION
**Pull request by kaikreuzer**
fixes https://github.com/openhab/openhab-distro/issues/333

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@maggu2810 This does not seem to fix openhab/openhab-distro#333.
I assume that it is because it includes a nested feature and not the bundles themselves (in which case it [should work](https://issues.apache.org/jira/browse/KARAF-576).

Would you be ok if I moved the start-level info to the ESH features instead? Or would you have any alternative suggestion on how to solve openhab/openhab-distro#333?

**Comment by maggu2810** [comment]
It seems openhab/openhab-distro#333 has already been updated that the error are not thrown any more on startup. So the start level seems not to be real problem for me. But I haven't had a deeper look at the problem at all, just read the last one / two comments.

About changing start level in ESH, I was of the opinion that we already agreed that we don't workaround stuff by forcing the usae special start levels order. All should work using the same start level (and there is already stuff left that does not work).

**Comment by kaikreuzer** [comment]
> that the error are not thrown any more on startup

Which I cannot explain, because the bundle startup-level is still at 80 as before. Maybe it is just luck due to the bundle installation order, so it might be back at any time.

> that we don't workaround stuff by forcing the usae special start levels order.

In theory right, yes, but we also already have [exceptions to this rule](https://github.com/eclipse/smarthome/blob/master/features/karaf/src/main/feature/feature.xml#L21). And we are aware of many problems, that would require something like a "system ready" information (https://github.com/eclipse/smarthome/issues/1896).

So as long as https://github.com/eclipse/smarthome/issues/1896 is not solved, I simply couldn't think of any different solution than changing the start-level. And as I knew that you wouldn't like it, I asked you if you had any better ideas :-)

**Comment by maggu2810** [comment]
> In theory right, yes, but we also already have exceptions to this rule.

Then we should reduce / eliminate that exceptions instead of adding new ones.

> I asked you if you had any better ideas

Haven't had any, because I don't know anything about the problem.
But if you think that this could be resolved by the "system ready" information, then we should try to move forward.

**Comment by maggu2810** [comment]
@kaikreuzer some questions:
* At which places a transformation service could be used (item states, scripts, ...)?
* If a transformation service is not available what is the expected behaviour?
* If a transformation service is added later, what is the expected behaviour?

For item states, shouldn't we set an undef state (at least it is undefined because the transformation result is not known)?
For item states, if a transformation service is added / removed, shouldn't we iterate over all items and update their state (if possible at all -- we could e.g. send the refresh command to such items).

**Comment by kaikreuzer** [comment]
> But if you think that this could be resolved by the "system ready" information, then we should try to move that discussion forward.

Agreed. Nonetheless, I would prefer to accept a short-term fix to solve this issue asap (as it is a regression, since in pre-karaf, this was always solved through start-levels already).

> At which places a transformation service could be used (item states, scripts, ...)?

Used in scripts, rules, labels/formatting in sitemaps and potentially by any other Java code.

> If a transformation service is not available what is the expected behaviour?

This is up to the caller of the service.

> If a transformation service is added later, what is the expected behaviour?

That it is available to callers from that moment on.

> For item states, shouldn't we set an undef state

No, because it is NOT applied to item states, but only used for representing the state to the user.

**Comment by watou** [comment]
> No, because it is NOT applied to item states, but only used for representing the state to the user.

Several 1.x bindings use transformations in the process of determining item states, but it should remain up to the bindings how to handle failures to transform, with the services remaining ignorant of how and where they are used.

**Comment by maggu2810** [comment]
I see the point for openHAB and I agree that openHAB needs a short term fix.
Before we introduced Karaf features in ESH there has been no start-levels defined in the ESH repo at all. The start levels has been defined in the openHAB startup configuration (correct me if I am wrong).
So, it is a regression in OH and not in ESH, that has been introduced by the movement to the Karaf and the consuming of the resp. features.

For a short-term fix I will approve the ESH commit and merge it. As I don't see any reason to have stuff in the ESH repo that is not (at least reliable) working stuff in the ESH repo.

Please let's think about the start level. Currently we are using 80 for all but two bundles.
The usage of 75 has been introduced by eclipse/smarthome#1856. I assume that start-levels could already be fixed by using the BundleProcessorVetoManager (would at least be great if this could be done).
As you used 70 for the transformation bundles: Has this choosen by intention or is 75 also okay?
My intention is to keep the number of different start-levels as small as possible (if we need more then one).

**Comment by maggu2810** [comment]
@kaikreuzer One additional point:
If one of the transformation service you decrease the start-level (direct or indirect by another function) calls a public static function of a bundle (e.g. core) that is using lazy loading (activate by first access), could this change the startup order of the bundles, too? So, perhaps some bundles are then also activated earlier then before... Just to think about...

**Comment by kaikreuzer** [comment]
> it is a regression in OH and not in ESH

No, it is a regression in ESH, which happened at the moment when the transformation services were moved out from core.transform into their own bundles - at least this step increased the risk that the services are started later than the rest.

> As you used 70 for the transformation bundles: Has this choosen by intention or is 75 also okay?

75 is ok as well - I mainly chose a different level in order to not imply that there is any similarity between these bundles.

> could this change the startup order of the bundles, too? So, perhaps some bundles are then also activated earlier then before

Valid point. I just did a quick scan and couldn't find any dependencies that have lazy-loading declared - so hopefully we are good.

**Pull request merged**
