### PR TITLE
update Tycho version and avoid warnings during the build

### PR DESCRIPTION
**Pull request by kaikreuzer**
See also https://github.com/eclipse/smarthome/pull/6198 and https://github.com/eclipse/smarthome/pull/6209

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by martinvw** [comment]
That is a very unhappy build... I don't have any principal problems with the change but I don't know whether the build problems are related?

**Comment by kaikreuzer** [comment]
That's indeed weird.
```
[ERROR]   Software being installed: org.openhab.core.karaf 2.4.0.qualifier
[ERROR]   Missing requirement: org.apache.karaf.features.core 4.2.1 requires 'osgi.service; (objectClass=org.osgi.service.cm.ConfigurationAdmin)' but it could not be found
[ERROR]   Cannot satisfy dependency: org.openhab.core.karaf 2.4.0.qualifier depends on: java.package; org.apache.karaf.features 0.0.0
```
@maggu2810 Do you happen to know why this comes up after an Tycho upgrade (from 1.0 to 1.2)? I couldn't really see any related issue in the release notes (neither 1.1 nor 1.2)...

**Comment by maggu2810** [comment]
@kaikreuzer I checked out your tycho12 branch of openhab-core.
If I trigger a build I get this one:

```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.openhab.core 2.4.0.qualifier
[ERROR]   Missing requirement: org.eclipse.smarthome.model.item 0.10.0.201809171332 requires 'osgi.bundle; org.eclipse.xtext.xbase.lib 2.14.0' but it could not be found
[ERROR]   Missing requirement: org.eclipse.smarthome.model.item 0.10.0.201809210646 requires 'osgi.bundle; org.eclipse.xtext.xbase.lib 2.14.0' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.smarthome.model.rule 0.10.0.201809171332 depends on: osgi.bundle; org.eclipse.smarthome.model.item 0.0.0
[ERROR]   Cannot satisfy dependency: org.eclipse.smarthome.model.rule 0.10.0.201809210646 depends on: osgi.bundle; org.eclipse.smarthome.model.item 0.0.0
[ERROR]   Cannot satisfy dependency: org.eclipse.smarthome.model.rule.runtime 0.10.0.201809171332 depends on: osgi.bundle; org.eclipse.smarthome.model.rule 0.0.0
[ERROR]   Cannot satisfy dependency: org.eclipse.smarthome.model.rule.runtime 0.10.0.201809210646 depends on: osgi.bundle; org.eclipse.smarthome.model.rule 0.0.0
[ERROR]   Cannot satisfy dependency: org.openhab.core 2.4.0.qualifier depends on: java.package; org.eclipse.smarthome.model.rule.runtime 0.0.0
```

This looks different...

Have I to build some other stuff first (didn't build any openHAB related stuff except ESH a while now)?

**Comment by kaikreuzer** [comment]
You must rebase that branch on master to have https://github.com/openhab/openhab-core/commit/5d57aa2c00fd118ac54c13ebdb6f218e54e8b9dc included.

**Comment by maggu2810** [comment]
It seems Tycho also checks the requirements for the dependencies.
It does not found anything that provides an implementation for the respective service.
Perhaps it is related to the Require and Provide Capability headers.

The (first) message can be removed by adding such an implementation to the build:
```xml
    <dependency>
      <groupId>org.apache.felix</groupId>
      <artifactId>org.apache.felix.configadmin</artifactId>
      <version>1.9.4</version>
      <scope>provided</scope>
    </dependency>
```

but this will lead to another missing service.

We need to tell Tycho not to check the dependent bundles but stop at the one that is compiled (at least for that project).

It seems it is not a good idea to mix Maven dependencies and p2 dependencies.

Perhaps this bundle can be migrated to a pure Maven one -- or a pure p2 one (packaging)...

**Comment by maggu2810** [comment]
Let try my me something, I have a simple idea -- simple if it is working...

**Comment by maggu2810** [comment]
@kaikreuzer Can you rebase your branch, too? I would like to create a PR to your branch, then you can have a look at.

**Comment by kaikreuzer** [comment]
done

**Comment by martinvw** [comment]
Done, thanks!

**Pull request merged**
