### PR TITLE
Fix javadoc warnings

### PR DESCRIPTION
**Pull request by holgerfriedrich**
This is a follow-up to #3867.

After applying both patches there are still some warnings left.
Not sure how to deal with the following ones:
```
ThingTypeRegistry.java:137: warning: Tag @link: reference not found: ThingType#getChannelType(ChannelUID)
ThingTypeRegistry.java:153: warning: Tag @link: reference not found: ThingType#getChannelType(ChannelUID)
```
References to RuleStatus.DISABLED which were missing with the first commit now are replaced by RuleStatusDetail.DISABLED.
The references to XtextFormattingTokenSerializer which were missing with the first commit now are replaced by org.eclipse.xtext.xtext.XtextFormatter.
The ref to getChannelType should probably be fixed, but I am not sure which function to reference.

There are some other correct refs failing, likely due the way the docs are built in the subdirectories.
Probably we cannot do much for those and the external references:
```
ScriptBusEvent.java:31: warning: Tag @link: reference not found: org.openhab.core.model.script.actions.BusEvent
ScriptThingActions.java:22: warning: Tag @link: reference not found: org.openhab.core.model.script.internal.engine.action.ThingActionService
Configuration.java:29: warning: Tag @link: reference not found: org.openhab.core.thing.Thing
WebSocketAdapter.java:38: warning: Tag @link: reference not found: org.eclipse.jetty.websocket.api.annotations
```

Maybe we should enforce no javadoc warnings in the CI (but then we would need some special handling if we cannot resolve the ones above).

### CODE REVIEW

**Comment by wborn** [comment]
> The references to XtextFormattingTokenSerializer are also no longer working, even searching the web for this does not give any results.

I think it lives on as the `XtextFormatter` but I created https://github.com/eclipse/xtext/pull/2840 to get this confirmed. :slightly_smiling_face:

**Comment by wborn** [comment]
> reference not found: RuleStatus#DISABLED

This seems to have been moved to `org.openhab.core.automation.RuleStatusDetail` in https://github.com/eclipse-archived/smarthome/pull/4468.

**Comment by holgerfriedrich** [comment]
Thanks @wborn for you help on this.
Now it is down to this one from ThingTypeRegistry:
ThingType#getChannelType

```
    /**
     * Returns the channel type for a given channel.
     *
     * <p>
     * <strong>Attention:</strong> If you iterate over multiple channels to find the according channel types, please
     * fetch the thing type first using
     * {@link ThingTypeRegistry#getThingType(ThingTypeUID)} and use
     * {@link ThingType#getChannelType(ChannelUID)} afterwards.
     *
     * @param channel channel
     * @return channel type or null if no channel type was found
     */
    public @Nullable ChannelType getChannelType(Channel channel) {
```

**Comment by wborn** [comment]
> Probably we cannot do much for those and the external references

Maybe just use `{@code ...}`  instead of `{@link ...}` ?

**Comment by holgerfriedrich** [comment]
Now it should be free of warnings (together with #3867).

WDYT @wborn, should we start a discussion about adding javadoc to CI build and enforcing warning free commits? If yes, I would start this in a separate issue.

**Review by wborn — APPROVED** [review]
Thanks for the cleanup!

**Comment by wborn** [comment]
> CI build and enforcing warning free commits

How will this impact build times? They are already take a lot of time.

**Comment by holgerfriedrich** [comment]
You are right, let's keep the response time low for the normal CI builds.

Maybe we could add a new Jenkins job or add a javadoc step to the build job we use for the build status badge:
image
In such a job, all warnings/errors could be displayed like in the SAT statistics.
And it could provide an easy way to access the current javadocs.

**Comment by wborn** [comment]
There's already a JavaDoc build which can be reconfigured and for which we can add a build badge:

`[JavaDoc Build Status](https://ci.openhab.org/view/Documentation/job/openHAB-JavaDoc/)`

[JavaDoc Build Status](https://ci.openhab.org/view/Documentation/job/openHAB-JavaDoc/)

**Comment by holgerfriedrich** [comment]
It is always passing with status success, see the older builds.

We need to set the build status to unstable or failed. I do not know how the job is configured, for pipelines the exit status can be used.
We have to check for "warning:" in the log and set build status to unstable. Same for "error:" and status fail.

**Comment by wborn** [comment]
With #3886 the build will fail on warnings/erros.

**Pull request merged**
