### PR TITLE
[uom] Allow DateTimeFormat for labels of Number:Time items

### PR DESCRIPTION
**Pull request by cweitkamp**
- Allow DateTimeFormat for labels of Number:Time items

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by cpmeister** [comment]
What about duration formats? Can you add support for those as well?

**Comment by cweitkamp** [comment]
Supporting a `Duration` format would be a possible enhancement. But to be honest I am not aware of a nice way to support user-defined `Duration` format patterns. I know that `toString()` method prints a ISO-8601 seconds based representation, such as PT8H6M12.345S. Do you have a hint?

**Comment by cpmeister** [comment]
Found a bit of code on stacktrace that might help:
```
public static String formatDuration(Duration duration) {
    long seconds = duration.getSeconds();
    long absSeconds = Math.abs(seconds);
    String positive = String.format(
        "%d:%02d:%02d",
        absSeconds / 3600,
        (absSeconds % 3600) / 60,
        absSeconds % 60);
    return seconds < 0 ? "-" + positive : positive;
}
```
Unlike jodatime, java's time framework doesn't apparently come with a prebuilt formatter.

**Comment by cweitkamp** [comment]
@cpmeister I do not think an algorithm is the problem. I am looking for a pattern which users can add e.g. to their item labels. Similar to what we can do with other Java types (see https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Formatter.html#syntax).

**Pull request merged**
