### PR TITLE
Improve channel handling in ThingImpl

### PR DESCRIPTION
**Pull request by J-N-K**
Reverts #719 and re-implements #693, therefore completing #731

### CODE REVIEW

**Comment by cweitkamp** [comment]
May I ask you to change the `List` of things in the `BridgeImpl` to a `Map` too?

**Comment by J-N-K** [comment]
Please make sure that the attached PR in openhab-addons is merged immediately after this change, otherwise the build will break.

**Review by cweitkamp — APPROVED** [review]
LGTM. Thanks.

Shall I wait meeting until the discussion in https://github.com/openhab/openhab-addons/pull/14027 will reach a decision?

**Comment by J-N-K** [comment]
Since the discussion is not related to the change I would prefer to see it merged.

**Comment by J-N-K** [comment]
@cweitkamp Can you merge this one? Thanks.

**Pull request merged**
