### PR TITLE
allow the use of an HTTP proxy

### PR DESCRIPTION
**Pull request by blafois**
This allows to use an HTTP proxy by using java Standard properties (http.proxyhost/https.proxyhost & proxyport).
This is extremely useful for debugging the development of new bindings, and also when direct internet connectivity is not available on the network.

Signed-off-by: LAFOIS Benjamin <benjamin.lafois@gmail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@blafois May I ask you to rebase this PR as it currently contains many other commits that are not related to your change?

**Comment by blafois** [comment]
Hello @kaikreuzer  ! Done :-)

**Review by kaikreuzer — APPROVED** [review]
Thanks, that looks much better! 😄 

Code looks good, thanks for the contribution.

**Comment by msveden-123** [comment]
I'm having issues after upgrading to 3.3 and enable proxy. It seems like openHAB Cloud connection make calls to localhost:8080 but localhost is not recognize by proxy server. I have tried to use Dhttp.nonProxyHosts to exclude localhost but it constantly ask proxy server anyway. Is there any issue with using parameter Dhttp.nonProxyHosts?

**Comment by blafois** [comment]
Hello,
How did you configure the proxy ?
The support of nonProxyHosts has not been implemented.
If localhost is not recognized - have you tried replacing it by the address aka 127.0.0.1 ?

**Comment by msveden-123** [comment]
I have added the proxy settings in /etc/default/openhab as EXTRA_JAVA_OPTS.

I don't know from where openHAB Cloud connection get the hostname localhost. Anyway 127.0.0.1 wouldn't help because that request would go to proxy too. Only solution is to either use valid hostname for Cloud connection or implement nonProxyHosts option.

I assume nonProxyHosts would make sense, I would like to be able to exclude internal systems.

**Comment by blafois** [comment]
Can you share the full extra_java_opts parameters ? (host+port) ?

**Comment by msveden-123** [comment]
EXTRA_JAVA_OPTS="-Dlog4j2.formatMsgNoLookups=true -Dhttp.proxySet=true -Dhttp.proxyHost=proxy.domain.com -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxy.domain.com -Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts=localhost|*.domain.com"

**Pull request merged**
