### PR TITLE
Auth pages i18n

### PR DESCRIPTION
**Pull request by ghys**
This implements localized messages for the authorize, change
password and create API token pages using a resource bundle.

Messages in English & French are included.

Signed-off-by: Yannick Schaus <github@schaus.net>

### CODE REVIEW

**Comment by ghys** [comment]
@kaikreuzer after this is approved & merged, thanks in advance to add these properties files in Crowdin as we discussed :)

**Comment by ghys** [comment]
Would appreciate an expedited review of this so it can be inclusion in the release :)
Given that the UI was translated into 15 languages in less 72 hours by the community, it could well happen for these too, and it would add to a good experience.

image

And if the properties files are configured it's relatively harmless to let the translation campaign happen next week for these IMO. If there are e.g. file encoding issues this can be adjusted before merging.

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Comment by kaikreuzer** [comment]
@ghys I have included these files in the crowdin config as discussed!

**Pull request merged**
