### PR TITLE
Update archetype-post-generate.groovy

### PR DESCRIPTION
**Pull request by davidgraeff**
My dream for this file is to be almost empty. Remove features file modification, we have a local file per bundle now.

Signed-off-by: David Graeff <david.graeff@web.de>

### CODE REVIEW

**Comment by davidgraeff** [comment]
It might not be the smartest way to have the archetype for generating bundles for another repo in here. Each time we change something over there, we need to remember to also adapt here.

**Comment by maggu2810** [comment]
> It might not be the smartest way to have the archetype for generating bundles for another repo in here. 

Shouldn't that archetype be valid for every openHAB bundle, also new openHAB Core bundles?

**Comment by cweitkamp** [comment]
Similar to #817. Without adding the feature.xml

**Comment by davidgraeff** [comment]
True. This is a duplicate

**Comment by davidgraeff** [comment]
@maggu2810 I don't think that will work in the long run:
* openHAB Core: One project, multiple bundles, one release
* openHAB addons: Multiple independent projects, not necessary to release together

Therefore the directory structure might indeed be a bit different between core and addon repos.

**Comment by maggu2810** [comment]
If the archetype is for "addons" only and cannot be used for "core" then I do not see any reason to maintain it here. Why not moving it to the "addons" repo if it is for addons only?

**Comment by davidgraeff** [comment]
That's what I'm thinking as well. The archetype will still be uploaded to a maven repo and can be used by other openhab2-addons-inofficial repos, but it cannot be used by openhab-core itself.

**Comment by maggu2810** [comment]
See also

---

 https://github.com/openhab/openhab-core/pull/589#issuecomment-467380732

> If we can design the archetype that it works for every bundle perhaps core makes the most sense.

---

https://github.com/openhab/openhab-core/pull/589#issuecomment-477097678

> I would prefer it to be in openhab-core (as it was in ESH in the past) as the skeleton can be seen as a tooling that is closely related to the API that we define in the core. That is, whenever we change something on the APIs and the way we expect add-ons to be developed, it should be done in a single PR against this repo.

---

For me it seems that this archetype is not only about the API anymore but also about the directory layout chosen by @openhab/2-x-add-ons-maintainers for its addons.
@kaikreuzer WDYT? Makes it sense to require PRs to core because the layout of the projects in addons changes?

**Comment by davidgraeff** [comment]
I think there is just still a lot of confusion about each repos purpose. Understandable because it is nowhere written down.

The Eclipse Smarthome repo was more than just a core framework, it was a full solution.
It contained the docu, a demo app, example bundles, "official" extensions and of course the archetype for developing more extensions. That is no more. openHAB-core is just the core bundles.

**Comment by kaikreuzer** [comment]
> If the archetype is for "addons" only and cannot be used for "core" then I do not see any reason to maintain it here. 

There shouldn't be "one archetype". The one that we have is the template how the core framework expects bindings to be implemented and provide a skeleton for it. So yes, for me, this clearly belongs in the core repo as it is valid for ANY binding being implemented (not just the ones in openhab2-addons).

> @kaikreuzer WDYT? Makes it sense to require PRs to core because the layout of the projects in addons changes?

Ideally, there should not be any dependency to a repo layout and we didn't have such a dependency in the past. If someone wants to create a custom binding in their own repo, this should be possible.
If we suggest a common directory layout that should be followed for any add-ons repo, then it is imho ok to also expect this to be followed when using the archetype.

**Comment by davidgraeff** [comment]
So the solution would be to move "archetype-post-generate" to openhab2-addons?

**Pull request closed without merging**
