### PR TITLE
Provide unit hint for system channel type `atmospheric-humidity`

### PR DESCRIPTION
**Pull request by jlaur**
Depends on #4079

### CODE REVIEW

**Review by mherwege — APPROVED** [review]
LGTM

**Review by andrewfg — APPROVED** [review]
LGTM thank you.

**Comment by andrewfg** [comment]
Plus note that this probably won't build until the xsd schema has bee uploaded onto the openhab.org server..

**Comment by jlaur** [comment]
@J-N-K - I don't think rebuild will help until #4079 is merged. 😉

**Comment by kaikreuzer** [comment]
@J-N-K Ok to merge now?

**Review by J-N-K — APPROVED** [review]
LGTM

**Pull request merged**
