### PR TITLE
Also return command line execution result in case of error return code

### LINKED ISSUE #2078: ExecUtil.executeCommandLineAndWaitResponse should return stderr response e.g. for Network binding
ExecUtil.executeCommandLineAndWaitResponse checks the return code of the program and if it is not 0, then the returned text will be discarded.

            if (exitCode == 0) {
                return outputFuture.get();
            } else {
                if (logger.isDebugEnabled()) {
                    logger.debug("exit code '{}', result '{}', errors '{}'", exitCode, outputFuture.get(),
                            errorFuture.get());
                }
                return null;
            }

## Expected Behavior
since stdout and stderr can be written with any exit code, the result of calling an executable should include the exit code, stdout and stderr. Especially when the stderr is read into errorFuture some lines above.

## Current Behavior
See description

## Possible Solution
Create an Class for the Result (How is this problem solved in other applications?)

## Steps to Reproduce (for Bugs)
Install the network binding and use iptools arping. It will call arping with argument --help. The arping does not know the argument and returns with code 2 and the argument list printed to stderr.

## Context
I'm trying to get the Network binding working and discovered this issue with arping. But it may be an issue with other bindings too, which run executables.

## Your Environment
current main & master of openHAB (problem seem to exist since long time OH 2.5.x with network binding.)
Ubuntu 20 on Odroid C2 with iputils arping
Linuxmint on Oracle VB with iputils arping

arping -V returns "arping from iputils s20190709"

### PR DESCRIPTION
**Pull request by kaikreuzer**
Fixes https://github.com/openhab/openhab-core/issues/2033
Fixes #2078 

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Review by Confectrician — APPROVED** [review]
👍

**Comment by lolodomo** [comment]
@kaikreuzer : can you please check that it will not break any existing OH3 binding?

**Comment by kaikreuzer** [comment]
@lolodomo I found 4 uses of the method, all of them should work nicely with that change.

**Comment by lolodomo** [comment]
Thank you.

**Review by wborn — APPROVED** [review]
Thanks!

**Pull request merged**
