### PR TITLE
updated target platform information

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@cdjackson FYI, this will make the zigbee build pass even without removing stuff from the manifest :-)

**Comment by cdjackson** [comment]
Ok, thanks. I took the quick and easy route for now given the annotations aren't used at the moment.  At least it shows the build is working again so the other PR worked :)

**Comment by kaikreuzer** [comment]
> given the annotations aren't used at the moment

Now they are https://github.com/openhab/org.openhab.binding.zigbee/pull/29 :-)

**Comment by cdjackson** [comment]
Thanks :)

**Pull request merged**
