### PR TITLE
add openHAB version and build info to dashboard footer

### PR DESCRIPTION
**Pull request by kaikreuzer**
Closes https://github.com/openhab/openhab-distro/issues/454

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
This PR changes the footer to include version and build no, see:

screen shot 2017-05-15 at 21 38 00

**Comment by VanHogan** [comment]
Yep looks good imo. Thanks!

**Comment by AngelosF** [comment]
I like it also ! 👍

**Comment by AngelosF** [comment]
2.4.0 Milestone Build does not display the build number (e.g. M6) is this intended ?

**Pull request merged**
