### PR TITLE
Keep channel properties in thing updates

### LINKED ISSUE #3610: thing upgrades: missing support to add/change/remove channel properties
I am using channel properties and as part of a change I also need to add some properties as part of a migration. See [#14866 ](https://github.com/openhab/openhab-addons/pull/14866) for details. Changing channel type worked fine for me but this is only a part of the migration. Please add support for this.

### PR DESCRIPTION
**Pull request by J-N-K**
Fixes #3610

### CODE REVIEW

**Comment by lolodomo** [comment]
Thank you @J-N-K .

I have the feeling you could also fix the problem for label/description with that code ?
```
        if (label != null) {
            channelBuilder.withLabel(Objects.requireNonNull(label));
        } else {
            channelBuilder.withLabel(oldChannel.getLabel());
        }

        if (description != null) {
            channelBuilder.withDescription(Objects.requireNonNull(description));
        } else {
            channelBuilder.withDescription(oldChannel.getDescription());
        }
```

**Comment by J-N-K** [comment]
No. That would most probably be wrong, because the new channel would inherit from the old one instead of the channel-type.

**Comment by lolodomo** [comment]
> No. That would most probably be wrong, because the new channel would inherit from the old one instead of the channel-type.

Oh yes, you're right but that is exactly the same thing for properties, we need to find properties from the new channel, not the old one, that is the use case from @alexf2015, he added channel properties.

**Comment by J-N-K** [comment]
We could probably add a new section similar to label that adds new properties.

**Comment by kaikreuzer** [comment]
@alexf2015 You mentioned [here](https://github.com/openhab/openhab-core/issues/3610#issuecomment-1546948150) that you don't think that this PR fixes your issue. Shall it be merged nonetheless or do you expect further changes?

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Pull request merged**
