### PR TITLE
Proposal for some new profiles : Change and update timestamp

### PR DESCRIPTION
**Pull request by clinique**
Would like your comments.

Signed-off-by: Gaël L'hopital <gael@lhopital.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
> The question is if it makes sense to extend items / events in general to carry their last change timestamps?

This has been discussed a couple of times in the past years, but although it sounds easy, it isn't straight forward. An event can be passed on. Should its timestamp be updated in that situation or not? What if you receive an event with a lower timestamp AFTER one with a higher one? Shouldn't the timestamp be the time of the measurement and not the time of arriving in the framework? What timestamp should be put in the datebase for persistence (note that the HistoricItem already has a timestamp).

The best solution to avoid such questions might be to have some "lastUpdated" method on the ItemRegistry and not on events and or items themselves.

**Comment by kaikreuzer** [comment]
But all the above is rather off-topic. Wrt this PR, I think the profile is ok, although it is pretty weird that the original state is not at all considered - it thus feels a bit like a misuse of the profile idea...

**Comment by clinique** [comment]
> ..although it is pretty weird that the original state is not at all considered...

Can you elaborate a bit on this ? I do not get your point. Thks

**Comment by clinique** [comment]
@cweitkamp : now that I'm on it, do you think it would be appropriate to turn expire binding into a profile ?

**Comment by cweitkamp** [comment]
@clinique Hm, from my point of view it will fit. But I do not want to decide that on my own. @openhab/2-x-add-ons-maintainers Wdyt?

**Comment by davidgraeff** [comment]
Actually I had the same thought a while ago. The issue that I'm seeing with it is that there is no way to get an overview of "running" expires. 
I know that this is also true for OH1-like expires, but I guess we can do better this time. Knowing how many expire timers are in the queue helps maintaining the system.

So maybe going with a profile and a `Registry` that keeps track of active expire profiles (that can be accessed by Rest later on)?

**Pull request merged**
