### PR TITLE
[marketplace] avoid collisions with multiple AddonProviders

### PR DESCRIPTION
**Pull request by J-N-K**
The current implementation could result in collision of file-path and failed in determining the installation status if other AddonProviders re-use the marketplace addon handlers.

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by J-N-K** [comment]
This will still not work. Update in progress.

**Comment by J-N-K** [comment]
This is not the most elegant solution (which would be to have a structure like `userdata/marketplace/<addonservice>/<addonid>`. However, this would require a breaking change for all current users, because the addons installed are currently under `userdata/marketplace/<addonid>` and would need to be removed. I now opted for `userdata/marketplace//UIDUtils.encode(<addonservice>:<addonid>)` for non-`marketplace`-addonservices and kept the "old" way for the marketplace.

**Review by hmerk — APPROVED** [review]
LGTM

**Review by cweitkamp — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
