### PR TITLE
[automation] Use UTF-8 to read files

### PR DESCRIPTION
**Pull request by cweitkamp**
- Use UTF-8 to read files

Otherwise I am seeing e.g. such log messages:

```
2020-05-19 14:37:56.639 [INFO ] [ipse.smarthome.model.script.presence] - Trigger fÃ¼r presenceChristophPresent changed from OFF to ON ...
```

Or wrong tags:

```JSON
        "tags": [
            "Anwesenheit",
            "KÃ¼che"
        ],
```
Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by cweitkamp** [comment]
I am using Python combined with the helper libraries.

**Comment by openhab-5iver** [comment]
Are you using unicode strings?

**Comment by cweitkamp** [comment]
```
automation/jsr223/python/personal/presence.py: Python script, UTF-8 Unicode text executable
```

**Comment by openhab-5iver** [comment]
@cweitkamp, I have tested this and I did not see any difference in functionality. Do you have a before/after test to show that this change is doing something?

**Comment by cweitkamp** [comment]
IIRC `InputStreamReader` defaults to system default charset - which might not always be UTF-8. Specifying it does not hurt as we try to keep it aligned throughout the framework.

I learned of [this community post](https://community.openhab.org/t/no-international-characters-unicode-with-jsr223-jython/99567) that OHC is not the real problem but encoding used by current Python / Jython version. For me masking a String via `u"..."` in my rules and saving the files with UTF-8 encoding is a working solution.

**Pull request merged**
