### PR TITLE
Update groovy license headers to 2022

### PR DESCRIPTION
**Pull request by wborn**
Updates the year in a few groovy file headers that were missed in #2671.

### CODE REVIEW

**Review by cweitkamp — COMMENTED** [review]
Thanks.
Do you have an idea why it wasn't picked up by the man command?

https://github.com/openhab/openhab-core/blob/89aae83b64510bd95f934047b069d332055fff80/pom.xml#L449

And add archetype Groovy script to the includes in the POM file?

**Comment by wborn** [comment]
> Do you have an idea why it wasn't picked up by the man command?

It did update the header at the top of the file but not the header used in the groovy code. 
So I've tweaked the code so it will always use the current year.

**Comment by cweitkamp** [comment]
That's an improvement. At best it would use the content from [licenses/epl-2.0/header.txt](https://github.com/openhab/openhab-core/blob/main/licenses/epl-2.0/header.txt) to add the header to generated classes :wink:. Wdyt?

**Comment by wborn** [comment]
It was not too difficult to accomplish that too. :wink:

**Review by cweitkamp — APPROVED** [review]
LGTM. Thanks.

Good to know that next year we have a little less that we don't have to worry about.

**Pull request merged**
