### PR TITLE
removed dashboard bundle as it has moved to https://github.com/openhab/openhab-webui

### PR DESCRIPTION
**Pull request by kaikreuzer**
The dashboard has not been part of ESH and it is rather specific to openHAB and the existing web UIs - so it imho makes sense to maintain it together with the other UI code.

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
Hm, I assume you should think about your openHAB-Core configuration.
It consumes artifacts of openHAB Core that are not part of the reactor anymore from the local repository.
This will hide the usage of no more existing artifacts.

**Comment by kaikreuzer** [comment]
Not exactly sure what you refer to as the "openHAB-Core configuration".
The only artifacts that use the dashboard are the UIs, so there should be no dependency to core anymore anywhere.
And wrt the openhab-core bom, I had merely forgot to remove the reference there, but this is fixed now and all builds are green.

**Comment by davidgraeff** [comment]
@maggu2810 Would be nice to get this merged, do you have any objections?

**Comment by maggu2810** [comment]
> Not exactly sure what you refer to as the "openHAB-Core configuration".

I was talking about the Jenkin's "PR-openHAB-Core" job configuration.
IMO such "no more existing references" should be detected by a CI job.

> @maggu2810 Would be nice to get this merged, do you have any objections?

No, it has been just a matter of time.

**Comment by maggu2810** [comment]
I would like to test a simple idea how we could start mixing PDE and Maven + Bnd in one IDE (demo app).

@kaikreuzer I was not able to build the openhab-webui repo.

```
rathgeb@pc05 ~/bin/pkgs/eclipse/oh2/git $ cd openhab-webui/
rathgeb@pc05 ~/bin/pkgs/eclipse/oh2/git/openhab-webui $ git reset --hard origin/master; git clean -x -d -f
HEAD is now at 8ed8126 Initial commit with UI code base as of 2019-02-17
rathgeb@pc05 ~/bin/pkgs/eclipse/oh2/git/openhab-webui $ mvn clean install
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=512m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1g; support was removed in 8.0
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.openhab.ui:pom:[unknown-version]: Could not find artifact org.openhab:pom-addons2:pom:2.5.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 11
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.openhab.ui:pom:[unknown-version] (/home/rathgeb/bin/pkgs/eclipse/oh2/git/openhab-webui/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.openhab.ui:pom:[unknown-version]: Could not find artifact org.openhab:pom-addons2:pom:2.5.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

**Comment by Hilbrand** [comment]
In openHAB 2-addons There are 2 projects that depend on `org.openhab.ui.dashboard`: `io.neeo` and `io.rest.docs|` because this is removed from core those projects fail to build.

**Comment by davidgraeff** [comment]
> io.rest.docs

Shouldn't that be moved to the webui repo anyway, as it basically renders a webui.

> io.neeo

I proposed this "custom binding pages" concept, that I like to have for MQTT, and that is required for Zwave (if we want to retire habmin at some point). io.neeo seem to require this concept as well, if they out of desperation registered their own page on the dashboard.

Maybe we can introduce that mechanism within the next days and port io.neeo over?

**Comment by kaikreuzer** [comment]
> Shouldn't that be moved to the webui repo anyway, as it basically renders a webui? (The bundle name could also be changed to "ui.rest.docs"?)

I'd agree that this would make sense. Anyone volunteering to create according PRs?

> I proposed this "custom binding pages" concept

Going towards a unified UI, having bindings registering custom UIs (with again custom technologies) on the dashboard does not sound a good way to go. I agree that we need some way to allow binding specific pages in the UI, but ideally, this should be defined within the scope of the discussion to have a new modular UI with a single technology stack backing it.

For the problem at hand, we might remove the Neeo dashboard tile for now and rather add to the docs the link to this custom UI, so that we remove the dependency from openhab2-addons to webui.

**Comment by davidgraeff** [comment]
> For the problem at hand, we might remove the Neeo dashboard tile for now and rather add to the docs the link to this custom UI, so that we remove the dependency from openhab2-addons to webui.

I agree.

> I agree that we need some way to allow binding specific pages in the UI

At the moment some bindings do this, like Neeo (and hue emulatuon), but in an uncoordinated way. I'm not taking about the actual html/ui that is delivered via those endpoints, but where those endpoints are registered. Could we add a binding API to solve this and make Neeo be the first consumer?

**Comment by wborn** [comment]
> Anyone volunteering to create according PRs?

I can create some. Should we also rename the feature to openhab-ui-restdocs?

**Comment by kaikreuzer** [comment]
> Could we add a binding API to solve this and make Neeo be the first consumer?

Yes, I just have no clue what such an API would look like. Imho to make it "pluggable" in the UI, it will pretty much depend on the UI technology and its extension mechanisms, don't you think?

> Should we also rename the feature to openhab-ui-restdocs?

Would make a lot of sense, although it is a breaking change - so we will have to mention it clearly in the release notes.

**Pull request merged**
