### PR TITLE
Fix AbstractScriptFileWatcher missing deletes on Windows

### LINKED ISSUE #3214: AbstractScriptFileWatcher malfunction on Windows
I saw this test failing in a GHA Windows build: https://github.com/wborn/openhab-core/actions/runs/3668681734/jobs/6201979819
Perhaps it is related to the #3168 changes.

```
[ERROR] Tests run: 14, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 18.383 s <<< FAILURE! - in org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest
[ERROR] org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest.testDirectoryRemoved  Time elapsed: 10.701 s  <<< FAILURE!
Wanted but not invoked:
scriptEngineManagerMock.removeEngine(
    "file:/C:/Users/RUNNER~1/AppData/Local/Temp/junit9061750780238590199/dir/script.js"
);
-> at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest.testDirectoryRemoved(AbstractScriptFileWatcherTest.java:428)

However, there were exactly 7 interactions with this mock:
scriptEngineManagerMock.addFactoryChangeListener(
    org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest$1@2d195ee4
);
-> at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcher.<init>(AbstractScriptFileWatcher.java:93)

scriptEngineManagerMock.isSupported("js");
-> at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcher.lambda$5(AbstractScriptFileWatcher.java:247)

scriptEngineManagerMock.createScriptEngine(
    "js",
    "file:/C:/Users/RUNNER~1/AppData/Local/Temp/junit9061750780238590199/dir/script.js"
);
-> at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcher.createAndLoad(AbstractScriptFileWatcher.java:272)

scriptEngineManagerMock.loadScript(
    null,
    java.io.InputStreamReader@3028e50e
);
-> at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcher.createAndLoad(AbstractScriptFileWatcher.java:276)

scriptEngineManagerMock.isSupported("js");
-> at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcher.lambda$5(AbstractScriptFileWatcher.java:247)

scriptEngineManagerMock.createScriptEngine(
    "js",
    "file:/C:/Users/RUNNER~1/AppData/Local/Temp/junit9061750780238590199/dir/script2.js"
);
-> at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcher.createAndLoad(AbstractScriptFileWatcher.java:272)

scriptEngineManagerMock.loadScript(
    null,
    java.io.InputStreamReader@5560bcdf
);
-> at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcher.createAndLoad(AbstractScriptFileWatcher.java:276)


	at org.openhab.core.automation.module.script.rulesupport.loader.AbstractScriptFileWatcherTest.testDirectoryRemoved(AbstractScriptFileWatcherTest.java:428)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutInvocation.proceed(TimeoutInvocation.java:46)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
```

### PR DESCRIPTION
**Pull request by J-N-K**
Fixes #3214 

Regression from #3185 

@wborn It would be great if you could check if it also fixes the issue in GHA builds.

Signed-off-by: Jan N. Klug <github@klug.nrw>

### CODE REVIEW

**Comment by wborn** [comment]
I've cherry-picked it onto my own branch: https://github.com/wborn/openhab-core/actions/runs/3669407664

Recently I had path issues due to spaces and @ symbols in file URLs. These end up to be URL encoded. To then get the right path they first needed to be URL decoded... wouldn't that also be an issue with these URLs?

**Comment by wborn** [comment]
I wrote a small test and see that `f.getScriptFileURL().getFile()` will be encoded too so it is probably not an issue. :slightly_smiling_face:

**Comment by J-N-K** [comment]
I think that since we use URL in both cases now everything will be encoded in the same way.

**Review by wborn — APPROVED** [review]
LGTM! I saw one Windows build succeeded in my fork and the other failed due to some other unstable test.

**Pull request merged**
