### PR TITLE
[IconServlet] New optional parameter anyFormat

### LINKED ISSUE #824: Fall back to other icon format if no icon is present for requested format
On high dpi mobile phones the PNG version of the default icon format looks pixelated (https://github.com/openhab/openhab-android/issues/1337). A user could change his icon format to svg, but then he has to provide all custom icons as svg, too.
I was thinking about this issue and IMO the best solution is to add a parameter to the icon request, like `fallback=true`. If added, the server may return icons in a different format, if no icon for the requested format was found. The client can look at the mime type to know how to parse the icon.
This would also allow us to change the default icon format in the clients to "svg" (for new installations), since it will only break the user experience if the user provides a png icon that overrides one of openHAB's icons.

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #824

If this new parameter is not used by the caller (UI), the behavior is unchanged. So this change will break no existing UI.

When this new parameter is provided and set to true by the caller (UI), the server will search the icon as SVG and PNG formats. If the icon provider is the same in the two cases, it will return the icon with the requested format. In case the 2 icon providers are different for SVG and PNG, the server will return the icon in the format corresponding to the provider with higer priority.

This new parameter allows an UI to select a preferred format for icons without loosing the customized user icons that can be defined  in a different format. Of course, in this case, the UI must handle possible different icon formats returned by the servlet.

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@mueller-ma : please have a look.

**Comment by mueller-ma** [comment]
Sounds good to, but IMO this PR should bump the rest api version.
@maniac103 What do you think about this change?

**Comment by lolodomo** [comment]
Note that it enhance the API without breaking it.
But I understand that a new version will help you to know if the new parameter is available.
Where is set the REST API version ?

**Comment by maniac103** [comment]
The version is defined in RootBean.java.
In general, the idea makes sense to me, as we can introduce an 'automatic' format mode with that (asking for SVG with anyFormat=true). That is assuming the sent mime type matches the sent image, but I'd be surprised if that weren't the case.

**Comment by lolodomo** [comment]
Maybe you can simply use the server version ?

**Comment by maniac103** [comment]
Server version as in ... ? You mean parsing e.g. `2.4.0`? That isn't really possible (or at least highly impractical) due to the huge number of corner cases in that approach.

**Comment by kaikreuzer** [comment]
Increasing the version in the RootBean is perfectly fine - it is meant for the UIs to check whether they can expect a certain feature on the server or not.

**Comment by lolodomo** [comment]
Fine, I am going to increase it. I am just surprised that the version is now only at 2 after so many years.

**Comment by lolodomo** [comment]
I moved the version from 2 to 2.1 but I hesitated with 2.0.1.

**Comment by kaikreuzer** [comment]
No, please increase it to 3, it is meant as an integer without any semver information on it.

**Comment by lolodomo** [comment]
Done, version changed from 2 to 3.

**Comment by lolodomo** [comment]
Can this one be merged ? ;)

**Comment by kaikreuzer** [comment]
Indeed, everything looks sooooo green ;-)

**Pull request merged**
