### PR TITLE
Support hexadecimal version parts explicitly.

### PR DESCRIPTION
**Pull request by YordanDZhelev**
Related to [this open issue](https://github.com/openhab/openhab-core/issues/561)
Signed-off-by: YordanDZhelev <zhelev.yordan@gmail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@YordanDZhelev Did you see @maggu2810's question?

**Comment by maggu2810** [comment]
@YordanDZhelev friendly ping

**Comment by maggu2810** [comment]
@openhab/core-maintainers Can we close this because of "no feedback"?

**Comment by YordanDZhelev** [comment]
@maggu2810 If we don't want to handle the case with FW versions in hexadeciaml format explicitly in the framework it si perfectly OK for me. The only place it is used by now is in one binding, and versions there are padded, so comparing them lexicographically as strings will handle this case. Maybe should close this PR.

**Comment by maggu2810** [comment]
All fine. Thank you for your response.

**Pull request closed without merging**
