### PR TITLE
[profiles] Remove update of timestamp on Change/Update for Item update

### LINKED ISSUE #1537: [profiles] timestamp-update channel profile forces Item state
Example Item, using channel profile **timestamp-update** -

`DateTime testTime "testing" {channel="openweathermap:weather-and-forecast:api:foss:current#condition" [profile="timestamp-update"]}`

Expectation - when that channel updates, the Item state will be updated with a timestamp.  That works well enough -
```
2020-07-01 19:01:56.453 [vent.ItemStateChangedEvent] - testTime changed from 2020-07-01T17:41:27.007+0100 to 2020-07-01T19:01:56.368+0100`
```

But, postUpdating the Item with some other value somehow causes the profile to immediately overwrite the state with a completely new value of "now"
```
2020-07-01 19:35:22.903 [vent.ItemStateChangedEvent] - testTime changed from 2020-07-01T19:01:56.368+0100 to 2011-01-01T10:10:10.000+0000
2020-07-01 19:35:22.934 [vent.ItemStateChangedEvent] - testTime changed from 2011-01-01T10:10:10.000+0000 to 2020-07-01T19:35:22.910+0100

```
Expectation here is that profile does nothing until the next real update of the associated channel.  It should not destroy any manually set value of the Item.  It certainly should not "invent" a new timestamp unrelated to its channel activity.

A nastier consequence; it is reasonable to link more than one channel with timestamp profile to a single Item, say to record the most recent event for any one of a set of sensors.

`DateTime testTime {channel="x:x:x:x" [profile="timestamp-update"], channel="z:z:z:z" [profile="timestamp-update"]}`

This results in disaster, the two profiles enter a loop of warring updates every few milliseconds
```
2020-07-01 19:47:25.926 [.ItemChannelLinkAddedEvent] - Link 'testTime-openweathermap:weather-and-forecast:api:foss:current#condition-id' has been added.
2020-07-01 19:47:25.940 [vent.ItemStateChangedEvent] - testTime changed from 2020-07-01T19:44:47.686+0100 to 2020-07-01T19:47:25.924+0100
2020-07-01 19:47:25.950 [vent.ItemStateChangedEvent] - testTime changed from 2020-07-01T19:47:25.924+0100 to 2020-07-01T19:47:25.934+0100
2020-07-01 19:47:25.957 [vent.ItemStateChangedEvent] - testTime changed from 2020-07-01T19:47:25.934+0100 to 2020-07-01T19:47:25.949+0100
2020-07-01 19:47:25.966 [vent.ItemStateChangedEvent] - testTime changed from 2020-07-01T19:47:25.949+0100 to 2020-07-01T19:47:25.958+0100
2020-07-01 19:47:25.975 [vent.ItemStateChangedEvent] - testTime changed from 2020-07-01T19:47:25.958+0100 to 2020-07-01T19:47:25.965+0100

```

This presumably also affects **timestamp-change**, and potentially other profiles.

### PR DESCRIPTION
**Pull request by cweitkamp**
- Remove update of timestamp on Change/Update for Item update

Fixes #1537

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@cweitkamp Could you please rebase this PR?

**Comment by cweitkamp** [comment]
Yes, I will do that. Do you think this is the right solution? Or should we remove the action in `onStateUpdateFromItem()`? IIRC the idea behind this method is to do some action when the Item state is updated which leads in this case to another refresh of the timestamp and the Item state itself.

**Comment by kaikreuzer** [comment]
I didn't yet read through the full thread of the issue, but did it now.
What I am wondering: Why is there any code in `onStateUpdateFromItem()` at all? Why not simply leaving this method empty? I do not see a use case, where an update on the DateTime item could provide any information of interest to the handler. Can you help me understand this?

**Comment by cweitkamp** [comment]
Sry for unambiguous wording. That is exactly my question. Currently I tend to leave it empty.

**Comment by kaikreuzer** [comment]
Go for it, that's a much simpler solution!

**Comment by cweitkamp** [comment]
@kaikreuzer Done.

**Review by kaikreuzer — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
