### PR TITLE
Reverts https://github.com/openhab/openhab-core/pull/905

### PR DESCRIPTION
**Pull request by kaikreuzer**
See https://github.com/openhab/openhab-core/issues/924#issuecomment-511787620

Fixes https://github.com/openhab/openhab-core/issues/924
Fixes https://github.com/openhab/openhab-core/issues/918

### CODE REVIEW

**Comment by kaikreuzer** [comment]
I used Gits "reverse commit" feature, which does not add any sign-offs (as they don't make much sense since the commit does not include any copyrightable content from me).

**Comment by kaikreuzer** [comment]
As it is approved, I'll merge it together with https://github.com/openhab/openhab-distro/pull/944.

**Comment by maggu2810** [comment]
> I used Gits "reverse commit" feature, which does not add any sign-offs (as they don't make much sense since the commit does not include any copyrightable content from me).

Does it matter?
The git revert command supports the `-s, --signoff` option similar to the commit option.
And git revert is just some tooling to create a commit and commits should be signed off.

IMHO

Code has been removed by a commit and code will be added again by a revert commit.
The sign off should be used to state "I am allowed" to add code to the current code base.
Assume a commit removes code because the license has been not clear. If you revert the removal you should still state that you know what you are doing.

**Comment by kaikreuzer** [comment]
Ok, sorry then. I used the revert feature of SourceTree and this has no sign-off option. Will try to do it with `-s` on the command line in future instead.

**Pull request merged**
