### PR TITLE
Sync Jetty version with version used by Karaf 4.2.6

### PR DESCRIPTION
**Pull request by wborn**
Resolves the Jetty bundle duplicates as reported in #892 

---

I still had these changes on my local checkout. :smile:

### CODE REVIEW

**Comment by lolodomo** [comment]
Cool

**Comment by cweitkamp** [comment]
Thanks. Do we have to align the BOMs too? Do you think the Jenkins error (discovery.mdns tests) is related?

**Comment by wborn** [comment]
The mDNS itest has been unstable for a while, see also #567.

**Comment by cweitkamp** [comment]
Alright. Thanks.

**Pull request merged**
