### PR TITLE
Upgrade build tools and allow parallel builds on macOS 12 / M1

### PR DESCRIPTION
**Pull request by J-N-K**
I could never use parallel builds on my MacBook Air with M1 processor. The reason is that the execution of the integration tests always resulted in a stuck build. By upgrading some build tools (bnd, maven-compiler-blugin, ecj, plexus-compiler-eclipse and JDT annotation) I was able to run with `-T8`. However, some tests failed because they used `org.eclipse.jdt.annotation.Checks.requireNonNull` instead of `java.util.Objects.requireNonNull`. Finally I ran into https://github.com/openhab/openhab-distro/issues/1327 and solved it by adding the bundle to the `runblacklist` instruction of the test. 

As a result I can build the full core with all tests successfully in a little bit more than 10 minutes:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for openHAB Core 3.3.0-SNAPSHOT:
[INFO] 
[INFO] openHAB Core ....................................... SUCCESS [  4.248 s]
[INFO] openHAB Core :: BOM ................................ SUCCESS [  0.034 s]
[INFO] openHAB Core :: BOM :: Compile ..................... SUCCESS [  0.192 s]
[INFO] openHAB Core :: BOM :: Compile Model ............... SUCCESS [  0.184 s]
[INFO] openHAB Core :: BOM :: Runtime ..................... SUCCESS [  0.302 s]
[INFO] openHAB Core :: BOM :: Runtime Index ............... SUCCESS [  0.929 s]
[INFO] openHAB Core :: BOM :: Test ........................ SUCCESS [  0.189 s]
[INFO] openHAB Core :: BOM :: Test Index .................. SUCCESS [  0.522 s]
[INFO] openHAB Core :: Bundles ............................ SUCCESS [  2.507 s]
[INFO] openHAB Core :: Bundles :: Core .................... SUCCESS [04:34 min]
[INFO] openHAB Core :: Bundles :: Test .................... SUCCESS [ 12.761 s]
[INFO] openHAB Core :: Bundles :: Configuration Core ...... SUCCESS [ 16.476 s]
[INFO] openHAB Core :: Bundles :: Console ................. SUCCESS [  8.533 s]
[INFO] openHAB Core :: Bundles :: Thing ................... SUCCESS [ 35.814 s]
[INFO] openHAB Core :: Bundles :: Configuration Discovery . SUCCESS [ 16.827 s]
[INFO] openHAB Core :: Bundles :: Network I/O ............. SUCCESS [ 15.805 s]
[INFO] openHAB Core :: Bundles :: Ephemeris ............... SUCCESS [  8.817 s]
[INFO] openHAB Core :: Bundles :: Automation .............. SUCCESS [ 45.178 s]
[INFO] openHAB Core :: Bundles :: Magic Bundle ............ SUCCESS [ 18.032 s]
[INFO] openHAB Core :: Bundles :: REST Interface .......... SUCCESS [ 14.550 s]
[INFO] openHAB Core :: Bundles :: Karaf Integration ....... SUCCESS [ 10.782 s]
[INFO] openHAB Core :: Bundles :: HTTP Interface .......... SUCCESS [ 11.215 s]
[INFO] openHAB Core :: Bundles :: Audio ................... SUCCESS [ 21.266 s]
[INFO] openHAB Core :: Bundles :: Voice ................... SUCCESS [ 14.601 s]
[INFO] openHAB Core :: Bundles :: Configuration XML ....... SUCCESS [ 14.549 s]
[INFO] openHAB Core :: Bundles :: Binding XML ............. SUCCESS [  8.274 s]
[INFO] openHAB Core :: Bundles :: ID ...................... SUCCESS [  9.020 s]
[INFO] openHAB Core :: Bundles :: Persistence ............. SUCCESS [ 16.608 s]
[INFO] openHAB Core :: Bundles :: Semantics ............... SUCCESS [ 15.125 s]
[INFO] openHAB Core :: Bundles :: Thing XML ............... SUCCESS [ 13.581 s]
[INFO] openHAB Core :: Bundles :: Transformation Service .. SUCCESS [ 10.219 s]
[INFO] openHAB Core :: Bundles :: JAAS Authentication ..... SUCCESS [  6.761 s]
[INFO] openHAB Core :: Bundles :: OAuth2Client ............ SUCCESS [  9.966 s]
[INFO] openHAB Core :: Bundles :: Binary To JSON converter  SUCCESS [  8.459 s]
[INFO] openHAB Core :: Bundles :: mDNS Service ............ SUCCESS [ 10.687 s]
[INFO] openHAB Core :: Bundles :: Modbus Transport ........ SUCCESS [ 45.560 s]
[INFO] openHAB Core :: Bundles :: Serial Transport ........ SUCCESS [ 10.147 s]
[INFO] openHAB Core :: Bundles :: Console for OSGi framework Eclipse Equinox SUCCESS [  8.596 s]
[INFO] openHAB Core :: Bundles :: Console for OSGi Console RFC 147 SUCCESS [  9.137 s]
[INFO] openHAB Core :: Bundles :: Console for OSGi runtime Karaf SUCCESS [  9.413 s]
[INFO] openHAB Core :: Bundles :: HTTP Interface Authentication SUCCESS [  8.335 s]
[INFO] openHAB Core :: Bundles :: Monitor ................. SUCCESS [ 16.362 s]
[INFO] openHAB Core :: Bundles :: Audio REST Interface .... SUCCESS [  6.998 s]
[INFO] openHAB Core :: Bundles :: Authentication Support for the REST Interface SUCCESS [ 13.756 s]
[INFO] openHAB Core :: Bundles :: REST Interface :: Core .. SUCCESS [ 29.104 s]
[INFO] openHAB Core :: Bundles :: REST UI Logging Module .. SUCCESS [  9.134 s]
[INFO] openHAB Core :: Bundles :: REST mDNS Announcer ..... SUCCESS [ 10.426 s]
[INFO] openHAB Core :: Bundles :: Model Core .............. SUCCESS [ 12.170 s]
[INFO] openHAB Core :: Bundles :: Model Sitemap ........... SUCCESS [ 52.738 s]
[INFO] openHAB Core :: Bundles :: UI ...................... SUCCESS [ 29.960 s]
[INFO] openHAB Core :: Bundles :: Sitemap REST Interface .. SUCCESS [ 17.706 s]
[INFO] openHAB Core :: Bundles :: SSE Interface ........... SUCCESS [ 10.605 s]
[INFO] openHAB Core :: Bundles :: REST Interface :: Swagger 1 SUCCESS [  8.743 s]
[INFO] openHAB Core :: Bundles :: UI REST Interface ....... SUCCESS [  8.922 s]
[INFO] openHAB Core :: Bundles :: Voice REST Interface .... SUCCESS [  8.263 s]
[INFO] openHAB Core :: Bundles :: MQTT Transport .......... SUCCESS [ 15.632 s]
[INFO] openHAB Core :: Bundles :: Serial Transport for Java Communications API SUCCESS [  8.305 s]
[INFO] openHAB Core :: Bundles :: Serial Transport for RXTX SUCCESS [  7.769 s]
[INFO] openHAB Core :: Bundles :: Serial Transport for RFC2217 SUCCESS [  3.401 s]
[INFO] openHAB Core :: Bundles :: UPnP Transport .......... SUCCESS [ 13.163 s]
[INFO] openHAB Core :: Bundles :: SSL Certificate Generator SUCCESS [ 11.187 s]
[INFO] openHAB Core :: Bundles :: Configuration mDNS Discovery SUCCESS [ 11.276 s]
[INFO] openHAB Core :: Bundles :: Configuration USB-Serial Discovery SUCCESS [ 10.708 s]
[INFO] openHAB Core :: Bundles :: Configuration USB-Serial Discovery for Linux using sysfs scanning SUCCESS [ 11.596 s]
[INFO] openHAB Core :: Bundles :: Configuration USB-Serial Discovery using ser2net mDNS scanning SUCCESS [ 15.388 s]
[INFO] openHAB Core :: Bundles :: Configuration UPnP Discovery SUCCESS [ 11.564 s]
[INFO] openHAB Core :: Bundles :: Configuration Dispatcher  SUCCESS [ 12.205 s]
[INFO] openHAB Core :: Bundles :: Configuration Serial .... SUCCESS [ 14.518 s]
[INFO] openHAB Core :: Bundles :: Automation Script Modules SUCCESS [ 13.122 s]
[INFO] openHAB Core :: Bundles :: Automation Media Modules  SUCCESS [  8.523 s]
[INFO] openHAB Core :: Bundles :: Automation Script RuleSupport SUCCESS [ 14.456 s]
[INFO] openHAB Core :: Bundles :: Automation REST API ..... SUCCESS [ 10.750 s]
[INFO] openHAB Core :: Bundles :: Model Items ............. SUCCESS [ 42.334 s]
[INFO] openHAB Core :: Bundles :: Model Item IDE .......... SUCCESS [ 15.951 s]
[INFO] openHAB Core :: Bundles :: Model Items Runtime ..... SUCCESS [  9.816 s]
[INFO] openHAB Core :: Bundles :: Model Persistence ....... SUCCESS [ 39.495 s]
[INFO] openHAB Core :: Bundles :: Model Persistence IDE ... SUCCESS [ 16.188 s]
[INFO] openHAB Core :: Bundles :: Model Script ............ SUCCESS [01:03 min]
[INFO] openHAB Core :: Bundles :: Model Rules ............. SUCCESS [ 18.234 s]
[INFO] openHAB Core :: Bundles :: Model Rule IDE .......... SUCCESS [  5.200 s]
[INFO] openHAB Core :: Bundles :: Model Script IDE ........ SUCCESS [  6.425 s]
[INFO] openHAB Core :: Bundles :: Model Sitemap IDE ....... SUCCESS [ 19.630 s]
[INFO] openHAB Core :: Bundles :: Model Thing ............. SUCCESS [ 42.979 s]
[INFO] openHAB Core :: Bundles :: Model Thing IDE ......... SUCCESS [ 10.875 s]
[INFO] openHAB Core :: Bundles :: Language Server ......... SUCCESS [  3.644 s]
[INFO] openHAB Core :: Bundles :: Model Persistence Runtime SUCCESS [  9.928 s]
[INFO] openHAB Core :: Bundles :: Model Script Runtime .... SUCCESS [  4.151 s]
[INFO] openHAB Core :: Bundles :: Model Rules Runtime ..... SUCCESS [  4.141 s]
[INFO] openHAB Core :: Bundles :: Model Sitemap Runtime ... SUCCESS [ 10.394 s]
[INFO] openHAB Core :: Bundles :: Model Thing Runtime ..... SUCCESS [  6.859 s]
[INFO] openHAB Core :: Bundles :: UI Icon Support ......... SUCCESS [ 11.713 s]
[INFO] openHAB Core :: Bundles :: JSON Storage ............ SUCCESS [ 11.345 s]
[INFO] openHAB Core :: Bundles :: Marketplace Add-on Services SUCCESS [ 14.612 s]
[INFO] openHAB Core :: Bundles :: Community Marketplace Add-on Service :: Karaf SUCCESS [  5.967 s]
[INFO] openHAB Core :: BOM :: openHAB Core ................ SUCCESS [  0.023 s]
[INFO] openHAB Core :: BOM :: openHAB Core Index .......... SUCCESS [  1.632 s]
[INFO] openHAB Core :: Bundles :: Sample Add-on Service ... SUCCESS [  8.641 s]
[INFO] openHAB Core :: Bundles :: Model Lazy Generation ... SUCCESS [ 11.165 s]
[INFO] openHAB Core :: Features ........................... SUCCESS [  0.041 s]
[INFO] openHAB Core :: Features :: Karaf .................. SUCCESS [  0.061 s]
[INFO] openHAB Core :: Features :: Karaf :: Target Platform SUCCESS [ 28.696 s]
[INFO] openHAB Core :: Features :: Karaf :: Core .......... SUCCESS [01:32 min]
[INFO] openHAB Core :: Tools .............................. SUCCESS [  0.060 s]
[INFO] openHAB Core :: Tools :: Archetypes ................ SUCCESS [  0.109 s]
[INFO] openHAB Core :: Tools :: Archetypes :: Binding ..... SUCCESS [  1.669 s]
[INFO] Internationalization Maven Plugin .................. SUCCESS [ 17.713 s]
[INFO] openHAB Core :: Integration Tests .................. SUCCESS [  1.088 s]
[INFO] openHAB Core :: Integration Tests :: Tests ......... SUCCESS [ 21.661 s]
[INFO] openHAB Core :: Integration Tests :: OAuth2Client Tests SUCCESS [ 12.781 s]
[INFO] openHAB Core :: Integration Tests :: Automation Tests SUCCESS [ 13.771 s]
[INFO] openHAB Core :: Integration Tests :: Automation Core Module Tests SUCCESS [ 13.793 s]
[INFO] openHAB Core :: Integration Tests :: Automation Module Timer Tests SUCCESS [ 19.858 s]
[INFO] openHAB Core :: Integration Tests :: Automation Script Module Tests SUCCESS [ 14.977 s]
[INFO] openHAB Core :: Integration Tests :: Automation Integration Tests SUCCESS [ 37.294 s]
[INFO] openHAB Core :: Integration Tests :: Binding XML Tests SUCCESS [ 14.398 s]
[INFO] openHAB Core :: Integration Tests :: Configuration Core Tests SUCCESS [ 13.956 s]
[INFO] openHAB Core :: Integration Tests :: Configuration mDNS Discovery Tests SUCCESS [ 12.617 s]
[INFO] openHAB Core :: Integration Tests :: Configuration Discovery Tests SUCCESS [ 30.882 s]
[INFO] openHAB Core :: Integration Tests :: Configuration Discovery UsbSerial Tests SUCCESS [ 12.633 s]
[INFO] openHAB Core :: Integration Tests :: Configuration Dispatcher Tests SUCCESS [ 16.105 s]
[INFO] openHAB Core :: Integration Tests :: Configuration XML Tests SUCCESS [ 12.588 s]
[INFO] openHAB Core :: Integration Tests :: Ephemeris Tests SUCCESS [ 12.641 s]
[INFO] openHAB Core :: Integration Tests :: IO REST Core Tests SUCCESS [ 19.792 s]
[INFO] openHAB Core :: Integration Tests :: Model Core Tests SUCCESS [01:12 min]
[INFO] openHAB Core :: Integration Tests :: Model Item Tests SUCCESS [ 24.521 s]
[INFO] openHAB Core :: Integration Tests :: Model Rule Tests SUCCESS [ 24.101 s]
[INFO] openHAB Core :: Integration Tests :: Model Script Tests SUCCESS [ 25.893 s]
[INFO] openHAB Core :: Integration Tests :: Model Thing Test Support SUCCESS [  7.130 s]
[INFO] openHAB Core :: Integration Tests :: Model Thing Tests SUCCESS [ 16.089 s]
[INFO] openHAB Core :: Integration Tests :: JSON Storage Tests SUCCESS [ 12.353 s]
[INFO] openHAB Core :: Integration Tests :: Thing Tests ... SUCCESS [01:25 min]
[INFO] openHAB Core :: Integration Tests :: Thing XML Tests SUCCESS [ 16.961 s]
[INFO] openHAB Core :: Integration Tests :: Voice Test .... SUCCESS [ 13.094 s]
[INFO] openHAB Core :: Integration Tests :: Configuration USB-Serial Discovery for Linux using sysfs scanning Tests SUCCESS [ 12.716 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10:21 min (Wall Clock)
[INFO] Finished at: 2022-03-12T18:09:55+01:00
[INFO] ------------------------------------------------------------------------
```

The non-parallel build takes 17:33 min, so the improvement is quite significant. Especially taking into account that the `AbstractWatchServiceTest` alone takes more than three minutes.

Signed-off-by: Jan N. Klug <github@klug.nrw>

### CODE REVIEW

**Comment by wborn** [comment]
I'd also get very annoyed if parallel builds would not work! 

Maybe it is possible to further increase the number of threads on the M1? I always build using `-T 1.5C` so the cores are saturated with work even if some threads are waiting on I/O or during tests. Giving Maven more memory also speeds up builds. I have plenty of memory so always set `MAVEN_OPTS=-Xmx4g`

On my aging i7-6700K (2015) it currently takes "10:31 min" to do a full openhab-core parallel build with tests, SAT and feature verification. I would expect it to be possible for the M1 to significantly beat my old CPU. :slightly_smiling_face: 

Can you also update those build tools in the addons/webui/distro repos so they all keep working similarly?

**Comment by J-N-K** [comment]
One reason it takes so long is really this one:

```
    @BeforeAll
    public static void setUpBeforeClass() {
        // set the NO_EVENT_TIMEOUT_IN_SECONDS according to the operating system used
        if (System.getProperty("os.name").startsWith("Mac OS X")) {
            noEventTimeoutInSeconds = 15;
        } else {
            noEventTimeoutInSeconds = 3;
        }
    }
```

which makes the `AbstractWatchServiceTest` take 5 times what it would take on Windows/Linux machines. Since it is in the `org.openhab.core` bundle and nearly all other bundles depend on that, the build waits a very long time here.

I can update addons and distro, but I can't build webui due to https://github.com/openhab/openhab-webui/issues/1165.

**Comment by J-N-K** [comment]
Do you know why we use 

```
                    <groupId>org.apache.felix</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.6.1</version>
```

in distro and

```
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.1</version>
          
```

in all other repositories?

**Comment by wborn** [comment]
> which makes the AbstractWatchServiceTest take 5 times what it would take on Windows/Linux machines. Since it is in the org.openhab.core bundle and nearly all other bundles depend on that, the build waits a very long time here.

That's a pity :confused: I also noticed my cores were sitting idle while org.openhab.core was building, so I've put those core to use with #2837. Maybe it also helps your build a bit. With these changes a full build now only took "09:02 min" (Java 17). :smile: 

> I can update addons and distro, but I can't build webui due to https://github.com/openhab/openhab-webui/issues/1165.

Very good! :+1: 

> Do you know why we use ... in distro and ... in all other repositories?

Not really, but if possible I would stick to the `org.apache.maven.plugins` compiler which is more standard. Maybe it is some kind of PDE leftover.

**Review by wborn — APPROVED** [review]
Thanks for the upgrades and fixes! :+1:

**Comment by wborn** [comment]
> AbstractWatchServiceTest take 5 times what it would take on Windows/Linux machines

It seems that the root cause for these WatchService issues on macOS is that the JVM uses polling instead of some native watch service mechnism. Until that is fixed, there is the [gmethvin/directory-watcher](https://github.com/gmethvin/directory-watcher) library which provides a native mechanism. It also seems to fix duplicate WatchService events on other OS-es by keeping track of file hashes.

**Comment by J-N-K** [comment]
Do you think we should switch to that implementation?

**Comment by wborn** [comment]
I don't know if the [known library issues](https://github.com/gmethvin/directory-watcher/issues) outweigh the benefits but it might be worth a try to see how well it works. :slightly_smiling_face:
If it works well it might fix long-standing issues like https://github.com/openhab/openhab-core/issues/671 and it would also be nice for macOS users to see their build times significantly reduced.

**Pull request merged**
