### PR TITLE
Add Automation extension type

### PR DESCRIPTION
**Pull request by wborn**
This type allows for installing automation add-ons such as:
* [Groovy Scripting](https://github.com/openhab/openhab-addons/pull/8772)
* [Jython Scripting](https://github.com/openhab/openhab-addons/pull/7208)
* [JS Scripting](https://github.com/openhab/openhab-addons/pull/8516)

### CODE REVIEW

**Comment by ghys** [comment]
Heads up, this has implications for the UI, docs processing, and website :)

**Comment by wborn** [comment]
Yes it does result in some more work. 

The UI already works well except for that it looks a bit bland:

Screenshot from 2020-10-16 23-23-03

Screenshot from 2020-10-16 23-28-30

**Comment by ghys** [comment]
That's the part where I thought it would break 😄

**Review by kaikreuzer — APPROVED** [review]
Imho much better than having it all under "Misc" - so assuming @ghys and @Confectrician will help adapting UI and docs/website, let's merge it 👍 .

**Comment by wborn** [comment]
I'm looking forward to see what kind of icon @ghys comes up with for this one. :wink:

**Comment by ghys** [comment]
Browsed the entire list of [icons](https://framework7.io/icons/) twice now. 😄 

I think the best option is to go with this one:
image

Provided we also replace the "Rules" icons from wand_rays to wand_stars:
image

The stars could be a reference to "magic", i.e. automation...?

As for the blurb below maybe: "Scripting languages and module types for rules" or similar?
image

**Comment by wborn** [comment]
I'm fine with that as it indeed does make sense that you need to apply sparkles with a wand. :-)

**Comment by kaikreuzer** [comment]
Go for it!

**Pull request merged**
