### PR TITLE
Bump UoM libraries to 2.2

### PR DESCRIPTION
**Pull request by J-N-K**

### CODE REVIEW

**Review by wborn — APPROVED** [review]
Thanks for the upgrade! Can you also create PRs for resolving the runbundles in the addons/distro repos?

**Comment by J-N-K** [comment]
Sure

**Comment by J-N-K** [comment]
@wborn Accidentally (because of a git misconfiguration) I pushed the openhab-distro change to the upstream-repo. Can you check and revert if necessary?

**Comment by wborn** [comment]
Yes it looks OK to me. :+1: Pushing to the wrong origin is always an accident waiting to happen. :upside_down_face:

**Pull request merged**
