### PR TITLE
Initial contribution of an implementation of the Automatic Certificat…

### PR DESCRIPTION
**Pull request by kgoderis**
…e Management Environment (ACME) protocol

This PR will require a CQ as some new external libs are included

Also, services.cfg needs to be expanded and include 

`org.openhab.io.jetty.certificate.generator:domain=mydomain.dyndns.org
`

and

`org.openhab.io.jetty.certificate.generator:type=acme
`

or

`org.openhab.io.jetty.certificate.generator:type=selfsigned
`

Signed-off-by: Karel Goderis <karel.goderis@me.com>

### CODE REVIEW

**Comment by kgoderis** [comment]
@kaikreuzer Can you introduce the CQ?

**Comment by kaikreuzer** [comment]
No need to file CQs for openHAB contributions!

**Comment by kgoderis** [comment]
Ok, so then you only have to merge it.... ;-)

**Comment by kgoderis** [comment]
@kaikreuzer ping....

**Comment by kaikreuzer** [comment]
It's a too big and risky change that I would merge it untested. WIll need some time for it and I am not sure if it is a good idea to merge for the 2.0 release already.

**Comment by kgoderis** [comment]
It can definitely wait after end of Jan, no stress

**Comment by kaikreuzer** [comment]
Many thanks! (I already have stress ;-))

**Comment by kaikreuzer** [comment]
Closing this as it is superseded by https://github.com/eclipse/smarthome/issues/4088.

**Pull request closed without merging**
