### PR TITLE
ensure rules can access joda time packages

### PR DESCRIPTION
**Pull request by maggu2810**
Fixes: https://github.com/openhab/openhab-core/issues/553

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Question: Won't we need the same fix for https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.model.script/bnd.bnd#L48?

**Comment by maggu2810** [comment]
The JAR file that are generated on my machine includes already that packages for the script models, as they are used by the code.
Are they missing on yours?

**Comment by kaikreuzer** [comment]
I didn't check it, that's why I was asking - the code looked similar, so I thought it might have the same problem.
If there is no problem, even better!

**Comment by maggu2810** [comment]
That's instructions for bnd.
The difference is that script is using the Joda packages in the code, the rule doesn't.
I assume the script executor should also fallback to another classloader (context?) to resolve classes that has been added and the caller does not need to know about.

**Pull request merged**
