### PR TITLE
add test: org.openhab.core.config.core

### PR DESCRIPTION
**Pull request by maggu2810**

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Now you have to figure out, why there are 3 faling tests... 
https://ci.openhab.org/job/PR-openHAB-Core/963/testReport/

**Comment by maggu2810** [comment]
> Now you have to ...

... think about why I should invest the time to migrate the existing tests? :wink:

**Comment by maggu2810** [comment]
I am not able to cancel running jobs on "PR-openHAB-Core" or to inspect the configuration (of the job and server). Would it be possible?

**Comment by maggu2810** [comment]
```Java
    @Before
    public void setup() throws URISyntaxException {
        provider = new I18nConfigOptionsProvider();
        uriI18N = new URI("system:i18n");
    }

    @Test
    public void testLanguage() throws Exception {
        assertThat(provider, not(nullValue()));
```

The test fails because `provider` is `null`.
I don't understand why -- it seems `setup` that is marked with `@Before` is not executed.

**Comment by maggu2810** [comment]
Reading the log I wonder why "openHAB Core :: Bundles :: Core" is not part of e.g. [#972](https://ci.openhab.org/job/PR-openHAB-Core/972/consoleFull)

**Comment by maggu2810** [comment]
The job [980](https://ci.openhab.org/job/PR-openHAB-Core/980/) has been triggered by [this](https://github.com/openhab/openhab-core/pull/516/commits/7c054d5126ab1c5283cd7833516b89883dfa336d) commit.

The log indicates:

```
12:29:51 [INFO] Reactor Build Order:
12:29:51 [INFO] 
12:29:51 [INFO] openHAB Core :: Bundles :: Test
12:29:51 [INFO] openHAB Core :: Bundles :: Configuration Core
```

So, the test BOM that is used by all the tests if not build in front of its usage.
It is not part of the whole build 980 at all.

I assume you enabled to build only changed stuff.
Can you please disable that option and do a full build.

**Comment by kaikreuzer** [comment]
Just to understand the problem: Why do unchanged parts need to be rebuilt and not reused from the local repo?

**Comment by maggu2810** [comment]
Can you please elaborate what "unchanged" means on a PR builder?
The source between the previous build and this build?
What if the build fails, is considered which artifacts has been already deployed to the local repository?
Do you use different local repositories between the master build and the PR build?

**Comment by maggu2810** [comment]
... and my example above should show that there has been changes in the test POM (added dependencies) but it has not been build.

**Comment by kaikreuzer** [comment]
> The source between the previous build and this build?

Yes, I hoped that it would identify the changes to the previous checkout and build those - but this might be a false assumption.

> Do you use different local repositories between the master build and the PR build?

Yes.

I have removed the "incremental build" flag now.

**Comment by kaikreuzer** [comment]
All green, how nice - sorry for the hassle!

**Pull request merged**
