### PR TITLE
Fix NPE of AddonServices during startup

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by J-N-K** [comment]
This is already part of #2607.

**Comment by kaikreuzer** [comment]
But #2607 seems to be much bigger and do a lot more.
I prefer small PRs that can be merged quickly for such bugs.

**Comment by J-N-K** [comment]
The CommunityMarketplaceAddonService has the same issue.

**Comment by cweitkamp** [comment]
Looks good so far. Thanks.

We have to fix this in the `CommunityMarketplaceAddonService` too.

https://github.com/openhab/openhab-core/blob/0a778df0adddd90f3db219662c1d7c7369bed14f/bundles/org.openhab.core.addon.marketplace/src/main/java/org/openhab/core/addon/marketplace/internal/community/CommunityMarketplaceAddonService.java#L482

**Comment by kaikreuzer** [comment]
Ok, I have added it for `CommunityMarketplaceAddonService`, too.

**Review by cweitkamp — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
