### PR TITLE
Add missing system profile types and UIDs

### PR DESCRIPTION
**Pull request by J-N-K**
See https://github.com/openhab/openhab-core/issues/4277#issuecomment-2227229188

### CODE REVIEW

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Comment by kaikreuzer** [comment]
Shall we backport this to 4.2.x?

**Comment by kaikreuzer** [comment]
Cherry-picked to `4.2.x`.

**Comment by wborn** [comment]
Now it is cherry-picked to the OH repo.

**Pull request merged**
