### PR TITLE
Upgrade to JmDNS 3.5.9

### PR DESCRIPTION
**Pull request by kaikreuzer**
See [changelog](https://github.com/jmdns/jmdns/milestone/11?closed=1)

### CODE REVIEW

**Review by wborn — CHANGES_REQUESTED** [review]
Thanks for the upgrade!
The Karaf feature also needs to be updated.

**Comment by wborn** [comment]
The version also needs to be resolved in `org.openhab.core.config.discovery.mdns.tests/itest.bndrun`

**Comment by kaikreuzer** [comment]
So many places... Thanks for the quick review!

**Review by wborn — APPROVED** [review]
LGTM now!

**Pull request merged**
