### PR TITLE
[voice] New voice manager dialog methods

### PR DESCRIPTION
**Pull request by GiviMAD**
New dialog methods for voice manager.

Related to https://github.com/openhab/openhab-core/issues/3140

Will close this one https://github.com/openhab/openhab-core/issues/3104

Signed-off-by: Miguel Álvarez <miguelwork92@gmail.com>

### CODE REVIEW

**Comment by GiviMAD** [comment]
@J-N-K I have done this using a record but spotless seems not ready for using record classes.
```
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.0.3:check (codestyle_check) on project org.openhab.core.voice: Execution codestyle_check of goal com.diffplug.spotless:spotless-maven-plugin:2.0.3:check failed: java.lang.reflect.InvocationTargetException: 30:9: error: class, interface, or enum expected -> [Help 1]
```
Is better to write it using a normal class for now?

**Comment by GiviMAD** [comment]
I have changed it to class for now as the change was easy.

**Comment by GiviMAD** [comment]
I think this PR is ready, I will open another one with the action and command changes once this gets merged.
Let me know if you think is better to add those to this PR instead.

**Review by wborn — APPROVED** [review]
It's much better to have a context instead of all those parameters. :+1:

**Pull request merged**
