### PR TITLE
Fix exception in WindowsUsbSerialDiscovery

### PR DESCRIPTION
**Pull request by mherwege**
Fixes https://github.com/openhab/openhab-core/pull/4224#issuecomment-2119849776

### CODE REVIEW

**Review by J-N-K — APPROVED** [review]
Thanks

**Comment by lolodomo** [comment]
Thank you @mherwege 
Did you check we don't have the same issue in the other UsbSerialDiscovery ?

**Comment by mherwege** [comment]
> Thank you @mherwege 
> Did you check we don't have the same issue in the other UsbSerialDiscovery ?

No, I didn't.

**Comment by lolodomo** [comment]
I found `Ser2NetUsbSerialDiscovery`: no bug because the deactivate method is missing. Should probably be added.

**Pull request merged**
