### PR TITLE
[Semantics] Fix properties loading

### LINKED ISSUE #956: Integrations tests - Semantics Tests failure
Run on Windows 10:
```
[INFO] --- bnd-testing-maven-plugin:4.2.0:testing (default) @ org.openhab.core.semantics.tests ---
[INFO] Matching glob *
20:24:54.175 [main] DEBUG org.eclipse.smarthome.core.common.ThreadPoolManager - Created thread pool 'safeCall' with size 5
20:24:54.238 [main] DEBUG org.eclipse.smarthome.core.internal.i18n.I18nProviderImpl - No language set, setting locale to 'null'.
20:24:54.238 [main] DEBUG org.eclipse.smarthome.core.internal.i18n.I18nProviderImpl - Error setting measurement system for value 'null'.
20:24:54.300 [main] DEBUG org.eclipse.smarthome.core.common.ThreadPoolManager - Created scheduled thread pool 'scheduler' of size 5
20:24:54.332 [main] DEBUG org.eclipse.smarthome.core.common.ThreadPoolManager - Created thread pool 'ConfigStatusService' with size 5
20:24:54.332 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "org.eclipse.smarthome.core.semantics.internal.SemanticsMetadataProvider" has been added.
20:24:54.363 [main] DEBUG org.eclipse.smarthome.storage.json.internal.JsonStorageService - Json Storage Service: Activated.
20:24:54.363 [main] DEBUG org.eclipse.smarthome.storage.json.internal.JsonStorage - Json storage file at 'D:\dev\openhab2\git\openhab-core\itests\org.openhab.core.semantics.tests\target\test\tmp\testing\itest\userdata\jsondb\org.eclipse.smarthome.core.items.Metadata.json' does not exist - checking for a backup.
20:24:54.378 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "org.eclipse.smarthome.core.internal.items.ManagedMetadataProviderImpl" has been added.
20:24:54.378 [main] DEBUG org.eclipse.smarthome.storage.json.internal.JsonStorage - Json storage file at 'D:\dev\openhab2\git\openhab-core\itests\org.openhab.core.semantics.tests\target\test\tmp\testing\itest\userdata\jsondb\org.eclipse.smarthome.core.items.Item.json' does not exist - checking for a backup.
20:24:54.378 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "org.eclipse.smarthome.core.items.ManagedItemProvider" has been added.
TEST testByLabelOrSynonym(org.eclipse.smarthome.core.semantics.SemanticTagsTest) <<< ERROR: null
java.util.NoSuchElementException
        at java.util.ArrayList$Itr.next(ArrayList.java:854)
        at org.eclipse.smarthome.core.semantics.SemanticTagsTest.testByLabelOrSynonym(SemanticTagsTest.java:75)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at aQute.junit.Activator.test(Activator.java:340)
        at aQute.junit.Activator.automatic(Activator.java:236)
        at aQute.junit.Activator.run(Activator.java:177)
        at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1385)
        at aQute.launcher.Launcher.run(Launcher.java:352)
        at aQute.launcher.Launcher.main(Launcher.java:152)
TEST testByLabel(org.eclipse.smarthome.core.semantics.SemanticTagsTest) <<< ERROR: expected:<interface org.eclipse.smarthome.core.semantics.model.location.Kitchen> but was:<null>
java.lang.AssertionError: expected:<interface org.eclipse.smarthome.core.semantics.model.location.Kitchen> but was:<null>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.eclipse.smarthome.core.semantics.SemanticTagsTest.testByLabel(SemanticTagsTest.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at aQute.junit.Activator.test(Activator.java:340)
        at aQute.junit.Activator.automatic(Activator.java:236)
        at aQute.junit.Activator.run(Activator.java:177)
        at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1385)
        at aQute.launcher.Launcher.run(Launcher.java:352)
        at aQute.launcher.Launcher.main(Launcher.java:152)
TEST testGetItemsInLocation(org.eclipse.smarthome.core.semantics.internal.SemanticsServiceImplTest) <<< ERROR: null
java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.eclipse.smarthome.core.semantics.internal.SemanticsServiceImplTest.testGetItemsInLocation(SemanticsServiceImplTest.java:89)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at aQute.junit.Activator.test(Activator.java:340)
        at aQute.junit.Activator.automatic(Activator.java:236)
        at aQute.junit.Activator.run(Activator.java:177)
        at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1385)
        at aQute.launcher.Launcher.run(Launcher.java:352)
        at aQute.launcher.Launcher.main(Launcher.java:152)
Tests run  : 7
Passed     : 4
Errors     : 3
Failures   : 0
[INFO] 3 Error(s)
```

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #956

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by cweitkamp** [comment]
Thank you for all the work in the last couple of days.

I am not sure if this is the right way to do it. Shouldn't we take the same path like we do in all the other i18n stuff?

https://github.com/openhab/openhab-core/blob/608507e451ca7b71171f273cfc9f3c1c7831df61/bundles/org.openhab.core/src/main/java/org/eclipse/smarthome/core/internal/i18n/LanguageResourceBundleManager.java#L176-L180

**Comment by lolodomo** [comment]
Yes, that is possible, the behavior will be slightly different.
With my code, if your default locale is French and you ask for Italian, this will finally consider tags_fr..properties.
With our i18n logic, in this case, tags.properties will be considered.
In all other cases, the result will be the same.
I agree that it makes more sense to consider the i18n logic for the semantics.

**Comment by lolodomo** [comment]
Ok, done.

**Comment by ghys** [comment]
Possibly related and my fix at the time:
https://github.com/ghys/habot/commit/f4a71cd5f4273277097620e314fbfe8a05490dc0

**Comment by lolodomo** [comment]
With this merge, I am finally able again to run a full build (including tests) of the openHAB core framework with success on Windows 10. It takes around 26 minutes on my PC.
```
[INFO] Reactor Summary:
[INFO]
[INFO] openHAB Core ....................................... SUCCESS [  6.998 s]
[INFO] openHAB Core :: BOM ................................ SUCCESS [  0.047 s]
[INFO] openHAB Core :: BOM :: Compile ..................... SUCCESS [  1.015 s]
[INFO] openHAB Core :: BOM :: Compile Model ............... SUCCESS [  1.593 s]
[INFO] openHAB Core :: BOM :: Runtime ..................... SUCCESS [  3.265 s]
[INFO] openHAB Core :: BOM :: Runtime Index ............... SUCCESS [ 25.354 s]
[INFO] openHAB Core :: BOM :: Test ........................ SUCCESS [  0.187 s]
[INFO] openHAB Core :: BOM :: Test Index .................. SUCCESS [  1.266 s]
[INFO] openHAB Core :: Bundles ............................ SUCCESS [  0.234 s]
[INFO] openHAB Core :: Bundles :: Core .................... SUCCESS [01:02 min]
[INFO] openHAB Core :: Bundles :: Test .................... SUCCESS [  7.223 s]
[INFO] openHAB Core :: Bundles :: Configuration Core ...... SUCCESS [ 10.176 s]
[INFO] openHAB Core :: Bundles :: Console ................. SUCCESS [  4.561 s]
[INFO] openHAB Core :: Bundles :: Thing ................... SUCCESS [ 15.810 s]
[INFO] openHAB Core :: Bundles :: Configuration Discovery . SUCCESS [  6.061 s]
[INFO] openHAB Core :: Bundles :: Network I/O ............. SUCCESS [  5.842 s]
[INFO] openHAB Core :: Bundles :: Scheduler Service ....... SUCCESS [  7.389 s]
[INFO] openHAB Core :: Bundles :: Automation .............. SUCCESS [ 14.309 s]
[INFO] openHAB Core :: Bundles :: Magic Bundle ............ SUCCESS [  5.718 s]
[INFO] openHAB Core :: Bundles :: Model Core .............. SUCCESS [  8.576 s]
[INFO] openHAB Core :: Bundles :: Persistence ............. SUCCESS [  5.045 s]
[INFO] openHAB Core :: Bundles :: Model Persistence ....... SUCCESS [ 25.088 s]
[INFO] openHAB Core :: Bundles :: Ephemeris ............... SUCCESS [  5.062 s]
[INFO] openHAB Core :: Bundles :: Transformation Service .. SUCCESS [  4.998 s]
[INFO] openHAB Core :: Bundles :: HTTP Interface .......... SUCCESS [  4.843 s]
[INFO] openHAB Core :: Bundles :: Audio ................... SUCCESS [  6.186 s]
[INFO] openHAB Core :: Bundles :: Voice ................... SUCCESS [  8.422 s]
[INFO] openHAB Core :: Bundles :: Model Script ............ SUCCESS [ 41.269 s]
[INFO] openHAB Core :: Bundles :: Model Rules ............. SUCCESS [ 41.319 s]
[INFO] openHAB Core :: Bundles :: Model Rules Runtime ..... SUCCESS [  6.295 s]
[INFO] openHAB Core :: Bundles :: Model Sitemap ........... SUCCESS [ 27.806 s]
[INFO] openHAB Core :: Bundles :: Boot .................... SUCCESS [  4.764 s]
[INFO] openHAB Core :: Bundles :: Model Items ............. SUCCESS [ 16.497 s]
[INFO] openHAB Core :: Bundles :: UI ...................... SUCCESS [ 10.263 s]
[INFO] openHAB Core :: Bundles :: 1.x Compatibility Layer . SUCCESS [ 11.966 s]
[INFO] openHAB Core :: Bundles :: Karaf Integration ....... SUCCESS [  7.373 s]
[INFO] openHAB Core :: Bundles :: Configuration XML ....... SUCCESS [  6.951 s]
[INFO] openHAB Core :: Bundles :: Binding XML ............. SUCCESS [  5.202 s]
[INFO] openHAB Core :: Bundles :: Sample Extension Service  SUCCESS [  4.234 s]
[INFO] openHAB Core :: Bundles :: REST Interface .......... SUCCESS [  6.866 s]
[INFO] openHAB Core :: Bundles :: ID ...................... SUCCESS [ 15.715 s]
[INFO] openHAB Core :: Bundles :: Semantics ............... SUCCESS [  8.347 s]
[INFO] openHAB Core :: Bundles :: Thing XML ............... SUCCESS [  7.482 s]
[INFO] openHAB Core :: Bundles :: JAAS Authentication ..... SUCCESS [  4.249 s]
[INFO] openHAB Core :: Bundles :: OAuth2Client ............ SUCCESS [  6.608 s]
[INFO] openHAB Core :: Bundles :: mDNS Service ............ SUCCESS [  5.655 s]
[INFO] openHAB Core :: Bundles :: Serial Transport ........ SUCCESS [  5.296 s]
[INFO] openHAB Core :: Bundles :: Console for OSGi framework Eclipse Equinox SUCCESS [  4.436 s]
[INFO] openHAB Core :: Bundles :: Console for OSGi Console RFC 147 SUCCESS [  4.968 s]
[INFO] openHAB Core :: Bundles :: Console for OSGi runtime Karaf SUCCESS [  4.827 s]
[INFO] openHAB Core :: Bundles :: HTTP Interface Authentication SUCCESS [  4.842 s]
[INFO] openHAB Core :: Bundles :: HTTP Interface Basic Authentication SUCCESS [  4.171 s]
[INFO] openHAB Core :: Bundles :: Monitor ................. SUCCESS [  4.312 s]
[INFO] openHAB Core :: Bundles :: Authentication Support for the REST Interface SUCCESS [  4.171 s]
[INFO] openHAB Core :: Bundles :: REST Interface :: Core .. SUCCESS [ 10.247 s]
[INFO] openHAB Core :: Bundles :: REST UI Logging Module .. SUCCESS [  4.702 s]
[INFO] openHAB Core :: Bundles :: REST mDNS Announcer ..... SUCCESS [  4.124 s]
[INFO] openHAB Core :: Bundles :: REST JAX-RS Optimizations SUCCESS [  4.359 s]
[INFO] openHAB Core :: Bundles :: Sitemap REST Interface .. SUCCESS [ 20.113 s]
[INFO] openHAB Core :: Bundles :: SSE Interface ........... SUCCESS [  5.420 s]
[INFO] openHAB Core :: Bundles :: Voice REST Interface .... SUCCESS [  4.609 s]
[INFO] openHAB Core :: Bundles :: DBus Transport .......... SUCCESS [  1.640 s]
[INFO] openHAB Core :: Bundles :: MQTT Transport .......... SUCCESS [  8.776 s]
[INFO] openHAB Core :: Bundles :: Serial Transport for Java Communications API SUCCESS [  5.061 s]
[INFO] openHAB Core :: Bundles :: Serial Transport for RXTX SUCCESS [  5.140 s]
[INFO] openHAB Core :: Bundles :: Serial Transport for RFC2217 SUCCESS [  4.421 s]
[INFO] openHAB Core :: Bundles :: UPnP Transport .......... SUCCESS [  5.701 s]
[INFO] openHAB Core :: Bundles :: SSL Certificate Generator SUCCESS [  7.264 s]
[INFO] openHAB Core :: Bundles :: Configuration mDNS Discovery SUCCESS [  6.202 s]
[INFO] openHAB Core :: Bundles :: Configuration USB-Serial Discovery SUCCESS [  5.374 s]
[INFO] openHAB Core :: Bundles :: Configuration USB-Serial Discovery for Linux using sysfs scanning SUCCESS [  5.639 s]
[INFO] openHAB Core :: Bundles :: Configuration UPnP Discovery SUCCESS [  5.327 s]
[INFO] openHAB Core :: Bundles :: Configuration Dispatcher  SUCCESS [  6.061 s]
[INFO] openHAB Core :: Bundles :: Configuration Serial .... SUCCESS [  4.593 s]
[INFO] openHAB Core :: Bundles :: Automation Script Modules SUCCESS [  7.764 s]
[INFO] openHAB Core :: Bundles :: Automation Media Modules  SUCCESS [  6.092 s]
[INFO] openHAB Core :: Bundles :: Automation Script RuleSupport SUCCESS [  8.154 s]
[INFO] openHAB Core :: Bundles :: Automation REST API ..... SUCCESS [  5.671 s]
[INFO] openHAB Core :: Bundles :: Model Item IDE .......... SUCCESS [ 10.107 s]
[INFO] openHAB Core :: Bundles :: Model Items Runtime ..... SUCCESS [  4.827 s]
[INFO] openHAB Core :: Bundles :: Model Persistence IDE ... SUCCESS [  9.794 s]
[INFO] openHAB Core :: Bundles :: Model Rule IDE .......... SUCCESS [ 10.607 s]
[INFO] openHAB Core :: Bundles :: Model Script IDE ........ SUCCESS [  9.779 s]
[INFO] openHAB Core :: Bundles :: Model Sitemap IDE ....... SUCCESS [ 10.716 s]
[INFO] openHAB Core :: Bundles :: Model Thing ............. SUCCESS [ 21.774 s]
[INFO] openHAB Core :: Bundles :: Model Thing IDE ......... SUCCESS [  9.857 s]
[INFO] openHAB Core :: Bundles :: Language Server ......... SUCCESS [  5.842 s]
[INFO] openHAB Core :: Bundles :: Model Persistence Runtime SUCCESS [  4.718 s]
[INFO] openHAB Core :: Bundles :: Model Script Runtime .... SUCCESS [  5.124 s]
[INFO] openHAB Core :: Bundles :: Model Sitemap Runtime ... SUCCESS [  4.530 s]
[INFO] openHAB Core :: Bundles :: Model Thing Runtime ..... SUCCESS [  5.202 s]
[INFO] openHAB Core :: Bundles :: UI Icon Support ......... SUCCESS [  5.701 s]
[INFO] openHAB Core :: Bundles :: JSON Storage ............ SUCCESS [  7.751 s]
[INFO] openHAB Core :: Bundles :: MapDB Storage ........... SUCCESS [  8.799 s]
[INFO] openHAB Core :: BOM :: openHAB Core ................ SUCCESS [  0.047 s]
[INFO] openHAB Core :: BOM :: openHAB Core Index .......... SUCCESS [  4.468 s]
[INFO] openHAB Core :: Bundles :: Model Lazy Generation ... SUCCESS [  6.529 s]
[INFO] openHAB Core :: Features ........................... SUCCESS [  0.032 s]
[INFO] openHAB Core :: Features :: Karaf .................. SUCCESS [  0.359 s]
[INFO] openHAB Core :: Features :: Karaf :: Target Platform SUCCESS [  8.810 s]
[INFO] openHAB Core :: Features :: Karaf :: Core .......... SUCCESS [ 54.050 s]
[INFO] openHAB Core :: Tools .............................. SUCCESS [  0.031 s]
[INFO] openHAB Core :: Tools :: Archetypes ................ SUCCESS [  2.922 s]
[INFO] openHAB Core :: Tools :: Archetypes :: Binding ..... SUCCESS [  3.061 s]
[INFO] openHAB Core :: Integration Tests .................. SUCCESS [  0.094 s]
[INFO] openHAB Core :: Integration Tests :: Tests ......... SUCCESS [01:23 min]
[INFO] openHAB Core :: Integration Tests :: Audio Test .... SUCCESS [ 24.317 s]
[INFO] openHAB Core :: Integration Tests :: OAuth2Client Tests SUCCESS [ 15.035 s]
[INFO] openHAB Core :: Integration Tests :: Automation Tests SUCCESS [ 16.031 s]
[INFO] openHAB Core :: Integration Tests :: Binding XML Tests SUCCESS [ 15.686 s]
[INFO] openHAB Core :: Integration Tests :: 1.x Compatibility Layer Tests SUCCESS [ 35.747 s]
[INFO] openHAB Core :: Integration Tests :: Configuration Core Tests SUCCESS [ 14.031 s]
[INFO] openHAB Core :: Integration Tests :: Configuration mDNS Discovery Tests SUCCESS [ 16.240 s]
[INFO] openHAB Core :: Integration Tests :: Configuration Discovery Tests SUCCESS [ 29.887 s]
[INFO] openHAB Core :: Integration Tests :: Network I/O HTTP Tests SUCCESS [  9.815 s]
[INFO] openHAB Core :: Integration Tests :: Network I/O Tests SUCCESS [ 13.933 s]
[INFO] openHAB Core :: Integration Tests :: IO REST Core Tests SUCCESS [ 19.698 s]
[INFO] openHAB Core :: Integration Tests :: Magic Bundle Tests SUCCESS [ 15.312 s]
[INFO] openHAB Core :: Integration Tests :: Model Core Tests SUCCESS [ 26.970 s]
[INFO] openHAB Core :: Integration Tests :: Model Language Server Protocol Tests SUCCESS [ 27.593 s]
[INFO] openHAB Core :: Integration Tests :: Model Persistence Tests SUCCESS [ 22.002 s]
[INFO] openHAB Core :: Integration Tests :: Model Thing Test Support SUCCESS [  7.795 s]
[INFO] openHAB Core :: Integration Tests :: Model Thing Tests SUCCESS [ 29.149 s]
[INFO] openHAB Core :: Integration Tests :: Semantics Tests SUCCESS [ 12.223 s]
[INFO] openHAB Core :: Integration Tests :: Storage JSON Tests SUCCESS [ 12.055 s]
[INFO] openHAB Core :: Integration Tests :: Thing Tests ... SUCCESS [01:46 min]
[INFO] openHAB Core :: Integration Tests :: Thing XML Tests SUCCESS [ 17.139 s]
[INFO] openHAB Core :: Integration Tests :: Transform Test  SUCCESS [ 11.005 s]
[INFO] openHAB Core :: Integration Tests :: UI Tests ...... SUCCESS [ 23.888 s]
[INFO] openHAB Core :: Integration Tests :: UI Icon Tests . SUCCESS [ 16.122 s]
[INFO] openHAB Core :: Integration Tests :: Voice Test .... SUCCESS [ 15.888 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25:43 min
[INFO] Finished at: 2019-08-16T21:57:26+02:00
[INFO] Final Memory: 419M/992M
[INFO] ------------------------------------------------------------------------
```

**Comment by cweitkamp** [comment]
Sounds good. Same for me.

**Pull request merged**
