### PR TITLE
Added PullApprove config

### PR DESCRIPTION
**Pull request by cweitkamp**
Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
Hm, it does not seem to work.

**Comment by cweitkamp** [comment]
The YAML is bases on PullApprove v2 which is used in openHAB 2 Add-ons. Maybe we have PullApprove v3 over here now. How can we validate that?

**Comment by maggu2810** [comment]
I cannot press the configure button: https://github.com/openhab/openhab-core/settings/installations
I assume @kaikreuzer is the single one that can have a look at.

**Comment by kaikreuzer** [comment]
Hm, for openhab2-addons we use a Pullapprove webhook, while here for openhab-core the PullApprove Github app is now installed. I cannot see any version mentioned with it, though, but it is likely that this is the newest version.
If we align the repos, it'd probably make sense to use the Github app also for openhab2-addons, but I'll only change the config once we have it working here.

**Pull request merged**
