### PR TITLE
UID: allow to encode arbitrary string (+decode)

### PR DESCRIPTION
**Pull request by maggu2810**
Related to: #847, #848

### CODE REVIEW

**Comment by maggu2810** [comment]
I will move the static functions (encode and decode) to an UIDUtils class.

**Comment by maggu2810** [comment]
@davidgraeff Is this still useful for you?

**Comment by davidgraeff** [comment]
Yes, it will be used to deduct thing and channel ids based on MQTT topics.

**Comment by maggu2810** [comment]
ping @openhab/core-maintainers

**Pull request merged**
