### PR TITLE
Fix inital loading and improve code for YAML model

### LINKED ISSUE #4196: customTags.yaml not loading after reboot
## Expected Behavior
I have created some custom tags. When I reboot, they should all remain.

## Current Behavior
When I reboot, my customTags.yaml file is not loaded, and every item that had a custom tag goes haywire in my model view.
If I open and resave the file, it works as expected.

## Steps to Reproduce (for Bugs)
1- Create a custom tag
2- Reboot openhab

### PR DESCRIPTION
**Pull request by J-N-K**
Fixes #4196

### CODE REVIEW

**Comment by lolodomo** [comment]
LGTM
Looks like you made another change not linked to the referenced issue by enabling `Feature.PARSE_BOOLEAN_LIKE_WORDS_AS_STRINGS`.

**Comment by J-N-K** [comment]
Yes, that was part of #4085, if this is not set, the strings `ON`, `YES`, `TRUE` (and abbreviations like `Y` or variants like `yes`/`Yes`) are parsed as boolean `true`. This is obviously wrong for our usage, only `true` should be parsed as `true`.

**Review by holgerfriedrich — APPROVED** [review]
LGTM

**Comment by jimtng** [comment]
Typo in PR title `inital`

**Comment by lolodomo** [comment]
I can confirm it works as expected in snapshot 4064.

**Pull request merged**
