### PR TITLE
Align I18nProviderImpl and thing description XSD

### PR DESCRIPTION
**Pull request by J-N-K**
See https://github.com/openhab/openhab-core/pull/4217#issuecomment-2118651155

### CODE REVIEW

**Comment by holgerfriedrich** [comment]
can you please double check the following types which do not occur in the whole core and add-ons repo:
```
Number:AmountOfSubstance
Number:CatalyticActivity
Number:Currency
Number:ElectricCapacitance
Number:ElectricConductance
Number:ElectricConductivity
Number:ElectricInductance
Number:Force
Number:LuminousFlux
Number:LuminousIntensity
Number:MagneticFlux
Number:MagneticFluxDensity
Number:RadioactiveActivity
Number:SolidAngle
```

The following types have an implementation in core, but are not found in add-ons:
```
Number:RadiationDoseAbsorbed
Number:RadiationDoseEffective
```

**Comment by J-N-K** [comment]
I only aligned the item-types to the supported units (i.e. those that have a default dimension). These were added in #3143, I can't remember exactly why I choose all those, but they are consistent with the list of supported dimensions [here](https://www.openhab.org/docs/concepts/units-of-measurement.html), so I guess we should not remove them.

**Review by holgerfriedrich — APPROVED** [review]
LGTM, thanks

**Comment by kaikreuzer** [comment]
I've updated the website accordingly with https://github.com/openhab/website/pull/462

**Pull request merged**
