### PR TITLE
[core] Revert ThingImpl and BridgeImpl changes as the storage uses those implementations

### LINKED ISSUE #717: after update to 2.5.0~S1569 my JSONDB throws errors
After update to snapshot 1569 I get errors in the log and quite a lot of my things are missing in the setup now.

```
2019-04-13 21:23:14.070 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@d0ddad'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.channels[0]
2019-04-13 21:23:14.074 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@1e1dc61'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.channels[0]
2019-04-13 21:23:14.077 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@cc6576'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.channels[0]
2019-04-13 21:23:14.081 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@8e7bac'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.channels[0]
2019-04-13 21:23:14.085 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@f9fae5'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $.channels.segments
2019-04-13 21:23:14.088 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@14c2c4f'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.channels[0]
2019-04-13 21:23:14.092 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@a80805'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.channels[0]
2019-04-13 21:23:14.095 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@1c25627'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.channels[0]
2019-04-13 21:23:14.099 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@23bba8'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.channels[0]
2019-04-13 21:23:14.102 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@dbc9f7'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.channels[0]
2019-04-13 21:23:14.106 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@c71349'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.channels[0]
2019-04-13 21:23:14.109 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@12b0218'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.channels[0]
2019-04-13 21:23:14.112 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@8a18ae'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $.channels.segments
2019-04-13 21:23:14.115 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@54e939'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $.channels.segments
2019-04-13 21:23:14.118 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@51f261'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $.channels.segments
2019-04-13 21:23:14.121 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@1cd1df1'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.channels[0]
2019-04-13 21:23:14.126 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@1dd35a7'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.channels[0]
2019-04-13 21:23:14.130 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@829078'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.channels[0]
2019-04-13 21:23:14.133 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@4073ae'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.channels[0]
2019-04-13 21:23:14.203 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@1b5bc6'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.channels[0]
2019-04-13 21:23:14.207 [ERROR] [me.storage.json.internal.JsonStorage] - Couldn't deserialize value 'org.eclipse.smarthome.storage.json.internal.StorageEntry@1722ef'. Root cause is: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $.channels.segments
```

### PR DESCRIPTION
**Pull request by cweitkamp**
- Partially revert #693

Closes #717 - But did not solve the root cause

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by cweitkamp** [comment]
@kaikreuzer @wborn May I ask you to start a snapshot build?

**Comment by kaikreuzer** [comment]
Started!

**Comment by MattL0** [comment]
Works perfect . Thanks

**Comment by cweitkamp** [comment]
Thank you.

**Pull request merged**
