### PR TITLE
Add compilation errors & SAT GitHub annotations

### PR DESCRIPTION
**Pull request by ghys**

### CODE REVIEW

**Comment by wborn** [comment]
Many static analysis tools nowadays also support the SARIF format.

It seems you can also use these files to integrate with the GitHub code scanning, see:

https://docs.github.com/en/code-security/code-scanning
https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/about-integration-with-code-scanning

Might also be worth to look into what this exactly does and how well it works when PRs are created. :wink:

**Comment by ghys** [comment]
So in the end I combined these two PRs into one:
- one that reports & displays Java compilation errors as annotations ([example](https://github.com/ghys/openhab-core/pull/1/files#diff-899c7989dc13bc74a38689d94df1fdf53a812cf558269e78df4e7258a11b1c47))
- one that reports SAT errors as annotations ([example](https://github.com/ghys/openhab-core/pull/2/files#diff-899c7989dc13bc74a38689d94df1fdf53a812cf558269e78df4e7258a11b1c47))

(Try Ctrl-F5 if the annotations don't show)

I eventually fixed some unrelated problems in this PR,  that's because the action originally had a bug and was treating every problem as errors unless there were warnings - so info levels were treated as failures... If they are not wanted I can revert them.

**Comment by ghys** [comment]
> https://docs.github.com/en/code-security/code-scanning
https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/about-integration-with-code-scanning

Those are interesting as well but it might be better to postpone them to another workflow dedicated to code checks?

**Review by wborn — APPROVED** [review]
Thanks a lot. :+1: 
I gave it a brief test in my own repo and it seems to work. :slightly_smiling_face: 
So let's test how it works for real!

**Comment by ghys** [comment]
If you think I'd be a good addition to other repos (notably openhab-addons) I can open similar PRs to those too.

**Comment by wborn** [comment]
Yes it would be nice to test it in the add-ons repo too!

I plan on adding GHA to more repos when all bugs are sorted out and we're happy with the features in the most active repos. :slightly_smiling_face: That prevents a lot of PRs to tune GHA everywhere. It might also be worth looking into [reusing workflows](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows) if we add GHA to many repos.

**Comment by vivox80pro** [comment]
> 

#16

**Pull request merged**
