### PR TITLE
 register static context handler

### LINKED ISSUE #422: html/static folder still throws 404 after ui.start bundle commit
The issue listed here: https://github.com/openhab/openhab-core/issues/420 should be fixed with https://github.com/openhab/openhab-core/pull/421 but with build #1409 apt version: 2.4.0~20181102181428-1 it still throws 404 on the static folder.

### PR DESCRIPTION
**Pull request by kaikreuzer**
fixes #422

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Jenkins again has issues with the incremental build, but Travis is happy!

**Comment by martinvw** [comment]
Great, but cannot merge from my phone, great if you could do that 👍

**Comment by kaikreuzer** [comment]
You seem to have a weird phone ;-)

**Comment by martinvw** [comment]
> You seem to have a weird phone ;-)
 
I can only easily merge completely green pr’s 😉

**Comment by maggu2810** [comment]
You can handle it if you request the "desktop page" in your phone's browser.

**Pull request merged**
