### PR TITLE
Add log web socket

### PR DESCRIPTION
**Pull request by J-N-K**
This adds a web socket connection for receiving logs. Similar to #3345 but for web sockets instead of SSE. 

@ghys FYI. It works fine with the `LogReaderService`and the `LogListener`.

### CODE REVIEW

**Comment by spacemanspiff2007** [comment]
Would it be also possible to add a short example to the docs how to use this?

**Comment by J-N-K** [comment]
Sure. Short description: open a web socket connection to `/ws/logs` and receive all logs. Sending an array of regex will enable a filter: only lines where the logging bundle matches at least one regex will be sent over the connection (e.g. `["org\.openhab\.core\..*"]` would only allow core messages to pass). An empty array again enables "full logging".

**Comment by spacemanspiff2007** [comment]
Perfect. The regex matches the whole line? So that's what I would want to use to filter e.g. for the levels INFO, WARNING and ERROR. Or is there an option to set the log level?

**Comment by spacemanspiff2007** [comment]
Just to clarify - I am looking for a way to subscribe to all messages of level INFO and above (e.g. WARNING, ERROR, CRITICAL and whatever other levels there may be).

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Comment by spacemanspiff2007** [comment]
What if I want to filter by log level and not by regex.
How can I set the filter to get everything of log level including INFO and above?
Or is there an overview of the availalbe log levels? I'm guessing the log levels can be added dynamically - are there levels which are specific to openHAB?

**Comment by spacemanspiff2007** [comment]
@J-N-K :
Is it possible to filter by log level? E.g. if I want only messages with level INFO and above?

**Comment by J-N-K** [comment]
No, this passes on what goes to the logger. I also think it would be confusing, because if you add `TRACE` but no logger is configured for TRACE logging, you would not get any other information.

**Comment by spacemanspiff2007** [comment]
> No, this passes on what goes to the logger. I also think it would be confusing, because if you add `TRACE` but no logger is configured for TRACE logging, you would not get any other information.

You misunderstand. If I configure `TRACE` I'd expect to get `TRACE` and above, e.g. all messages with`TRACE`, `DEBUG`, `INFO`, `WARNING` and `ERROR`.
If I configure `INFO` I'd expect to get `INFO`, `WARNING` and `ERROR`.

Or do you have another idea how I can get all `WARNING` and `ERROR` messages without client side filtering.

**Pull request merged**
