### PR TITLE
Revert LinkedTransferQueue high CPU usage workaround

### PR DESCRIPTION
**Pull request by wborn**
Reverts the workaround (https://github.com/openhab/openhab-core/pull/3756) that was introduced for [JDK-8301341](https://bugs.openjdk.org/browse/JDK-8301341) because it is fixed in OpenJDK 21 (https://github.com/openjdk/jdk/pull/14317).

### CODE REVIEW

**Review by holgerfriedrich — APPROVED** [review]
LGTM, thanks for cleaning this up!

**Comment by ccutrer** [comment]
Trying to run 5.0.0-SNAPSHOT, none of my UPnP bundles will start, because this PR removes OHUpnpServiceConfiguration:

```
openhab> list | grep Waiting
279 │ Waiting │  80 │ 3.0.1                 │ jUPnP Core Library
295 │ Waiting │  80 │ 5.0.0.202412190408    │ openHAB Add-ons :: Bundles :: Onkyo Binding
303 │ Waiting │  80 │ 5.0.0.202412170258    │ openHAB Core :: Bundles :: uPnP Suggested Add-on Finder
306 │ Waiting │  80 │ 5.0.0.202412170301    │ openHAB Core :: Bundles :: Configuration UPnP Discovery
316 │ Waiting │  80 │ 5.0.0.202412170252    │ openHAB Core :: Bundles :: UPnP Transport
openhab> diag 279
jUPnP Core Library (279)
------------------------
Status: Waiting
Declarative Services
org.jupnp.OSGiUpnpServiceConfigurationEnabler (327)
org.jupnp.util.SpecificationViolationReporterConfig (329)
org.jupnp.UpnpServiceImpl (328)
  missing references: UpnpServiceConfiguration
```

Is there something in my OSGi config I need to remove? For now I've locally reverted this commit, and removed the overrides in `OHUpnpServiceConfiguration`, then installed the removed bundle, and things seem to be working.

**Comment by wborn** [comment]
https://github.com/openhab/openhab-distro/pull/1705 is also necessary for reverting it so it uses the default config. It only got recently merged.

**Comment by wborn** [comment]
Maybe the config value state is still persisted as false and we need to set it to true instead so it does not wait.

**Comment by ccutrer** [comment]
That did the trick (removing `autoEnable` from `$(userdata)/etc/org.jupnp.cfg`). Thanks!

**Comment by holgerfriedrich** [comment]
FYI: I have seen that jupnp is in state "waiting" on my dev system as well. Installing the current snapshot fixed it for me. 👍
No manual change needed.

**Comment by wborn** [comment]
Great! I'll also check what happens when I do a 4.3 🏗️ 5.0  Docker upgrade.

**Pull request merged**
