### PR TITLE
Fix CommunicationManager command handling

### LINKED ISSUE #3694: Profile JS Transformation Item ->  Thing for Datatype Datetime not triggered
JS-Transformation in a profile for direction item to thing is not triggered in case input value is of datatype datetime. 

Details  see also reference https://community.openhab.org/t/oh4-m4-problem-with-profile-js-transformation-of-datetime-type/147662

OH4 Milstone 4

### PR DESCRIPTION
**Pull request by J-N-K**
Fixes #3694

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Lgtm in general, but I also cannot judge on possible side effects. It might be too risky to merge it one day before the RC.
Shall we better wait and only merge it for 4.1?

**Comment by J-N-K** [comment]
The problem is that I'm not sure if this worked before (in 3.4) and is a regression from the `CommunicationManager` refactoring.

**Comment by kaikreuzer** [comment]
It is a fairly rare use case, so I'd rather live with that regression than to potentially introduce other ones unintentionally now.

**Comment by J-N-K** [comment]
Fine. We can also do a 4.0.1 if it turns out to be a bigger issue.

**Comment by wborn** [comment]
> Shall we better wait and only merge it for 4.1?

Perhaps we can merge it now?

**Review by kaikreuzer — APPROVED** [review]
Good idea. :-)

**Pull request merged**
