### PR TITLE
DSL rule: new sendCommand with a State as parameter

### LINKED ISSUE #950: [Rules DSL] enhance sendCommand to handle OnOffType
Forgive my probably incorrect terminology.

`myItem.sendCommand(xxx)`
We frequently advise using sendCommand method as it is "better out sorting out argument types" for xxx.   I imagine it usually reduces xxx to its string equivalent.

Working with Switch type Items, it is not uncommon to base a **command** on some other Switch's **state**.
`mySwitch.sendCommand(otherSwitch.state)`
This results in an error
```
2019-08-01 00:13:16.139 [ERROR] [ntime.internal.engine.RuleEngineImpl] - Rule 'test': An error occurred during the script execution: Could not invoke method: org.eclipse.smarthome.model.script.actions.BusEvent.sendCommand(org.eclipse.smarthome.core.items.Item,java.lang.Number) on instance: null
```
Circumvention is simple
`mySwitch.sendCommand(otherSwitch.state.toString)`
but the error is rather unexpected from the user viewpoint.   I guess an OnOffType state of ON is not quite the same as OnOffType command ON ??

This is a request for enhancement of sendCommand method to handle Item state as argument.

Use case-
https://community.openhab.org/t/two-switches-one-light-eg-staircase-switch-rule/79035/5

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #950

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
This is not tested as I don't have any IDE in which I can run openHAB.

**Comment by openhab-5iver** [comment]
You could build org.openhab.core.model.script, drop it into a system running a recent snapshot, clear the cache, and test it that way. That's how I ended up testing a lot of the automation changes without an IDE to debug in.

**Comment by lolodomo** [comment]
I have no problem to test bindings in such a way but to replace a core bundle in my production environment, I am less aware how to achieve that **properly**. What do you mean exactly by "clear the cache" ? And should I first uninstall or stop the existing bundle before putting the new jar in my addons folder ?

**Comment by openhab-5iver** [comment]
Stop OH, copy in the file (/runtime/system/org/openhab/core/bundles/...) overwriting the old one or rename the file extension of the old one to revert later, delete /userdata/cache/org.eclipse.osgi (I found that was all I needed to clear for testing automation), restart OH. On recent snapshots, I've found that I need to restart twice after clearing the cache to startup without errors.

Hope this helps!

**Comment by lolodomo** [comment]
Never try to do that in such a way. Will try.

**Comment by J-N-K** [comment]
You can also replace a single bundle with `bundle:update <number> <uri>`. `<uri>` can be something like `file:///home/lolodomo/my-cool-new-bundle.jar`. Going back is the same, just update to the „old“ (unpatched) version.

**Comment by lolodomo** [comment]
Looks cleaner ;)

**Comment by openhab-5iver** [comment]
Wow... I've done that with addons, but never thought to do it with a core bundle. That will definitely save some time... if it works!

**Comment by lolodomo** [comment]
I can confirm that this enhancement is working perfectly. I tested it with a Switch item and a Number item.

PS: regarding the way to update the bundle, the solution with bundle:update is ok but the bundle remained in status "Waiting". I restarted openHAB and that was OK with the new bundle.

**Comment by J-N-K** [comment]
Maybe you need to `bundle:resolve <number>` and/or `bundle:start <number>`. `bundle:diag <number>` tells you what is missing to start the bundle.

**Comment by lolodomo** [comment]
Yes, I should have tried at least bundle:start ! Will try the next time.

**Comment by lolodomo** [comment]
@J-N-K : I tried again to restore the old bundle.
`bundle:start 171` does not help, the bundle remains in state Waiting.
`bundle:resolve 171` returns nothing.
bundle:diag 171 returns:
```
openHAB Core :: Bundles :: Model Script (171)
---------------------------------------------
Status: Waiting
Declarative Services
org.eclipse.smarthome.model.script.extension.ScriptEngineConsoleCommandExtension (291)
  missing references: ScriptEngine
```
Here are the bundles in a Waiting state:
```
164 x Waiting x  80 x 2.5.0.201907292052    x openHAB Core :: Bundles :: Language Server
170 x Waiting x  90 x 2.5.0.201907292033    x openHAB Core :: Bundles :: Model Rules Runtime
171 x Waiting x  80 x 2.5.0.201907292031    x openHAB Core :: Bundles :: Model Script
173 x Waiting x  80 x 2.5.0.201907292052    x openHAB Core :: Bundles :: Model Script Runtime
```
I tried to start 170 and 173 in addition to 171 but with no more success.

**Comment by lolodomo** [comment]
What is done here is that we try to get a command from the state. It looks like what you request.
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/actions/BusEvent.java#L85
If this is failing, th efollowing message will be logged: Cannot convert '{}' to a command type which item '{}' accepts: {}.

**Comment by cweitkamp** [comment]
@lolodomo Do you agree with closing this PR?

**Comment by lolodomo** [comment]
It is really a pity and I don't understand the reason why this enhancement is rejected
But yes, if mainteners don't want this improvement, it has no sense to keep it open.

**Pull request closed without merging**
