### PR TITLE
Added i18n feature for profiles

### PR DESCRIPTION
**Pull request by cweitkamp**
- Added i18n feature for profiles

One comment: There is an internal class `LocalizedProfileTypeKey` which is used in a very similar way for other translatable objects (e.g. https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.thing/src/main/java/org/eclipse/smarthome/core/thing/DefaultSystemChannelTypeProvider.java#L281-L328 and https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.config.xml/src/main/java/org/eclipse/smarthome/config/xml/AbstractXmlBasedProvider.java#L40-L79). I am not very happy with that and think about a refactoring. Let me know your opinion.

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
What about a `LocalizedKey<K,V>`?

* `SystemProfileFactory.java.LocalizedProfileTypeKey` can be replaced by `LocalizedKey<UID, @Nullable String>`
* `DefaultSystemChannelTypeProvider.LocalizedChannelTypeKey` can be replaced by `LocalizedKey<UID, @Nullable String>
* `AbstractXmlBasedProvider.LocalizedKey` can be replaced by `LocalizedKey<Object, @Nullable String>`

Okay, while reading the classes, I assume we don't need generics at all.

`LocalizedKey` can use two members:
* `final Object key`
* `final @Nullable String locale`

The type of the key does not matter.

**Comment by cweitkamp** [comment]
Yes, sounds good. Moving it to an own class in the i18n package.

Another question which came to my mind was if it is the right place to use the localized caches in the `XXXTypeProvider`s. Or should we maybe move them over to the `XXXTypeI18nLocalizationService`s components which makes imho much more sense because the services could be used in multiple places and the benefits may be even bigger.

Independently of the final approach we should do it in a separate PR to keep the history clean.

**Comment by maggu2810** [comment]
> Independently of the final approach we should do it in a separate PR to keep the history clean.

:+1: 

IMHO also the `LocalizedKey` can be done in another PR as it is not about i18n feature in profiles itself.
Will you volunteer for that improvement? :wink:

**Comment by cweitkamp** [comment]
> Will you volunteer for that improvement?

Of course. I already have it in the pipe.

**Pull request merged**
