### PR TITLE
Added arm64 support for serial port access

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by martinvw** [comment]
Something for the release notes?

**Comment by kaikreuzer** [comment]
Good point. I have updated the title and added the "enhancement" label.
The feature is related to https://community.openhab.org/t/openhab-on-synology-ds418-serial-binding-problem/57161/25.

**Comment by martinvw** [comment]
oO unhappy builds

**Comment by kaikreuzer** [comment]
https://ci.openhab.org/job/openHAB-Deps-Repo/45/ had to finish first.

**Comment by kaikreuzer** [comment]
@martinvw all green now!

**Pull request merged**
